<?php
return [
"Generated By" => "দ্বারা তৈরি করা হয়েছে",

"Please Enter Your Credit details" => "অনুগ্রহ করে আপনার ক্রেডিট বিবরণ লিখুন",

"Please Enter Your Debit details" => "অনুগ্রহ করে আপনার ডেবিট বিবরণ লিখুন",

"This was selected before Without Changing this you cannot submit this" => "এটি পরিবর্তন করার আগে এটি নির্বাচন করা হয়েছে আপনি এটি জমা দিতে পারবেন না",

"This item is already added" => "এই আইটেম ইতিমধ্যেই যোগ করা হয়েছে",

"Please Select Customer First" => "অনুগ্রহ করে স্বনির্বাচিত প্রথমটি বেছে নিন",

"Your due is greater than your credit limit" => "আপনার ক্রেডিট সীমার চেয়ে বড়",

"Something went wrong" => "কিছু একটা ভুল হয়েছে",

"Approval has been changed Successfully" => "অনুমোদন সফলভাবে পরিবর্তন করা হয়েছে",

"browse" => "ব্রাউজ",

"type" => "ধরন",

"delete" => "মুছে ফেলো",

"select" => "নির্বাচন করুন",

"Delete" => "মুছে ফেলো",

"Select" => "নির্বাচন করুন",

"Type" => "ধরন",

"Browse" => "ব্রাউজ",

"Add Value" => "মান যোগ করো",

"Success" => "সফল",

"Error" => "ত্রুটি",

"Show" => "দেখাও",

"Purchase Price" => "পার্স প্রাইস",

"Quick Search" => "দ্রুত অনুসন্ধান",

"Browse file" => "ফাইল ব্রাউজ করুন",

"Price" => "মূল্য",

"Branch" => "ব্রাঞ্চ",

"Amount" => "অ্যাকাউন্ট",

"Value" => "মান",

"Tax" => "ট্যাক্স",

"Payment Method" => "পেমেন্ট পদ্ধতি",

"Cash" => "ক্যাশ",

"Bank Name" => "ব্যাংক নাম",

"Account No" => "অ্যাকাউন্ট নেই",

"Total" => "মোট",

"Alert Qty" => "অ্যালার্ট পরিমান",

"Selling Price" => "বিক্রেতা মূল্য",

"Product Images" => "প্রোডাক্ট ইমেজ",

"Quantity" => "কোয়ান্টিটি",

"quantity" => "কোয়ান্টিটি",

"amount" => "অ্যাকাউন্ট",

"Updated Successfully" => "সফলভাবে আপডেট করা হয়েছে",

"Account Owner" => "অ্যাকাউন্ট মালিক",

"Enter Amount" => "অ্যাকাউন্ট লিখুন",

"Narration" => "নার্সট্রেশন",

"Select one" => "একটি নির্বাচন করুন",

"Please Enter Your credit details" => "অনুগ্রহ করে আপনার ক্রেডিট বিবরণ লিখুন",

"Browse File" => "ফাইল ব্রাউজ করুন",

"Select One" => "একটি বেছে নিন",

"Min. Selling Price" => "মিন. বিক্রেতা মূল্য",

"success" => "সফল রং",

"total" => "মোট",

"price" => "মূল্য",

"tax" => "ট্যাক্স",

"error" => "ত্রুটি",

"entries" => "এন্ট্রি",

"of" => "হতে",

"value" => "মান",

"Select State" => "স্টেট নির্বাচন করুন",

"Select City" => "শহর বেছে নিন",

"No data available in table" => "টেবিলে কোন তথ্য বিদ্যমান নেই",

"Showing page" => "পৃষ্ঠা শোনান",

"No records available" => "কোনো রেকর্ড বিদ্যমান নেই",

"filtered from" => "ফিল্টার করা হয়েছে",

"total records" => "মোট রেকর্ড",

"What you are looking is not found" => "আপনি যা খুঁজছেন তা খুঁজে পাওয়া যায়না",

"Opps" => "ওপস!",

"Something went wrong. If you are seeing this message multiple times, please contact Spondon IT authors." => "কিছু একটা ভুল হয়েছে. আপনি যদি একাধিক বার এই বার্তাটি দেখতে পাবেন, তাহলে দয়া করে স্প্যানটনের সাথে যোগাযোগ করুন.",

"Something is not right" => "কিছু একটা সঠিক নয়",

"Validation Error" => "বৈধতা সংক্রান্ত ত্রুটি",

"Please Enter Your debit details" => "অনুগ্রহ করে আপনার ডেবিট বিবরণ লিখুন",
    'Search' => 'অনুসন্ধান'

];
