<?php
return [
"A Product Has been Created" => "একটি প্রোডাক্ট তৈরি করা হয়েছে",

"Your info has been updated as a Staff by" => "আপনার তথ্য একটি স্টাফ হিসাবে হালনাগাদ করা হয়েছে",

"Your info Have Been updated by" => "আপনার তথ্য দ্বারা সর্বশেষ হালনাগাদ করা হয়েছে",

"as a Staff for" => "একজন স্টাফ হিসেবে",

"Congrats ! You have been added as a Staff by" => "আপনাকে একজন স্টাফ হিসেবে যোগ করা হয়েছে",

"Staff Added" => "স্টাফ যোগ করা হয়েছে",

"A Voucher has been created by" => "একটি ভাউচার তৈরি করা হয়েছে",

"Voucher Create Reminder" => "ভাউচার তৈরি রিমেন্ডার",

"Voucher Update Reminder" => "ভাউচার আপডেট রিমেন্ডার",

"A Voucher has been Update by" => "একটি ভাউচার আপডেট করেছেন- ",

"A Voucher has been Delete by" => "একটি ভাউচার মুছে ফেলেছেন- ",

"Voucher Approve Reminder" => "ভাউচার অনুমোদন বিজ্ঞপ্তি",

"A Voucher has been Approve by" => "একজন ভাউচার দ্বারা আপাতত করা হয়েছে",

"You Have Been added as" => "আপনি হিসাবে যোগ করেছেন",

"Added" => "যোগ করা হয়েছে",

"Congrats ! You Have Been added as" => "অভিনন্দন! আপনি হিসাবে যোগ করা হয়েছে ",

"Your info Have Been updated as" => "আপনার তথ্য যেমন আপডেট করা হয়েছে",

"A Branch Has been Created" => "একটি শাখা তৈরি করা হয়েছে",

"Stock Transfer Reminder" => "স্টক ট্রান্সফার রিমেন্ডার",

"Transfer Has been Made From" => "ট্রান্সফার তৈরি করা হয়েছে",

"A WareHouse Has been Created" => "একটি ওয়্যারহাউস তৈরি করা হয়েছে",

"Salary Has been generated by" => "সালায়ারি তৈরি করা হয়েছে",

"Your Net Salary was" => "আপনার নেট সালায়ারি ছিল",

"Salary Generate Reminder" => "বেতন জেনারেট রিমাইন্ডার",

"A purchase has been made by" => "একটি ক্রয় দ্বারা তৈরি করা হয়েছে",

"A Purchase has been created by" => "একটি ক্রয় দ্বারা তৈরি করা হয়েছে",

"Invoice No:" => "আওয়াজ নং",

"Amount: " => "মান: ",

"Purchase Update Reminder" => "ক্রয় আপডেট রিমাইন্ডার",

"A Purchase has been approved by" => "একটি ক্রয় দ্বারা অনুমোদিত হয়েছে",

"Product Receive Reminder" => "প্রোডাক্ট গ্রহণ রিমেন্ডার",

"Products Has been Received by" => "প্রোডাক্টস পাওয়া গেছে",

"Product Has been Added as Opening Stock" => "প্রোডাক্ট ওপনিং স্টক হিসাবে যোগ করা হয়েছে",

"Quotation Create Reminder" => "উদ্ধৃতি তৈরি করো",

"A Quotation, invoice no : " => "একটি উদ্ধৃতি, আমন্ত্রণ না: ",

"Has been Created" => "তৈরি করা হয়েছে",

"Sale Create Reminder" => "বিক্রয় অনুস্মারক তৈরি করুন",

"A Sale has been created by" => "একটি সেলে তৈরি করা হয়েছে",

"Sale Delete Reminder" => "বিক্রয় ডিলিট রিমাইন্ডার",

"A Sale has been destroyed by" => "একটি বিক্রয় দ্বারা ধ্বংস করা হয়েছে",

"A Sale has been approved by" => "একটি সালকে অনুমোদন করা হয়েছে",

"Leave Reminder" => "রিমেইন্ডার ত্যাগ করা হবে",

"A Leave Has been Applied By " => "একটি ছাড় প্রয়োগ করা হয়েছে ",

"A Leave Has been Edited By " => "একটি ছাঁদ সম্পাদনা করা হয়েছে ",

"A leave request has been made by " => "একটি ছাড়ার অনুরোধ করা হয়েছে ",

"for being " => "থাকার জন্য ",

"has been approved" => "অনুমোদন করা হয়েছে",

"Congrats ! Staff Has been added by " => "স্টাফ যোগ করা হয়েছে ",

"added" => "যোগ করা হয়েছে",

"by" => "দ্বারা",

"By" => "দ্বারা",

];