<?php


namespace Tests\Browser\Modules\Style;


use Illuminate\Foundation\Testing\WithFaker;
use Laravel\Dusk\Browser;
use Modules\Setting\Entities\Theme;
use Tests\DuskTestCase;

class ThemeCustomizationTest extends DuskTestCase
{
    use WithFaker;

    public function tearDown(): void
    {
        $themes = Theme::where('id', '!=', 1)->get();
        foreach ($themes as $theme){
            $theme->delete();
        }
        $theme = Theme::where('id', 1)->first();
        $theme->is_default = 1;
        $theme->save();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testVisitPageWithoutLogin()
    {

        $this->browse(function (Browser $browser) {
            $browser->visit('/style/themes')
                ->assertPathIs('/login')
                ->visit('/style/themes/create')
                ->assertPathIs('/login');
        });
    }

    public function testVisitPageWithLogin()
    {

        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/style/themes')
                ->assertSee('Theme Customization');
        });
    }

    public function testCreateTheme()
    {

        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/style/themes/create')
                ->assertSee('Color Theme')
                ->type('#title', $this->faker->name)
                ->click('#main-content > div.row.justify-content-center > div.col-lg-12 > div > form > div:nth-child(2) > div:nth-child(3) > div')
                ->click('#main-content > div.row.justify-content-center > div.col-lg-12 > div > form > div:nth-child(2) > div:nth-child(3) > div > ul > li:nth-child(2)')

                ->type('#background_color', $this->faker->hexColor)
                ->type('#base_color', $this->faker->hexColor)
                ->type('#gradient_1', $this->faker->hexColor)
                ->type('#gradient_2', $this->faker->hexColor)
                ->type('#gradient_3', $this->faker->hexColor)
                ->type('#scroll_color', $this->faker->hexColor)
                ->type('#text-color', $this->faker->hexColor)
                ->type('#text_white', $this->faker->hexColor)
                ->type('#bg_white', $this->faker->hexColor)
                ->type('#text_black', $this->faker->hexColor)
                ->type('#bg_black', $this->faker->hexColor)
                ->type('#border_color', $this->faker->hexColor)
                ->type('#input__bg', $this->faker->hexColor)
                ->type('#success', $this->faker->hexColor)
                ->type('#warning', $this->faker->hexColor)
                ->type('#danger', $this->faker->hexColor)
                ->click('#main-content > div.row.justify-content-center > div.col-lg-12 > div > form > div:nth-child(5) > div:nth-child(2) > div > button:nth-child(2)')
                ->waitFor('.toast-message')
                ->assertSee('New Theme Created Successful')
            ;
        });
    }



    public function testCloneTheme(){
        $this->testVisitPageWithLogin();
        $this->browse(function (Browser $browser){
            $browser
                ->visit('/style/themes')
                ->assertSee('Theme Customization')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(6) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(6) > div > div > a:nth-child(1)')
                ->waitFor('.toast-message')
                ->assertSee('Theme Cloned Successful');
        });

    }


    public function testEditTheme(){
        $this->testCloneTheme();
        $this->browse(function (Browser $browser){
            $browser
                ->visit('/style/themes')
                ->assertSee('Theme Customization')
                ->pause(3000)
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(6) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(6) > div > div > a:nth-child(1)')
                ->pause(5000)

                ->click('#main-content > div.row.justify-content-center > div.col-lg-12 > div > form > div:nth-child(5) > div > div > button:nth-child(2)')
                ->waitFor('.toast-message')
                ->assertSee('Theme Updated Successful');
        });

    }

    public function testDeleteTheme(){
        $this->testCloneTheme();
        $this->browse(function (Browser $browser){
            $browser
                ->visit('/style/themes')
                ->pause(3000)
                ->assertSee('Theme Customization')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(6) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(6) > div > div > a:nth-child(3)')
                ->whenAvailable('#main-content > div.row.justify-content-center > div.col-lg-12 > div > div > div > div.modal.fade.admin-query.show', function ($modal){
                    $modal->click('div > div > div.modal-body > div.mt-40.d-flex.justify-content-between > button.primary-btn.fix-gr-bg');
                })
                ->waitFor('.toast-message')
                ->assertSee('Theme Deleted Successful');
        });

    }

    public function testMakeDefaultTheme(){
        $this->testCloneTheme();
        $this->browse(function (Browser $browser){
            $browser->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(5) > a')
                ->waitFor('.toast-message')
                ->assertSee('Theme Set Default Successful');
        });

    }



}
