<?php


namespace Tests\Browser\Modules\Transfer;


use Carbon\Carbon;
use Laravel\Dusk\Browser;
use Tests\Browser\Traits\PurchaseTrait;
use Tests\DuskTestCase;

class TransferTest extends DuskTestCase
{
    use PurchaseTrait;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->createShowRoom();
    }

    public function tearDown(): void
    {
        $this->clearVoucherTable();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testVisitPageWithOutAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/transfer/create')
                ->assertPathIs('/login')
                ->visit('/transfer/lists')
                ->assertPathIs('/login');
        });

    }

    public function testVisitPageWithAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/transfer/create')
                ->assertSee('Make A Transfer')
                ->visit('/transfer/lists')
                ->assertSee('Transfered Lists');
        });
    }

    public function testMakeACashTransferFromMainToSecondBranch()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('session-data')
                ->visit('/transfer/create')
                ->assertSee('Make A Transfer')
                ->type("#startDate", Carbon::today()->format('m/d/Y'))
                ->type('#add_payment > section > div > div > div:nth-child(2) > div > form > div:nth-child(2) > div:nth-child(3) > div > input', $this->faker->paragraph)
                ->click('#add_payment > section > div > div > div:nth-child(2) > div > form > div.row.form > div:nth-child(1) > div > div')
                ->click('#add_payment > section > div > div > div:nth-child(2) > div > form > div.row.form > div:nth-child(1) > div > div > ul > li:nth-child(3)')
                ->type('#add_payment > section > div > div > div:nth-child(2) > div > form > div.row.form > div:nth-child(2) > div > input', 5000)
                ->click('#add_payment > section > div > div > div:nth-child(2) > div > form > div:nth-child(4) > div > div > button')
                ->waitFor('.toast-message', 20)
                ->assertSee('Contra Voucher has been added Successfully')
                ;
        });
    }

    public function testViewDetailsACashTransferFromMainToSecondBranch()
    {
        $this->testMakeACashTransferFromMainToSecondBranch();
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/transfer/lists')
                ->assertSee('Transfered Lists')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(6) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(6) > div > div > a')
                ->whenAvailable('#Voucher_info_modal', function ($modal){
                    $modal->assertSee('Transaction Details')
                    ->click('div > div > div.modal-body > div:nth-child(5) > div > button');
                })
                ;
        });
    }

    public function testMakeABankTransferFromMainToSecondBranch()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('session-data')
                ->visit('/transfer/create')
                ->assertSee('Make A Transfer')
                ->pause(5000)
                ->type("#startDate", Carbon::today()->format('m/d/Y'))
                ->click('#add_payment > section > div > div > div:nth-child(2) > div > form > div:nth-child(2) > div:nth-child(2) > div > div')
                ->click('#add_payment > section > div > div > div:nth-child(2) > div > form > div:nth-child(2) > div:nth-child(2) > div > div > ul > li:nth-child(2)')
                ->pause(3000)

                ->type('#add_payment > section > div > div > div:nth-child(2) > div > form > div:nth-child(2) > div:nth-child(3) > div > input', $this->faker->paragraph)

                ->click('#add_payment > section > div > div > div:nth-child(2) > div > form > div:nth-child(2) > div.col-lg-6.payment_from_div > div > div > div')
                ->click('#add_payment > section > div > div > div:nth-child(2) > div > form > div:nth-child(2) > div.col-lg-6.payment_from_div > div > div > div > ul > li:nth-child(2)')

                ->type('#cheque_no', $this->faker->randomNumber(6))
                ->type('#cheque_date', Carbon::today()->format('m/d/Y'))

                ->type('#bank_name', $this->faker->name)

                ->type('#bank_branch', $this->faker->name)


                ->click('#add_payment > section > div > div > div:nth-child(2) > div > form > div.row.form > div:nth-child(1) > div > div')
                ->click('#add_payment > section > div > div > div:nth-child(2) > div > form > div.row.form > div:nth-child(1) > div > div > ul > li:nth-child(3)')

                ->type('#add_payment > section > div > div > div:nth-child(2) > div > form > div.row.form > div:nth-child(2) > div > input', 5000)
                ->click('#add_payment > section > div > div > div:nth-child(2) > div > form > div:nth-child(4) > div > div > button')
                ->waitFor('.toast-message', 20)
                ->assertSeeIn('.toast-message', 'Contra Voucher has been added Successfully')
            ;
        });
    }

    public function testViewDetailsABankTransferFromMainToSecondBranch()
    {
        $this->testMakeABankTransferFromMainToSecondBranch();
        $this->browse(function (Browser $browser) {
            $browser
                ->visit('/transfer/lists')
                ->assertSee('Transfered Lists')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(6) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(6) > div > div > a')
                ->whenAvailable('#Voucher_info_modal', function ($modal){
                    $modal->assertSee('Transaction Details')
                        ;
                })
            ;
        });
    }

}
