<?php

namespace Tests\Browser\Modules\Sale;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Laravel\Dusk\Browser;
use Tests\Browser\Traits\PurchaseTrait;
use Tests\DuskTestCase;

class SaleTest extends DuskTestCase
{
    use PurchaseTrait;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
      $this->createProduct();
        $this->createCustomer();
    }

    public function tearDown(): void
    {
        $this->clearTable();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testVisitPageWithoutLogin(){

        $this->browse(function (Browser $browser){
            $browser->visit('/sale/sale')
                ->assertPathIs('/login')
                ->visit('/sale/sale/create')
                ->assertPathIs('/login');
        });
    }

    public function testVisitPageWithLogin(){

        $this->browse(function (Browser $browser){
            $browser->loginAs(1)
                ->visit('/sale/sale/create')
                ->assertSee('Add Sale');
        });
    }

    /*public function testCreateSaleWithRequiredFieldWithDueWithVariantProduct(){

        $this->testVisitPageWithLogin();
        $this->browse(function (Browser $browser){
            $browser
                ->click('#saleForm > div:nth-child(2) > div:nth-child(2) > div > div')
                ->click('#saleForm > div:nth-child(2) > div:nth-child(2) > div > div > ul > li:nth-child(2)')

                ->click('#saleForm > div:nth-child(2) > div:nth-child(3) > div > div')
                ->click('#saleForm > div:nth-child(2) > div:nth-child(3) > div > div > ul > li:nth-child(2)')

                ->pause(3000)

//                select Product
                ->click('#saleForm > div:nth-child(2) > div:nth-child(6) > div > div')
                ->click('#saleForm > div:nth-child(2) > div:nth-child(6) > div > div > ul > li:nth-child(2)') // Single product
                ->pause(2000)

               ->click('#saleForm > div:nth-child(2) > div:nth-child(6) > div > div')
                ->click('#saleForm > div:nth-child(2) > div:nth-child(6) > div > div > ul > li:nth-child(3)') // Variant product
                ->whenAvailable('#Item_Details', function($model){
                    $model->click('div > div > div.modal-body > form > div > div:nth-child(1) > a > img')

                    ;
                })
                ->pause(3000)

                ->type('#saleForm > div:nth-child(8) > div > div > div > div.note-editing-area > div.note-editable.card-block', $this->faker->paragraph)
                ->click('#main-content > section > div > div > div:nth-child(3) > div > div.col-12.mt-20 > div > button:nth-child(1)')
                ->waitFor('.toast-message')
                ->assertSee('Sale has Been Approved')
            ;
        });

    }*/

    public function testCreateSaleWithRequiredFieldWithDue(){

        $this->testVisitPageWithLogin();
        $this->browse(function (Browser $browser){
            $browser
                ->click('#saleForm > div:nth-child(2) > div:nth-child(2) > div > div')
                ->click('#saleForm > div:nth-child(2) > div:nth-child(2) > div > div > ul > li:nth-child(2)')

                ->click('#saleForm > div:nth-child(2) > div:nth-child(3) > div > div')
                ->click('#saleForm > div:nth-child(2) > div:nth-child(3) > div > div > ul > li:nth-child(2)')

                ->pause(3000)

                //                select Product
                ->click('#saleForm > div:nth-child(2) > div:nth-child(6) > div > div')
                ->click('#saleForm > div:nth-child(2) > div:nth-child(6) > div > div > ul > li:nth-child(2)') // Single product
                ->pause(3000)

                ->type('#saleForm > div:nth-child(8) > div > div > div > div.note-editing-area > div.note-editable.card-block', $this->faker->paragraph)
                ->click('#main-content > section > div > div > div:nth-child(3) > div > div.col-12.mt-20 > div > button:nth-child(1)')
                ->waitFor('.toast-message')
                ->assertSee('Sale has Been Approved')
            ;
        });

    }

    public function testAddPayment(){
        $this->testCreateSaleWithRequiredFieldWithDue();
        $this->browse(function (Browser $browser){
            $browser->visit('/sale/sale')
            ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(10) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(10) > div > div > a:nth-child(1)')
                ->assertSee('Payment')
                ->click('#add_product > section > div > div > div:nth-child(2) > form > div > div.col-lg-12.text-center.pt_15 > div > div.payment_buttons > button.primary_color_btn.payment_btn.multiple-payment-button.green_btn')
                ->waitFor('.toast-message')
                ->assertSee('Payment Successful');
        });
    }

    public function testSaleOrderDetails(){
        $this->testCreateSaleWithRequiredFieldWithDue();
        $this->browse(function (Browser $browser){
            $browser->visit('/sale/sale')
            ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(10) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(10) > div > div > a:nth-child(3)')
                ->assertSee('A4 SIZE');
        });
    }

    public function testCreateSaleWithRequiredFieldWithCashPayment(){

        $this->testVisitPageWithLogin();
        $this->browse(function (Browser $browser){
            $browser
                ->click('#saleForm > div:nth-child(2) > div:nth-child(2) > div > div')
                ->click('#saleForm > div:nth-child(2) > div:nth-child(2) > div > div > ul > li:nth-child(2)')

                ->click('#saleForm > div:nth-child(2) > div:nth-child(3) > div > div')
                ->click('#saleForm > div:nth-child(2) > div:nth-child(3) > div > div > ul > li:nth-child(2)')

                ->pause(3000)

                //                select Product
                ->click('#saleForm > div:nth-child(2) > div:nth-child(6) > div > div')
                ->click('#saleForm > div:nth-child(2) > div:nth-child(6) > div > div > ul > li:nth-child(2)') // Single product
                ->pause(3000)


                ->type('#saleForm > div:nth-child(2) > div.col-md-4.col-lg-4.col-sm-6.amount_div > div > input', 50)

                ->type('#saleForm > div:nth-child(8) > div > div > div > div.note-editing-area > div.note-editable.card-block', $this->faker->paragraph)
                ->click('#main-content > section > div > div > div:nth-child(3) > div > div.col-12.mt-20 > div > button:nth-child(1)')
                ->waitFor('.toast-message')
                ->assertSee('Sale has Been Approved')
            ;
        });

    }

    public function testAddPaymentToPartialInvoice()
    {
        $this->testCreateSaleWithRequiredFieldWithCashPayment();
        $this->browse(function (Browser $browser){
            $browser->visit('/sale/sale')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(10) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(10) > div > div > a:nth-child(1)')
                ->assertSee('Payment')
                ->click('#add_product > section > div > div > div:nth-child(2) > form > div > div.col-lg-12.text-center.pt_15 > div > div.payment_buttons > button.primary_color_btn.payment_btn.multiple-payment-button.green_btn')
                ->waitFor('.toast-message')
                ->assertSee('Payment Successful');
        });

    }

    public function testAddPartialPaymentToSaleOrder(){
        $this->testCreateSaleWithRequiredFieldWithDue();
        $this->browse(function (Browser $browser){
            $browser->visit('/sale/sale')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(10) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(10) > div > div > a:nth-child(1)')
                ->assertSee('Payment')
                ->type('#pos_payment_method > div:nth-child(1) > div:nth-child(1) > div > input', 50)
                ->click('#add_product > section > div > div > div:nth-child(2) > form > div > div.col-lg-12.text-center.pt_15 > div > div.payment_buttons > button.primary_color_btn.payment_btn.multiple-payment-button.green_btn')
                ->waitFor('.toast-message')
                ->assertSee('Payment Successful');
        });
    }

    public function testAddMultiplePaymentToSaleOrder(){
        $this->testCreateSaleWithRequiredFieldWithDue();
        $this->browse(function (Browser $browser){
            $browser->visit('/sale/sale')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(10) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(10) > div > div > a:nth-child(1)')
                ->assertSee('Payment')
                ->type('#pos_payment_method > div:nth-child(1) > div:nth-child(1) > div > input', 50)
                ->click('#add_product > section > div > div > div:nth-child(2) > form > div > div.row > div > div > div.pos_payment_method_upper > div.row.justify-content-center.mt-20.no-gutters > a')
                ->type('#pos_payment_method1 > div.row > div:nth-child(1) > div > input', 40)

                ->click('#add_product > section > div > div > div:nth-child(2) > form > div > div.col-lg-12.text-center.pt_15 > div > div.payment_buttons > button.primary_color_btn.payment_btn.multiple-payment-button.green_btn')
                ->waitFor('.toast-message')
                ->assertSee('Payment Successful');
        });
    }

    public function testQuickCashPaymentToSaleOrder(){
        $this->testCreateSaleWithRequiredFieldWithDue();
        $this->browse(function (Browser $browser){
            $browser->visit('/sale/sale')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(10) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(10) > div > div > a:nth-child(1)')
                ->assertSee('Payment')
                ->click('#add_product > section > div > div > div:nth-child(2) > form > div > div.row > div > div > div.payment_widget_tiket > ul > li:nth-child(5) > a')
                ->click('#add_product > section > div > div > div:nth-child(2) > form > div > div.row > div > div > div.payment_widget_tiket > ul > li:nth-child(6) > a')
                ->click('#add_product > section > div > div > div:nth-child(2) > form > div > div.row > div > div > div.payment_widget_tiket > ul > li:nth-child(6) > a')

                ->click('#add_product > section > div > div > div:nth-child(2) > form > div > div.col-lg-12.text-center.pt_15 > div > div.payment_buttons > button.primary_color_btn.payment_btn.multiple-payment-button.green_btn')
                ->waitFor('.toast-message')
                ->assertSee('Payment Successful');
        });
    }


    public function testCloneToSale(){
        $this->testCreateSaleWithRequiredFieldWithDue();
        $this->browse(function (Browser $browser){
            $browser->visit('/sale/sale')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(10) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(10) > div > div > a:nth-child(6)')
                ->assertSee('Clone to Sale')
                ->click('#main-content > section > div > div > div:nth-child(2) > div > div > div > button:nth-child(1)')

                ->waitFor('.toast-message')
                ->assertSee('Sale has Been Approved');
        });
    }

    public function testCloneToQuotation(){
        $this->testCreateSaleWithRequiredFieldWithDue();
        $this->browse(function (Browser $browser){
            $browser->visit('/sale/sale')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(10) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(10) > div > div > a:nth-child(7)')
                ->assertSee('Clone to Quotation')
                ->click('#add_product > section > div > div > div:nth-child(2) > div > div > div > button:nth-child(1)')

                ->waitFor('.toast-message')
                ->assertSee('Quotation Added Successfully');
        });
    }

    public function testSaleReturn(){
        $this->testCreateSaleWithRequiredFieldWithDue();
        $this->browse(function (Browser $browser){
            $browser->visit('/sale/sale')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(10) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(10) > div > div > a:nth-child(2)')
                ->type('#DataTables_Table_0 > tbody > tr:nth-child(2) > td:nth-child(9) > input.primary_input_field.quantity', 1)

                ->type('#main-content > section > div > div > div:nth-child(2) > div > form > div.row.mt-50 > div > div.row.pb-30 > div:nth-child(1) > div > div > div.note-editing-area > div.note-editable.card-block', $this->faker->paragraph)

                ->click('#main-content > section > div > div > div:nth-child(2) > div > form > div.row.mt-50 > div > div.col-12.mt-5 > div > button')

                ->waitFor('.toast-message')
                ->assertSee('Item Returned Successfully');
        });
    }


    public function testVisitSaleReturnPageWithOutLogin(){
        $this->browse(function (Browser $browser){
            $browser->visit('/sale/sale-return-list')
                ->assertPathIs('/login')
                ->visit('sale/sale-return-create')
                ->assertPathIs('/login');
        });
    }

    public function testSaleReturnDetails(){
        $this->testSaleReturn();
        $this->browse(function (Browser $browser){
            $browser->visit('sale/sale-return-list')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(10) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(10) > div > div > a')
                ->assertSee('Sale Return');
        });
    }

    public function testCreateSaleDraftWithRequiredFieldWithDue(){

        $this->testVisitPageWithLogin();
        $this->browse(function (Browser $browser){
            $browser
                ->click('#saleForm > div:nth-child(2) > div:nth-child(2) > div > div')
                ->click('#saleForm > div:nth-child(2) > div:nth-child(2) > div > div > ul > li:nth-child(2)')

                ->click('#saleForm > div:nth-child(2) > div:nth-child(3) > div > div')
                ->click('#saleForm > div:nth-child(2) > div:nth-child(3) > div > div > ul > li:nth-child(2)')

                ->pause(3000)

                //                select Product
                ->click('#saleForm > div:nth-child(2) > div:nth-child(6) > div > div')
                ->click('#saleForm > div:nth-child(2) > div:nth-child(6) > div > div > ul > li:nth-child(2)') // Single product
                ->pause(3000)

                ->type('#saleForm > div:nth-child(8) > div > div > div > div.note-editing-area > div.note-editable.card-block', $this->faker->paragraph)
                ->click('#main-content > section > div > div > div:nth-child(3) > div > div.col-12.mt-20 > div > button:nth-child(2)')
                ->assertSee('Update Sale')
                ->click('#main-content > section > div > div > div:nth-child(2) > div > div > div > button:nth-child(1)')
            ;
        });

    }

    public function testApproveDraftSale(){
        $this->testCreateSaleDraftWithRequiredFieldWithDue();
        $this->browse(function (Browser $browser){
            $browser->visit('/sale/sale')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(10) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(10) > div > div > a:nth-child(3)')
                ->whenAvailable('#confirm-approve', function ($modal) {
                    $modal->click('#approve_link');
                })

                ->waitFor('.toast-message')
                ->assertSee('Sale has Been Approved');
        });
//
    }

    public function testEditDraftSale(){
        $this->testCreateSaleDraftWithRequiredFieldWithDue();
        $this->browse(function (Browser $browser){
            $browser->visit('/sale/sale')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(10) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(10) > div > div > a:nth-child(1)')
                ->assertSee('Update Sale')
                ->click('#main-content > section > div > div > div:nth-child(2) > div > div > div > button:nth-child(1)')

                ->waitFor('.toast-message')
                ->assertSee('Sale Updated Successfully');
        });
//
    }




}

