<?php

namespace Tests\Browser\Modules\Quotation;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Laravel\Dusk\Browser;
use Tests\Browser\Traits\PurchaseTrait;
use Tests\DuskTestCase;

class QuotationTest extends DuskTestCase
{
    use PurchaseTrait;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->createProduct();
        $this->createCustomer();
    }

    public function tearDown(): void
    {
        $this->clearTable();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testVisitPageWithoutLogin(){

        $this->browse(function (Browser $browser){
            $browser->visit('/quotation/quotation')
                ->assertPathIs('/login')
                ->visit('/quotation/quotation/create')
                ->assertPathIs('/login');
        });
    }

    public function testVisitPageWithLogin(){

        $this->browse(function (Browser $browser){
            $browser->loginAs(1)
                ->visit('session-data')
                ->visit('/quotation/quotation/create')
                ->assertSee('Add Quotation');
        });
    }

    public function testCreateQuotationWithRequiredFieldWithDue(){

        $this->testVisitPageWithLogin();
        $this->browse(function (Browser $browser){
            $browser
                ->click('#quote_form > div:nth-child(2) > div:nth-child(1) > div > div')
                ->click('#quote_form > div:nth-child(2) > div:nth-child(1) > div > div > ul > li:nth-child(2)')

                ->click('#quote_form > div:nth-child(2) > div:nth-child(2) > div > div')
                ->click('#quote_form > div:nth-child(2) > div:nth-child(2) > div > div > ul > li:nth-child(2)')

                ->pause(3000)

                //                select Product
                ->click('#quote_form > div:nth-child(5) > div.col-lg-8.col-md-8.col-sm-12 > div > div')
                ->click('#quote_form > div:nth-child(5) > div.col-lg-8.col-md-8.col-sm-12 > div > div > ul > li:nth-child(2)') // Single product
                ->pause(3000)

                ->type('#quote_form > div:nth-child(11) > div > div > div > div.note-editing-area > div.note-editable.card-block', $this->faker->paragraph)
                ->click('#add_product > section > div > div > div:nth-child(2) > div > div > div > button:nth-child(1)')
                ->waitFor('.toast-message')
                ->assertSee('Quotation Added Successfully')
            ;
        });

    }

    public function testEditQuotation(){
        $this->testCreateQuotationWithRequiredFieldWithDue();
        $this->browse(function (Browser $browser){
            $browser->visit('/quotation/quotation')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(8) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(8) > div > div > a:nth-child(1)')

                ->click('#add_product > section > div > div > div:nth-child(2) > div > div > div > button:nth-child(1)')
                ->waitFor('.toast-message')
                ->assertSee('Quotation Updated Successfully');
        });
    }

    public function testShowDetailsQuotation(){
        $this->testCreateQuotationWithRequiredFieldWithDue();
        $this->browse(function (Browser $browser){
            $browser->visit('/quotation/quotation')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(8) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(8) > div > div > a:nth-child(2)')

                ->assertSee('Bill No');
        });
    }

    public function testConvertToSaleQuotation(){
        $this->testCreateQuotationWithRequiredFieldWithDue();
        $this->browse(function (Browser $browser){
            $browser->visit('/quotation/quotation')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(8) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(8) > div > div > a:nth-child(3)')
                ->assertSee('Convert To Sale')
                ->click('#main-content > section > div > div > div:nth-child(2) > div > div > div > button:nth-child(1)')
                ->waitFor('.toast-message')
                ->assertSee('Sale has Been Approved');
        });
    }

    public function testCloneToQuotation(){
        $this->testCreateQuotationWithRequiredFieldWithDue();
        $this->browse(function (Browser $browser){
            $browser->visit('/quotation/quotation')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(8) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(8) > div > div > a:nth-child(5)')
                ->assertSee('Clone to Quotation')
                ->click('#add_product > section > div > div > div:nth-child(2) > div > div > div > button:nth-child(1)')
                ->waitFor('.toast-message')
                ->assertSee('Quotation Added Successfully');
        });
    }

    public function testDeleteSingleProduct()
    {
        $this->testCreateQuotationWithRequiredFieldWithDue();
        $this->browse(function (Browser $browser){
            $browser->visit('/quotation/quotation')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(8) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(8) > div > div > a:nth-child(6)')
                ->whenAvailable('#confirm-delete', function ($modal) {
                    $modal->assertSee('Delete Confirmation')
                        ->click('#delete_link');
                })
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Quotation Deleted Successfully');
        });
    }
}
