<?php


namespace Tests\Browser\Modules\Accounts;


use Laravel\Dusk\Browser;
use Modules\Account\Entities\ChartAccount;
use Tests\Browser\Traits\PurchaseTrait;
use Tests\DuskTestCase;

class ChartAccountsTest extends DuskTestCase
{
    use PurchaseTrait;

    public function tearDown(): void
    {
        $chartAccounts = ChartAccount::where('id', '>', 34)->get();
        foreach ($chartAccounts as $a){
            $a->delete();
        }
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testVisitPageWithOutAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser
                ->visit('/account')
                ->assertPathIs('/login');
        });

    }

    public function testVisitPageWithAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('session-data')
                ->visit('/account')
                ->assertSee('Chart Of Accounts');
        });
    }

    public function testCreateAssetNoGroupActiveParentChartAccount()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser->click('#main-content > section > div > div > div.col-12 > div > div > ul > li > a')
                ->whenAvailable('#Item_Details', function ($modal) {
                    $modal
                        ->type('#chart_account_form > div > div:nth-child(1) > div > input', $this->faker->name)
                        ->type('#chart_account_form > div > div:nth-child(3) > div > input', $this->faker->paragraph)
                        ->click('#save_button_parent');
                })
                ->waitFor('.toast-message')
                ->assertSee('New Chart Account Added Successfully');
        });
    }

    public function testCreateAssetNoGroupActiveChildChartAccount()
    {
        $this->testCreateAssetNoGroupActiveParentChartAccount();
        $this->browse(function (Browser $browser) {
            $browser->click('#main-content > section > div > div > div.col-12 > div > div > ul > li > a')
                ->whenAvailable('#Item_Details', function ($modal) {
                    $modal
                        ->type('#chart_account_form > div > div:nth-child(1) > div > input', $this->faker->name)
                        ->type('#chart_account_form > div > div:nth-child(3) > div > input', $this->faker->paragraph)
                        ->click('#chart_account_form > div > div:nth-child(6) > div > label.primary_checkbox.d-flex.mr-12 > span')
                        ->pause(3000)
                        ->click('#parent_chart_account_list > div')
                        ->click('#parent_chart_account_list > div > ul > li:nth-child(1)')
                        ->click('#save_button_parent');
                })
                ->waitFor('.toast-message')
                ->assertSee('New Chart Account Added Successfully');
        });
    }

    public function testCreateAssetNoGroupDeActiveChildChartAccount()
    {
        $this->testCreateAssetNoGroupActiveParentChartAccount();
        $this->browse(function (Browser $browser) {
            $browser->click('#main-content > section > div > div > div.col-12 > div > div > ul > li > a')
                ->whenAvailable('#Item_Details', function ($modal) {
                    $modal
                        ->type('#chart_account_form > div > div:nth-child(1) > div > input', $this->faker->name)
                        ->type('#chart_account_form > div > div:nth-child(3) > div > input', $this->faker->paragraph)
                        ->click('#status_checkbox > li:nth-child(2) > label > span')
                        ->click('#chart_account_form > div > div:nth-child(6) > div > label.primary_checkbox.d-flex.mr-12 > span')
                        ->pause(3000)
                        ->click('#parent_chart_account_list > div')
                        ->click('#parent_chart_account_list > div > ul > li:nth-child(1)')
                        ->click('#save_button_parent');
                })
                ->waitFor('.toast-message')
                ->assertSee('New Chart Account Added Successfully');
        });
    }

    public function testCreateAssetGroupDeActiveChildChartAccount()
    {
        $this->testCreateAssetNoGroupActiveParentChartAccount();
        $this->browse(function (Browser $browser) {
            $browser->click('#main-content > section > div > div > div.col-12 > div > div > ul > li > a')
                ->whenAvailable('#Item_Details', function ($modal) {
                    $modal
                        ->type('#chart_account_form > div > div:nth-child(1) > div > input', $this->faker->name)
                        ->type('#chart_account_form > div > div:nth-child(3) > div > input', $this->faker->paragraph)
                        ->click('#group_checkbox > li:nth-child(1) > label > span')
                        ->click('#status_checkbox > li:nth-child(2) > label > span')
                        ->click('#chart_account_form > div > div:nth-child(6) > div > label.primary_checkbox.d-flex.mr-12 > span')
                        ->pause(3000)
                        ->click('#parent_chart_account_list > div')
                        ->click('#parent_chart_account_list > div > ul > li:nth-child(1)')
                        ->click('#save_button_parent');
                })
                ->waitFor('.toast-message')
                ->assertSee('New Chart Account Added Successfully');
        });
    }

    public function testEditAssetGroupDeActiveParentChartAccount()
    {
        $this->testCreateAssetNoGroupActiveParentChartAccount();
        $this->browse(function (Browser $browser) {
            $browser->click('#datas > tr:nth-child(1) > td:nth-child(7) > div > button')
                ->click('#datas > tr:nth-child(1) > td:nth-child(7) > div > div > a.dropdown-item.edit_chart_account')
                ->whenAvailable('#ChartAccount_Edit', function ($modal) {
                    $modal
                        ->pause(5000)
                        ->click('#ChartAccountEditForm > div > div.col-lg-12.text-center > div > button');
                })
                ->waitFor('.toast-message')
                ->assertSee('Chart Account Updated Successfully');
        });
    }

    public function testDeleteAssetGroupDeActiveParentChartAccount()
    {
        $this->testCreateAssetNoGroupActiveParentChartAccount();
        $this->browse(function (Browser $browser) {
            $browser->click('#datas > tr:nth-child(1) > td:nth-child(7) > div > button')
                ->click('#datas > tr:nth-child(1) > td:nth-child(7) > div > div > a:nth-child(2)')
                ->whenAvailable('#confirm-delete', function ($modal) {
                    $modal
                        ->click('#delete_link');
                })
                ->waitFor('.toast-message')
                ->assertSee('Chart Account Deleted Successfully');
        });
    }

    public function testEditAssetGroupDeActiveChildChartAccount()
    {
        $this->testCreateAssetGroupDeActiveChildChartAccount();
        $this->browse(function (Browser $browser) {
            $browser->pause(5000)
                ->click('#datas > tr:nth-child(2) > td:nth-child(7) > div > button')
                ->click('#datas > tr:nth-child(2) > td:nth-child(7) > div > div > a.dropdown-item.edit_chart_account')
                ->whenAvailable('#ChartAccount_Edit', function ($modal) {
                    $modal
                        ->pause(5000)
                        ->click('#ChartAccountEditForm > div > div.col-lg-12.text-center > div > button');
                })
                ->waitFor('.toast-message')
                ->assertSee('Chart Account Updated Successfully');
        });
    }

    public function testDeleteAssetGroupDeActiveChildChartAccount()
    {
        $this->testCreateAssetGroupDeActiveChildChartAccount();
        $this->browse(function (Browser $browser) {
            $browser
                ->pause(5000)
                ->click('#datas > tr:nth-child(2) > td:nth-child(7) > div > button')
                ->click('#datas > tr:nth-child(2) > td:nth-child(7) > div > div > a:nth-child(2)')
                ->whenAvailable('#confirm-delete', function ($modal) {
                    $modal
                        ->click('#delete_link');
                })
                ->waitFor('.toast-message')
                ->assertSee('Chart Account Deleted Successfully');
        });
    }

    public function testDeleteAssetGroupDeActiveParentWithChildChartAccount()
    {
        $this->testCreateAssetGroupDeActiveChildChartAccount();
        $this->browse(function (Browser $browser) {
            $browser
                ->pause(5000)
                ->click('#datas > tr:nth-child(1) > td:nth-child(7) > div > button')
                ->click('#datas > tr:nth-child(1) > td:nth-child(7) > div > div > a:nth-child(2)')
                ->whenAvailable('#confirm-delete', function ($modal) {
                    $modal
                        ->click('#delete_link');
                })
                ->waitFor('.toast-message')
                ->assertSee('Chart Account Has Children Account. Please Delete Children Account First.');
        });
    }
}
