<?php

namespace Tests\Browser\Modules\Product;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\WithFaker;
use Laravel\Dusk\Browser;
use Modules\Product\Entities\Brand;
use Tests\DuskTestCase;

class BrandTest extends DuskTestCase
{
    use withFaker;

    public function tearDown(): void
    {
        $brands = Brand::get();
        foreach ($brands as $brand){
            $brand->delete();
        }
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testVisitPageWithOutAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/product/brand')
                ->assertPathIs('/login');
        });

    }

    public function testVisitPageWithAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/product/brand')
                ->assertSee('Brand');
        });
    }

    public function testCreateBrandWithRequiredField()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > a')
                ->whenAvailable('#brandForm', function ($modal) {
                    $modal->type('name', $this->faker->name)
                        ->click('#save_button_parent');
                })->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Brand Added Successfully');
        });
    }

    public function testEditBrandWithRequiredField()
    {
        $this->testCreateBrandWithRequiredField();
        $this->browse(function (Browser $browser) {
            $browser->visit('/product/brand')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(5) > div > div > a.dropdown-item.edit_brand')
                ->whenAvailable('#Item_Edit', function ($modal) {
                    $modal->pause(5000)
                        ->type('name', $this->faker->name)
                        ->click('#update_save_button_parent')
                    ;
                })
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Brand Updated Successfully');
        });
    }

    public function testCreateBrandWithAllField()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > a')
                ->whenAvailable('#Item_Details', function ($modal) {
                    $modal->type('name', $this->faker->name)
                        ->type('description', $this->faker->paragraph)
                        ->click('#save_button_parent');
                })->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Brand Added Successfully');
        });
    }

    public function testEditBrandWithAllField()
    {
        $this->testCreateBrandWithAllField();
        $this->browse(function (Browser $browser) {
            $browser->visit('/product/brand')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(5) > div > div > a.dropdown-item.edit_brand')
                ->whenAvailable('#Item_Edit', function ($modal) {
                    $modal->pause(3000)
                        ->type('name', $this->faker->name)
                        ->type('description', $this->faker->paragraph)
                        ->click('#update_save_button_parent');
                })
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Brand Updated Successfully');
        });
    }

    public function testCreateBrandWithAllFieldStatusDeActive()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > a')
                ->whenAvailable('#Item_Details', function ($modal) {
                    $modal->type('name', $this->faker->name)
                        ->type('description', $this->faker->paragraph)
                        ->click('#theme_nav > li:nth-child(2) > label > span')
                        ->click('#save_button_parent');
                })->waitFor('.toast-message')
                ->with('.table', function ($table){
                    $table->waitFor('.badge_4')
                        ->assertSee('DeActive');
                })
                ->assertSeeIn('.toast-message', 'Brand Added Successfully');
        });
    }

    public function testEditBrandWithAllFieldsChangeStatusDeActiveToActive()
    {
        $this->testCreateBrandWithAllFieldStatusDeActive();
        $this->browse(function (Browser $browser){
            $browser->visit('/product/brand')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(5) > div > div > a.dropdown-item.edit_brand')
                ->whenAvailable('#Item_Edit', function ($modal) {
                    $modal->pause(3000)
                        ->type('name', $this->faker->name)
                        ->type('description', $this->faker->paragraph)
                        ->click('#theme_nav > li:nth-child(1) > label > span')
                        ->click('#update_save_button_parent');
                })
                ->waitFor('.toast-message')
                ->with('.table', function ($table){
                    $table->waitFor('.badge_1')
                        ->assertSee('Active');
                })
                ->assertSeeIn('.toast-message', 'Brand Updated Successfully');
        });

    }

    public function testDeleteBrand (){
        $this->testCreateBrandWithAllField();
        $this->browse(function(Browser $browser){
            $browser->visit('/product/brand')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(5) > div > div > a:nth-child(2)')
                ->whenAvailable('#confirm-delete', function ($modal) {
                    $modal->click('#delete_link');
                })->waitFor('.toast-message')
                ->assertSee('Brand Deleted Successfully');

        });
    }



}
