<?php

namespace Tests\Browser\Modules\Product;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\WithFaker;
use Laravel\Dusk\Browser;
use Modules\Product\Entities\Category;
use Tests\DuskTestCase;

class CategoryTest extends DuskTestCase
{
    use withFaker;

    public function tearDown(): void
    {
        $categories = Category::get();
        foreach ($categories as $category){
            $category->delete();
        }
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testVisitPageWithOutAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/product/category')
                ->assertPathIs('/login');
        });

    }

    public function testVisitPageWithAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/product/category')
                ->assertSee('Category');
        });
    }

    public function testCreateCategoryWithRequiredField()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > a')
                ->whenAvailable('#Item_Details', function ($modal) {
                    $modal->type('name', $this->faker->name)
                        ->click('#save_button_parent');
                })->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Category Added Successfully');
        });
    }

    public function testEditCategoryWithRequiredField()
    {
        $this->testCreateCategoryWithRequiredField();
        $this->browse(function (Browser $browser) {
            $browser->visit('/product/category')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(7) > div > div > a.dropdown-item.edit_category')
                ->whenAvailable('#Item_Edit', function ($modal) {
                    $modal->pause(3000)
                        ->type('name', $this->faker->name)
                        ->click('#update_save_button_parent');
                })
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Category Updated Successfully');
        });
    }


    public function testCreateCategoryWithAllField()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > a')
                ->whenAvailable('#Item_Details', function ($modal) {
                    $modal->type('name', $this->faker->name)
                        ->type('code', $this->faker->randomNumber(4))
                        ->type('description', $this->faker->paragraph)
                        ->click('#save_button_parent');
                })->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Category Added Successfully');
        });
    }

    public function testEditCategoryWithAllField()
    {
        $this->testCreateCategoryWithAllField();
        $this->browse(function (Browser $browser) {
            $browser->visit('/product/category')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(7) > div > div > a.dropdown-item.edit_category')
                ->whenAvailable('#Item_Edit', function ($modal) {
                    $modal->pause(3000)
                        ->type('name', $this->faker->name)
                        ->type('code', $this->faker->randomNumber(4))
                        ->type('description', $this->faker->paragraph)
                        ->click('#update_save_button_parent');
                })
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Category Updated Successfully');
        });
    }

    public function testCreateCategoryWithAllFieldStatusDeActive()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > a')
                ->whenAvailable('#Item_Details', function ($modal) {
                    $modal->type('name', $this->faker->name)
                        ->type('code', $this->faker->randomNumber(4))
                        ->type('description', $this->faker->paragraph)
                        ->click('#theme_nav > li:nth-child(2) > label > span')
                        ->click('#save_button_parent');
                })->waitFor('.toast-message')
                ->with('.table', function ($table){
                    $table->waitFor('.badge_4')
                    ->assertSee('DeActive');
                })
                ->assertSeeIn('.toast-message', 'Category Added Successfully');
        });
    }

    public function testEditCategoryWithAllFieldsChangeStatusDeActiveToActive()
    {
        $this->testCreateCategoryWithAllFieldStatusDeActive();
        $this->browse(function (Browser $browser){
            $browser->visit('/product/category')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(7) > div > div > a.dropdown-item.edit_category')
                ->whenAvailable('#Item_Edit', function ($modal) {
                    $modal->pause(3000)
                        ->type('name', $this->faker->name)
                        ->type('code', $this->faker->randomNumber(4))
                        ->type('description', $this->faker->paragraph)
                        ->click('#theme_nav > li:nth-child(1) > label > span')
                        ->click('#update_save_button_parent');
                })
                ->waitFor('.toast-message')
                ->with('.table', function ($table){
                    $table->waitFor('.badge_1')
                        ->assertSee('Active');
                })
                ->assertSeeIn('.toast-message', 'Category Updated Successfully');
        });

    }

    public function testCreateSubCategory(){
        $this->testCreateCategoryWithAllField();
        $this->browse(function (Browser $browser){
            $browser->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > a')
                ->whenAvailable('#Item_Details', function ($modal) {
                    $modal->type('name', $this->faker->name)
                        ->type('code', $this->faker->randomNumber(4))
                        ->type('description', $this->faker->paragraph)
                        ->click('#categoryForm > div > div:nth-child(5) > div > label.primary_checkbox.d-flex.mr-12 > span')

                        ->pause(3000)

                        ->click('#save_button_parent');
                })->waitFor('.toast-message')
                ->with('.table', function ($table){
                    $table->pause(3000)
                        ->assertSee('->');
                })
                ->assertSeeIn('.toast-message', 'Category Added Successfully');
        });
    }

    public function testEditSubcategory(){
        $this->testCreateSubCategory();
        $this->browse(function (Browser $browser){
            $browser->visit('/product/category')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(7) > div > div > a.dropdown-item.edit_category')
                ->whenAvailable('#Item_Edit', function ($modal) {
                    $modal->pause(3000)
                        ->type('name', $this->faker->name)
                        ->type('code', $this->faker->randomNumber(4))
                        ->type('description', $this->faker->paragraph)

                        ->click('#update_save_button_parent');
                })
                ->waitFor('.toast-message')
                ->with('.table', function ($table){
                    $table->pause(3000)
                        ->assertSee('->');
                })
                ->assertSeeIn('.toast-message', 'Category Updated Successfully');
        });
    }


    public function testEditSubcategoryToParentCategory(){
        $this->testCreateSubCategory();
        $this->browse(function (Browser $browser){
            $browser->visit('/product/category')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(7) > div > div > a.dropdown-item.edit_category')
                ->whenAvailable('#Item_Edit', function ($modal) {
                    $modal->pause(3000)
                        ->type('name', $this->faker->name)
                        ->type('code', $this->faker->randomNumber(4))
                        ->type('description', $this->faker->paragraph)
                        ->click('#categoryEditForm > div > div:nth-child(6) > div > label.primary_checkbox.d-flex.mr-12 > span')
                        ->click('#update_save_button_parent');
                })
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Category Updated Successfully');
        });
    }

    public function testDeleteCategory (){
        $this->testCreateCategoryWithAllField();
        $this->browse(function(Browser $browser){
           $browser->visit('/product/category')
           ->click('#dropdownMenu2')
               ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(7) > div > div > a:nth-child(2)')
               ->whenAvailable('#confirm-delete', function ($modal) {
                    $modal->click('#delete_link');
               })->waitFor('.toast-message')
               ->assertSee('Category Deleted Successfully');

        });
    }

    public function testDeleteSubCategory (){
        $this->testCreateSubCategory();
        $this->browse(function(Browser $browser){
           $browser->visit('/product/category')
           ->click('#dropdownMenu2')
               ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(7) > div > div > a:nth-child(2)')
               ->whenAvailable('#confirm-delete', function ($modal) {
                    $modal->click('#delete_link');
               })->waitFor('.toast-message')
               ->assertSee('Category Deleted Successfully');
        });
    }

    public function testDeleteParentCategory (){
        $this->testCreateSubCategory();
        $this->browse(function(Browser $browser){
           $browser->visit('/product/category')
           ->click('#dropdownMenu3')
               ->click('#DataTables_Table_0 > tbody > tr.even > td:nth-child(7) > div > div > a:nth-child(2)')
               ->whenAvailable('#confirm-delete', function ($modal) {
                    $modal->click('#delete_link');
               })->waitFor('.toast-message')
               ->assertSee('Category Deleted Successfully');
        });
    }


}
