<?php

namespace Tests\Browser\Modules\Product;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\WithFaker;
use Laravel\Dusk\Browser;
use Modules\Product\Entities\ModelType;
use Tests\DuskTestCase;

class ModelTest extends DuskTestCase
{
    use withFaker;

    public function tearDown(): void
    {
        $models = ModelType::get();
        foreach ($models as $model){
            $model->delete();
        }
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testVisitPageWithOutAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/product/model')
                ->assertPathIs('/login');
        });

    }

    public function testVisitPageWithAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/product/model')
                ->assertSee('Model');
        });
    }

    public function testCreateModelWithRequiredField()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > a')
                ->whenAvailable('#Item_Details', function ($modal) {
                    $modal->type('name', $this->faker->name)
                        ->click('#save_button_parent');
                })->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Model Added Successfully');
        });
    }

    public function testEditModelWithRequiredField()
    {
        $this->testCreateModelWithRequiredField();
        $this->browse(function (Browser $browser) {
            $browser->visit('/product/model')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(5) > div > div > a.dropdown-item.edit_model_type')
                ->whenAvailable('#Item_Edit', function ($modal) {
                    $modal->pause(3000)
                        ->type('name', $this->faker->name)
                        ->click('#update_save_button_parent');
                })
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Model Updated Successfully');
        });
    }

    public function testCreateModelWithAllField()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > a')
                ->whenAvailable('#Item_Details', function ($modal) {
                    $modal->type('name', $this->faker->name)
                        ->type('description', $this->faker->paragraph)
                        ->click('#save_button_parent');
                })->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Model Added Successfully');
        });
    }

    public function testEditModelWithAllField()
    {
        $this->testCreateModelWithAllField();
        $this->browse(function (Browser $browser) {
            $browser->visit('/product/model')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(5) > div > div > a.dropdown-item.edit_model_type')
                ->whenAvailable('#Item_Edit', function ($modal) {
                    $modal->pause(3000)
                        ->type('name', $this->faker->name)
                        ->type('description', $this->faker->paragraph)
                        ->click('#update_save_button_parent');
                })
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Model Updated Successfully');
        });
    }

    public function testCreateModelWithAllFieldStatusDeActive()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > a')
                ->whenAvailable('#Item_Details', function ($modal) {
                    $modal->type('name', $this->faker->name)
                        ->type('description', $this->faker->paragraph)
                        ->click('#theme_nav > li:nth-child(2) > label > span')
                        ->click('#save_button_parent');
                })->waitFor('.toast-message')
                ->with('.table', function ($table){
                    $table->waitFor('.badge_4')
                        ->assertSee('DeActive');
                })
                ->assertSeeIn('.toast-message', 'Model Added Successfully');
        });
    }

    public function testEditModelWithAllFieldsChangeStatusDeActiveToActive()
    {
        $this->testCreateModelWithAllFieldStatusDeActive();
        $this->browse(function (Browser $browser){
            $browser->visit('/product/model')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(5) > div > div > a.dropdown-item.edit_model_type')
                ->whenAvailable('#Item_Edit', function ($modal) {
                    $modal->pause(3000)
                        ->type('name', $this->faker->name)
                        ->type('description', $this->faker->paragraph)
                        ->click('#theme_nav > li:nth-child(1) > label > span')
                        ->click('#update_save_button_parent');
                })
                ->waitFor('.toast-message')
                ->with('.table', function ($table){
                    $table->waitFor('.badge_1')
                        ->assertSee('Active');
                })
                ->assertSeeIn('.toast-message', 'Model Updated Successfully');
        });

    }

    public function testDeleteModel (){
        $this->testCreateModelWithAllField();
        $this->browse(function(Browser $browser){
            $browser->visit('/product/model')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(5) > div > div > a:nth-child(2)')
                ->whenAvailable('#confirm-delete', function ($modal) {
                    $modal->click('#delete_link');
                })->waitFor('.toast-message')
                ->assertSee('Model Deleted Successfully');

        });
    }



}
