<?php

namespace Tests\Browser\Modules\Product;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\WithFaker;
use Laravel\Dusk\Browser;
use Modules\Inventory\Entities\StockReport;
use Modules\Product\Entities\Brand;
use Modules\Product\Entities\Category;
use Modules\Product\Entities\ModelType;
use Modules\Product\Entities\Product;
use Modules\Product\Entities\ProductHistory;
use Modules\Product\Entities\UnitType;
use Modules\Product\Entities\Variant;
use Modules\Product\Entities\VariantValues;
use Tests\DuskTestCase;

class ProductCreateTest extends DuskTestCase
{
    use withFaker;

    public function tearDown(): void
    {
        $products = Product::get();
        foreach ($products as $product) {
            $product->skus()->delete();
            $product->variations()->delete();
            $product->delete();
        }

        $categories = Category::get();
        foreach ($categories as $category) {
            $category->delete();
        }
        $models = ModelType::get();
        foreach ($models as $model) {
            $model->delete();
        }
        $unitTypes = UnitType::get();
        foreach ($unitTypes as $unitType) {
            $unitType->delete();
        }
        $brands = Brand::get();
        foreach ($brands as $brand) {
            $brand->delete();
        }

        $variants = Variant::get();
        foreach ($variants as $variant) {
            $variant->values()->delete();
            $variant->delete();
        }

        $productHistories = ProductHistory::get();
        foreach ($productHistories as $history) {
            $history->delete();
        }

        $stocks = StockReport::get();
        foreach ($stocks as $stock) {
            $stock->delete();
        }

        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testVisitPageWithOutAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/product/add_product')
                ->assertPathIs('/login');
        });

    }

    public function testVisitPageWithAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('session-data')
                ->visit('/product/add_product')
                ->assertSee('Add New Product');
        });
    }

    public function testCreateSingleTypeProductWithOnlyRequiredField()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser->type('product_name', $this->faker->name)
                ->type('selling_price', 1000)
                ->click('#content_form > div.col-12 > div > button.primary-btn.semi_large2.fix-gr-bg.submit')
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Product has been added Successfully');

        });
    }

    public function testCreateSingleTypeProductWithAllFieldWithCreateModal()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser->type('product_name', $this->faker->name)
                ->type('product_sku', $this->faker->randomNumber(4))

//               Create Unit
                ->click('#unit_type_div > div > div.double_label.d-flex.justify-content-between > label.primary_input_label.green_input_label > a')
                ->whenAvailable('#new_unit', function ($unit_modal) {
                    $unit_modal->assertSee('Add Unit Type')
                        ->type('#unitTypeForm > div > div:nth-child(1) > div > input', $this->faker->name)
                        ->type('#unitTypeForm > div > div:nth-child(2) > div > input', $this->faker->paragraph)
                        ->click('#unit_submit')
                        ->pause(3000);
                })
                ->click('#barcode_type_div > div > div')
                ->click('#barcode_type_div > div > div > ul > li:nth-child(2)')

//               Create Brand
                ->click('#brand_div > div > div.double_label.d-flex.justify-content-between > label.primary_input_label.green_input_label > a')
                ->whenAvailable('#new_barnd', function ($brand_modal) {
                    $brand_modal->assertSee('Add Brand')
                        ->type('#brandForm > div > div:nth-child(1) > div > input', $this->faker->name)
                        ->click('#brandForm > div > div:nth-child(2) > div > input', $this->faker->paragraph)
                        ->click('#brand_submit')
                        ->pause(3000);
                })

//               Create Category

                ->click('#category_div > div > div.double_label.d-flex.justify-content-between > label.primary_input_label.green_input_label > a')
                ->whenAvailable('#Item_Details', function ($category_modal) {
                    $category_modal->assertSee('Add Category')
                        ->type('#categoryForm > div > div:nth-child(1) > div > input', $this->faker->name)
                        ->type('#categoryForm > div > div:nth-child(2) > div > input', $this->faker->randomNumber(4))
                        ->type('#categoryForm > div > div:nth-child(3) > div > input', $this->faker->paragraph)
                        ->click('#category_submit')
                        ->pause(3000);
                })

//               Create Sub category

                ->click('#sub_category_div > div > div.double_label.d-flex.justify-content-between > label.primary_input_label.green_input_label > a')
                ->whenAvailable('#new_sub_cat', function ($sub_cat_modal) {
                    $sub_cat_modal->assertSee('Sub Category')
                        ->type('#subcategoryForm > div > div:nth-child(1) > div > input', $this->faker->name)
                        ->type('#subcategoryForm > div > div:nth-child(2) > div > input', $this->faker->randomNumber(4))
                        ->type('#subcategoryForm > div > div:nth-child(3) > div > input', $this->faker->paragraph)
                        ->click('#sub_category_submit')
                        ->pause(3000);
                })

//                Create model

                ->click('#model_div > div > div.double_label.d-flex.justify-content-between > label.primary_input_label.green_input_label > a')
                ->whenAvailable('#new_model', function ($model_modal) {
                    $model_modal->assertSee('New Model')
                        ->type('#modelTypeForm > div > div:nth-child(1) > div > input', $this->faker->name)
                        ->type('#modelTypeForm > div > div:nth-child(2) > div > input', $this->faker->paragraph)
                        ->click('#model_submit')
                        ->pause(3000);
                })
                ->type('alert_quantity', 10)
                ->attach('file', public_path('img/profile.jpg'))
                ->type('purchase_price', 90)
                ->type('selling_price', 100)
                ->type('min_selling_price', 95)
                ->type('price_of_other_currency', 150)
                ->type('tax', 15)
                ->type('#content_form > div:nth-child(2) > div.col-xl-12 > div > div > div.note-editing-area > div.note-editable.card-block', $this->faker->paragraph)
                ->click('#content_form > div.col-12 > div > button.primary-btn.semi_large2.fix-gr-bg.submit')
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Product has been added Successfully');

        });
    }

    public function testCreateVariantTypeProduct()
    {
        $variant = Variant::create([
            'name' => 'Color',
            'status' => 1
        ]);
        VariantValues::insert([
            [
                'variant_id' => $variant->id,
                'value' => 'Red'
            ],
            [
                'variant_id' => $variant->id,
                'value' => 'Green'
            ],
            [
                'variant_id' => $variant->id,
                'value' => 'Yellow'
            ]

        ]);

        $variant = Variant::create([
            'name' => 'Size',
            'status' => 1
        ]);
        VariantValues::insert([
            [
                'variant_id' => $variant->id,
                'value' => '32'
            ],
            [
                'variant_id' => $variant->id,
                'value' => '34'
            ],
            [
                'variant_id' => $variant->id,
                'value' => '36'
            ]

        ]);
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser->click('#content_form > div:nth-child(2) > div:nth-child(1) > div > div')
                ->click('#content_form > div:nth-child(2) > div:nth-child(1) > div > div > ul > li:nth-child(2)')
                ->type('product_name', $this->faker->name)
                ->scrollIntoView('#content_form > div:nth-child(4) > div > div > div')
                ->click('#content_form > div:nth-child(4) > div > div > div')
                ->click('#content_form > div:nth-child(4) > div > div > div > ul > li:nth-child(1)')
                ->pause(4000)
                ->click('#content_form > div:nth-child(4) > div > div > div')
                ->click('#content_form > div:nth-child(4) > div > div > div > ul > li:nth-child(2)')
                ->pause(4000)
                ->type('#DataTables_Table_0 > tbody > tr > td:nth-child(3) > input', $this->faker->randomNumber(4))
                ->type('#DataTables_Table_0 > tbody > tr > td:nth-child(4) > input', 10)
                ->type('#DataTables_Table_0 > tbody > tr > td:nth-child(5) > input', 90)
                ->type('#DataTables_Table_0 > tbody > tr > td:nth-child(6) > input', 95)
                ->type('#DataTables_Table_0 > tbody > tr > td:nth-child(7) > input', 100)
                ->attach('#document_file_2', public_path('img/profile.jpg'))
                ->click('#content_form > div.col-lg-12.choose_variant > div.add_items_button.pt-10 > button')
                ->pause(3000)
                ->click('#DataTables_Table_0 > tbody > tr.variant_row_lists.even > td:nth-child(2) > div')
                ->click('#DataTables_Table_0 > tbody > tr.variant_row_lists.even > td:nth-child(2) > div > ul > li:nth-child(2)')
                ->type('#DataTables_Table_0 > tbody > tr.variant_row_lists.even > td:nth-child(3) > input', $this->faker->randomNumber(4))
                ->type('#DataTables_Table_0 > tbody > tr.variant_row_lists.even > td:nth-child(4) > input', 10)
                ->type('#DataTables_Table_0 > tbody > tr.variant_row_lists.even > td:nth-child(5) > input', 90)
                ->type('#DataTables_Table_0 > tbody > tr.variant_row_lists.even > td:nth-child(6) > input', 95)
                ->type('#DataTables_Table_0 > tbody > tr.variant_row_lists.even > td:nth-child(7) > input', 100)
                ->attach('#document_file_3', public_path('img/profile.jpg'))
                ->click('#content_form > div.col-lg-12.choose_variant > div.add_items_button.pt-10 > button')
                ->pause(3000)
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(3) > td:nth-child(2) > div')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(3) > td:nth-child(2) > div > ul > li:nth-child(3)')
                ->type('#DataTables_Table_0 > tbody > tr:nth-child(3) > td:nth-child(3) > input', $this->faker->randomNumber(4))
                ->type('#DataTables_Table_0 > tbody > tr:nth-child(3) > td:nth-child(4) > input', 10)
                ->type('#DataTables_Table_0 > tbody > tr:nth-child(3) > td:nth-child(5) > input', 90)
                ->type('#DataTables_Table_0 > tbody > tr:nth-child(3) > td:nth-child(6) > input', 95)
                ->type('#DataTables_Table_0 > tbody > tr:nth-child(3) > td:nth-child(7) > input', 100)
                ->attach('#document_file_4', public_path('img/profile.jpg'))
                ->type('#content_form > div:nth-child(2) > div.col-xl-12 > div > div > div.note-editing-area > div.note-editable.card-block', $this->faker->paragraph)
                ->click('#content_form > div.col-12 > div > button.primary-btn.semi_large2.fix-gr-bg.submit')
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Product has been added Successfully');
        });
    }

    public function testCreateComboProduct()
    {
        $this->testCreateVariantTypeProduct();

        $this->browse(function (Browser $browser) {
            $browser->visit('/inventory/product/add-opening-stock')
                ->click('#main-content > section > div > div > div:nth-child(2) > div > form > div:nth-child(2) > div:nth-child(1) > div > div')
                ->click('#main-content > section > div > div > div:nth-child(2) > div > form > div:nth-child(2) > div:nth-child(1) > div > div > ul > li:nth-child(2)')
                ->click('#main-content > section > div > div > div:nth-child(2) > div > form > div:nth-child(2) > div:nth-child(4) > div > div')
                ->click('#main-content > section > div > div > div:nth-child(2) > div > form > div:nth-child(2) > div:nth-child(4) > div > div > ul > li:nth-child(2)')
                ->pause(2000)
                ->type('stock_quantity', 100)
                ->click('#main-content > section > div > div > div:nth-child(2) > div > form > small > div > div > div > button')
                ->waitFor('.toast-message')
                ->assertSee('Product has been added to stock successfully')
                ->click('#main-content > section > div > div > div:nth-child(2) > div > form > div:nth-child(2) > div:nth-child(1) > div > div')
                ->click('#main-content > section > div > div > div:nth-child(2) > div > form > div:nth-child(2) > div:nth-child(1) > div > div > ul > li:nth-child(3)')
                ->click('#main-content > section > div > div > div:nth-child(2) > div > form > div:nth-child(2) > div:nth-child(4) > div > div')
                ->click('#main-content > section > div > div > div:nth-child(2) > div > form > div:nth-child(2) > div:nth-child(4) > div > div > ul > li:nth-child(2)')
                ->pause(2000)
                ->type('stock_quantity', 100)
                ->click('#main-content > section > div > div > div:nth-child(2) > div > form > small > div > div > div > button')
                ->waitFor('.toast-message')
                ->assertSee('Product has been added to stock successfully')
                ->click('#main-content > section > div > div > div:nth-child(2) > div > form > div:nth-child(2) > div:nth-child(1) > div > div')
                ->click('#main-content > section > div > div > div:nth-child(2) > div > form > div:nth-child(2) > div:nth-child(1) > div > div > ul > li:nth-child(4)')
                ->click('#main-content > section > div > div > div:nth-child(2) > div > form > div:nth-child(2) > div:nth-child(4) > div > div')
                ->click('#main-content > section > div > div > div:nth-child(2) > div > form > div:nth-child(2) > div:nth-child(4) > div > div > ul > li:nth-child(2)')
                ->pause(2000)
                ->type('stock_quantity', 100)
                ->click('#main-content > section > div > div > div:nth-child(2) > div > form > small > div > div > div > button')
                ->waitFor('.toast-message')
                ->assertSee('Product has been added to stock successfully');
        });

        $this->browse(function (Browser $browser) {
            $browser->visit('/product/add_product')
                ->click('#content_form > div:nth-child(2) > div:nth-child(1) > div > div')
                ->click('#content_form > div:nth-child(2) > div:nth-child(1) > div > div > ul > li:nth-child(3)')
                ->type('product_name', $this->faker->name)
                ->click('#select_product > div > div')
                ->click('#select_product > div > div > ul > li:nth-child(1)')
                ->click('#select_product > div > div > ul > li:nth-child(2)')
                ->click('#select_product > div > div')
                ->click('#select_product > div > div > ul > li:nth-child(3)')
                ->type('combo_selling_price', 350)
                ->type('#content_form > div:nth-child(2) > div.col-xl-12 > div > div > div.note-editing-area > div.note-editable.card-block', $this->faker->paragraph)
                ->click('#content_form > div.col-12 > div > button.primary-btn.semi_large2.fix-gr-bg.submit')
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Product has been added Successfully');
        });
    }

    public function testCreateService()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser->click('#content_form > div:nth-child(2) > div:nth-child(1) > div > div')
                ->click('#content_form > div:nth-child(2) > div:nth-child(1) > div > div > ul > li:nth-child(4)')
                ->type('product_name', $this->faker->name)
                ->type('hourly_rate', 500)
                ->type('#content_form > div:nth-child(2) > div.col-xl-12 > div > div > div.note-editing-area > div.note-editable.card-block', $this->faker->paragraph)
                ->click('#content_form > div.col-12 > div > button.primary-btn.semi_large2.fix-gr-bg.submit')
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Product has been added Successfully');
        });

    }

    public function testEditSingleProduct()
    {
        $this->testCreateSingleTypeProductWithAllFieldWithCreateModal();
        $this->browse(function (Browser $browser) {
            $browser->visit('/product/add_product/create')
                ->pause(5000)
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_1 > tbody > tr > td:nth-child(15) > div > div > a:nth-child(1)')
                ->assertSee('Edit Product')
                ->type('product_name', $this->faker->name)
                ->click('#main-content > section > div > div > div:nth-child(2) > div > form > div.col-12 > div > button')
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Product has been updated Successfully');
        });
    }

    public function testViewSingleProduct()
    {
        $this->testCreateSingleTypeProductWithAllFieldWithCreateModal();
        $this->browse(function (Browser $browser) {
            $browser->visit('/product/add_product/create')
                ->pause(3000)
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_1 > tbody > tr > td:nth-child(15) > div > div > a:nth-child(3)')
                ->whenAvailable('#Item_Details', function ($modal) {
                    $modal->assertSee('Product Name')
                        ->click('div > div > div.modal-header > button');
                }, 10000);
        });
    }

    public function testDeleteSingleProduct()
    {
        $this->testCreateSingleTypeProductWithAllFieldWithCreateModal();
        $this->browse(function (Browser $browser) {
            $browser->visit('/product/add_product/create')
                ->pause(3000)
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_1 > tbody > tr.odd > td:nth-child(15) > div > div > a.dropdown-item.edit_brand')
                ->whenAvailable('#confirm-delete', function ($modal) {
                    $modal->assertSee('Delete Confirmation')
                        ->click('#delete_link');
                })
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Product has been deleted Successfully');
        });
    }

    public function testEditVariantProduct()
    {
        $this->testCreateVariantTypeProduct();
        $this->browse(function (Browser $browser) {
            $browser->visit('/product/add_product/create')
                ->pause(3000)
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_1 > tbody > tr > td:nth-child(15) > div > div > a:nth-child(1)')
                ->assertSee('Edit Product')
                ->type('product_name', $this->faker->name)
                ->click('#main-content > section > div > div > div:nth-child(2) > div > form > div.col-12 > div > button')
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Product has been updated Successfully');
        });
    }


    public function testViewVariantProduct()
    {
        $this->testCreateVariantTypeProduct();
        $this->browse(function (Browser $browser) {
            $browser->visit('/product/add_product/create')
                ->pause(3000)
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_1 > tbody > tr > td:nth-child(15) > div > div > a:nth-child(2)')
                ->whenAvailable('#Item_Details', function ($modal) {
                    $modal->assertSee('Product Name')
                        ->click('div > div > div.modal-header > button');
                });
        });
    }

    public function testDeleteVariantProduct()
    {
        $this->testCreateVariantTypeProduct();
        $this->browse(function (Browser $browser) {
            $browser->visit('/product/add_product/create')
                ->pause(3000)
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_1 > tbody > tr.odd > td:nth-child(15) > div > div > a.dropdown-item.edit_brand')
                ->whenAvailable('#confirm-delete', function ($modal) {
                    $modal->assertSee('Delete Confirmation')
                        ->click('#delete_link');
                })
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Product has been deleted Successfully');
        });
    }

    public function testEditComboProduct()
    {
        $this->testCreateComboProduct();
        $this->browse(function (Browser $browser) {
            $browser->visit('/product/add_product/create')
                ->click('#main-content > div:nth-child(4) > div > ul > li:nth-child(2) > a')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(9) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(9) > div > div > a:nth-child(1)')
                ->assertSee('Edit Product')
                ->type('product_name', $this->faker->name)
                ->click('#main-content > section > div > div > div:nth-child(2) > div > form > div.col-12 > div > button')
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Product has been updated Successfully');
        });
    }

    public function testShowComboProduct()
    {
        $this->testCreateComboProduct();
        $this->browse(function (Browser $browser) {
            $browser->visit('/product/add_product/create')
                ->click('#main-content > div:nth-child(4) > div > ul > li:nth-child(2) > a')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(9) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(9) > div > div > a:nth-child(2)')
                ->whenAvailable('#Item_Details', function ($modal) {
                    $modal->assertSee('Product Name')
                        ->click('div > div > div.modal-header > button');
                });
        });
    }

    public function testDeleteComboProduct()
    {
        $this->testCreateComboProduct();
        $this->browse(function (Browser $browser) {
            $browser->visit('/product/add_product/create')
                ->click('#main-content > div:nth-child(4) > div > ul > li:nth-child(2) > a')
                ->pause(3000)
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(9) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(9) > div > div > a.dropdown-item.edit_brand')
                ->whenAvailable('#confirm-delete', function ($modal) {
                    $modal->assertSee('Delete Confirmation')
                        ->click('#delete_link');
                })
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Product has been deleted Successfully');
        });
    }

    public function testSingleProductPriceHistory(){
//        Todo::write test after purchase and sell.
        $this->testCreateSingleTypeProductWithAllFieldWithCreateModal();
        $this->browse(function (Browser $browser){
           $browser->visit('product/add_product/create')
               ->pause(3000)
           ->click('#dropdownMenu2')
           ->click('#DataTables_Table_1 > tbody > tr:nth-child(1) > td:nth-child(15) > div > div > a:nth-child(4)');

        });
    }
}
