<?php

namespace Tests\Browser\Modules\Product;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\WithFaker;
use Laravel\Dusk\Browser;
use Modules\Product\Entities\UnitType;
use Tests\DuskTestCase;

class UnitTypeTest extends DuskTestCase
{
    use withFaker;

    public function tearDown(): void
    {
        $unit_types = UnitType::get();
        foreach ($unit_types as $unit_type){
            $unit_type->delete();
        }
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testVisitPageWithOutAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/product/unit_type')
                ->assertPathIs('/login');
        });

    }

    public function testVisitPageWithAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/product/unit_type')
                ->assertSee('Unit Type');
        });
    }

    public function testCreateUnitTypeWithRequiredField()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > a')
                ->whenAvailable('#Item_Details', function ($modal) {
                    $modal->type('name', $this->faker->name)
                        ->click('#save_button_parent');
                })->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Unit Type Added Successfully');
        });
    }

    public function testEditUnitTypeWithRequiredField()
    {
        $this->testCreateUnitTypeWithRequiredField();
        $this->browse(function (Browser $browser) {
            $browser->visit('/product/unit_type')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(5) > div > div > a.dropdown-item.edit_unit_type')
                ->whenAvailable('#Item_Edit', function ($modal) {
                    $modal->pause(3000)
                        ->type('name', $this->faker->name)
                        ->click('#update_save_button_parent');
                })
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Unit Type Updated Successfully');
        });
    }

    public function testCreateUnitTypeWithAllField()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > a')
                ->whenAvailable('#Item_Details', function ($modal) {
                    $modal->type('name', $this->faker->name)
                        ->type('description', $this->faker->paragraph)
                        ->click('#save_button_parent');
                })->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Unit Type Added Successfully');
        });
    }

    public function testEditUnitTypeWithAllField()
    {
        $this->testCreateUnitTypeWithAllField();
        $this->browse(function (Browser $browser) {
            $browser->visit('/product/unit_type')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(5) > div > div > a.dropdown-item.edit_unit_type')
                ->whenAvailable('#Item_Edit', function ($modal) {
                    $modal->pause(3000)
                        ->type('name', $this->faker->name)
                        ->type('description', $this->faker->paragraph)
                        ->click('#update_save_button_parent');
                })
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Unit Type Updated Successfully');
        });
    }

    public function testCreateUnitTypeWithAllFieldStatusDeActive()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > a')
                ->whenAvailable('#Item_Details', function ($modal) {
                    $modal->type('name', $this->faker->name)
                        ->type('description', $this->faker->paragraph)
                        ->click('#theme_nav > li:nth-child(2) > label > span')
                        ->click('#save_button_parent');
                })->waitFor('.toast-message')
                ->with('.table', function ($table){
                    $table->waitFor('.badge_4')
                        ->assertSee('DeActive');
                })
                ->assertSeeIn('.toast-message', 'Unit Type Added Successfully');
        });
    }

    public function testEditUnitTypeWithAllFieldsChangeStatusDeActiveToActive()
    {
        $this->testCreateUnitTypeWithAllFieldStatusDeActive();
        $this->browse(function (Browser $browser){
            $browser->visit('/product/unit_type')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(5) > div > div > a.dropdown-item.edit_unit_type')
                ->whenAvailable('#Item_Edit', function ($modal) {
                    $modal->pause(3000)
                        ->type('name', $this->faker->name)
                        ->type('description', $this->faker->paragraph)
                        ->click('#theme_nav > li:nth-child(1) > label > span')
                        ->click('#update_save_button_parent');
                })
                ->waitFor('.toast-message')
                ->with('.table', function ($table){
                    $table->waitFor('.badge_1')
                        ->assertSee('Active');
                })
                ->assertSeeIn('.toast-message', 'Unit Type Updated Successfully');
        });

    }

    public function testDeleteUnitType (){
        $this->testCreateUnitTypeWithAllField();
        $this->browse(function(Browser $browser){
            $browser->visit('/product/unit_type')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(5) > div > div > a:nth-child(2)')
                ->whenAvailable('#confirm-delete', function ($modal) {
                    $modal->click('#delete_link');
                })->waitFor('.toast-message')
                ->assertSee('Unit Type Deleted Successfully');

        });
    }



}
