<?php

namespace Tests\Browser\Modules\Product;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\WithFaker;
use Laravel\Dusk\Browser;
use Modules\Product\Entities\Variant;
use Tests\DuskTestCase;

class VariantTest extends DuskTestCase
{
    use withFaker;

    public function tearDown(): void
    {
        $variants = Variant::get();
        foreach ($variants as $variant){
            $variant->delete();
        }
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testVisitPageWithOutAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/product/variant')
                ->assertPathIs('/login');
        });

    }

    public function testVisitPageWithAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/product/variant')
                ->assertSee('Variant');
        });
    }

    public function testCreateVariantWithRequiredField()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > a')
                ->whenAvailable('#Item_Details', function ($modal) {
                    $modal->type('name', $this->faker->name)
                        ->click('#save_button_parent');
                })->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Variant Added Successfully');
        });
    }

    public function testEditVariantWithRequiredField()
    {
        $this->testCreateVariantWithRequiredField();
        $this->browse(function (Browser $browser) {
            $browser->visit('/product/variant')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(5) > div > div > a.dropdown-item.edit_variant')
                ->pause(6000)
                ->whenAvailable('#Item_Edit', function ($modal) {
                    $modal
                        ->type('name', $this->faker->name)
                        ->click('#update_save_button_parent');
                })
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Variant Updated Successfully');
        });
    }

    public function testCreateVariantWithAllField()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > a')
                ->whenAvailable('#Item_Details', function ($modal) {
                    $modal->type('name', $this->faker->name)
                        ->type('description', $this->faker->paragraph)
                        ->type('#variantForm > div > div:nth-child(4) > div > div > div > table > tbody > tr > td:nth-child(1) > input', $this->faker->name)
                        ->click('#variantForm > div > div:nth-child(4) > div > div > div > table > tbody > tr > td.pl-0.pb-0.pr-0 > div > button')
                        ->type('#variantForm > div > div:nth-child(4) > div > div > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > input', $this->faker->name)
                        ->click('#variantForm > div > div:nth-child(4) > div > div > div > table > tbody > tr > td.pl-0.pb-0.pr-0 > div > button')
                        ->type('#variantForm > div > div:nth-child(4) > div > div > div > table > tbody > tr:nth-child(3) > td:nth-child(1) > input', $this->faker->name)
                        ->click('#variantForm > div > div:nth-child(4) > div > div > div > table > tbody > tr > td.pl-0.pb-0.pr-0 > div > button')
                        ->click('#variantForm > div > div:nth-child(4) > div > div > div > table > tbody > tr:nth-child(4) > td.pl-0.pb-0.pr-0.remove > a')
                        ->click('#save_button_parent');
                })->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Variant Added Successfully');
        });
    }

    public function testEditVariantWithAllField()
    {
        $this->testCreateVariantWithAllField();
        $this->browse(function (Browser $browser) {
            $browser->visit('/product/variant')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(5) > div > div > a.dropdown-item.edit_variant')
                ->whenAvailable('#Item_Edit', function ($modal) {
                    $modal->pause(3000)
                        ->type('name', $this->faker->name)
                        ->type('description', $this->faker->paragraph)
                        ->click('#update_save_button_parent');
                })
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Variant Updated Successfully');
        });
    }

    public function testCreateVariantWithAllFieldStatusDeActive()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > a')
                ->whenAvailable('#Item_Details', function ($modal) {
                    $modal->type('name', $this->faker->name)
                        ->type('description', $this->faker->paragraph)
                        ->click('#theme_nav > li:nth-child(2) > label > span')
                        ->click('#save_button_parent');
                })->waitFor('.toast-message')
                ->with('.table', function ($table){
                    $table->waitFor('.badge_4')
                        ->assertSee('DeActive');
                })
                ->assertSeeIn('.toast-message', 'Variant Added Successfully');
        });
    }

    public function testEditVariantWithAllFieldsChangeStatusDeActiveToActive()
    {
        $this->testCreateVariantWithAllFieldStatusDeActive();
        $this->browse(function (Browser $browser){
            $browser->visit('/product/variant')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(5) > div > div > a.dropdown-item.edit_variant')
                ->whenAvailable('#Item_Edit', function ($modal) {
                    $modal->pause(3000)
                        ->type('name', $this->faker->name)
                        ->type('description', $this->faker->paragraph)
                        ->click('#theme_nav > li:nth-child(1) > label > span')
                        ->click('#update_save_button_parent');
                })
                ->waitFor('.toast-message')
                ->with('.table', function ($table){
                    $table->waitFor('.badge_1')
                        ->assertSee('Active');
                })
                ->assertSeeIn('.toast-message', 'Variant Updated Successfully');
        });

    }

    public function testViewVariantDetails (){
        $this->testCreateVariantWithAllField();
        $this->browse(function(Browser $browser){
            $browser->visit('/product/variant')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(5) > div > div > a:nth-child(2)')
                ->assertSee('Varient Name');

        });
    }

    public function testDeleteVariant (){
        $this->testCreateVariantWithAllField();
        $this->browse(function(Browser $browser){
            $browser->visit('/product/variant')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(5) > div > div > a:nth-child(3)')
                ->whenAvailable('#confirm-delete', function ($modal) {
                    $modal->click('#delete_link');
                })->waitFor('.toast-message')
                ->assertSee('Variant Deleted Successfully');

        });
    }



}
