<?php

namespace Tests\Browser\Modules\Contact;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\WithFaker;
use Laravel\Dusk\Browser;
use Modules\Contact\Entities\ContactModel;
use Modules\Setting\Model\GeneralSetting;
use Tests\DuskTestCase;

class ContactWithLoginTest extends DuskTestCase
{
    use withFaker;

    protected $settings = null;

    public function setUp(): void
    {
        parent::setUp();
        $this->settings = GeneralSetting::first();
        if (!$this->settings->contact_login){
            $this->settings->contact_login = 1;
            $this->settings->save();
        }

    }

    public function tearDown(): void
    {
        $contacts = ContactModel::where('id', '!=', 1)->get();
        foreach ($contacts as $contact){
            $contact->accounts()->delete();
            $contact->user()->delete();
            $contact->delete();
        }
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testEnableContactLogin()
    {

        $this->settings->contact_login = 0;
        $this->settings->save();

        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/contact/settings')
                ->assertSee('LOGIN PERMISSION')
                ->click('#contact_settings > section > div > div > div:nth-child(2) > div > form > div > div > div > div.col-lg-9 > div > div > div:nth-child(1) > div > label')
                ->click('#_submit_btn_admission')
                ->waitFor('.toast-message')
                ->assertSee('Contact Settings updated Successfully !!!.');
        });
    }

    public function testDisableContactLogin()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/contact/settings')
                ->assertSee('LOGIN PERMISSION')
                ->click('#contact_settings > section > div > div > div:nth-child(2) > div > form > div > div > div > div.col-lg-9 > div > div > div:nth-child(2) > div > label')
                ->click('#_submit_btn_admission')
                ->waitFor('.toast-message')
                ->assertSee('Contact Settings updated Successfully !!!.');
        });
    }

    public function testCreateCustomerWithPassword()
    {

        $this->browse(function (Browser $browser) {

            $browser->loginAs(1)
                ->visit('contact/add_contact')
                ->assertSee('Add Contact')
                ->click('#content_form > div.row.form > div:nth-child(1) > div > div')
                ->click('#content_form > div.row.form > div:nth-child(1) > div > div > ul > li:nth-child(2)')
                ->type('name', $this->faker->name)
                ->type('business_name', $this->faker->name)
                ->type('tax_number', $this->faker->bankAccountNumber)
                ->type('opening_balance', $this->faker->randomNumber(4))
                ->type('credit_limit', $this->faker->randomNumber(4))
                ->type('pay_term', $this->faker->randomNumber(4))
                ->type('email', $this->faker->email)
                ->type('password', '12345678')
                ->type('mobile', $this->faker->phoneNumber)
                ->type('alternate_contact_no', $this->faker->phoneNumber)
//                ->attach('file', public_path('img/profile.jpg'))
               /* //Country
                ->click('#content_form > div.row.form > div:nth-child(15) > div > div')
                ->click('#content_form > div.row.form > div:nth-child(15) > div > div > ul > li:nth-child(2)')
                ->pause(2000)

                // State
                ->click('#content_form > div.row.form > div:nth-child(16) > div > div')
                ->click('#content_form > div.row.form > div:nth-child(16) > div > div > ul > li:nth-child(2)')
                ->pause(2000)

                // City
                ->click('#content_form > div.row.form > div:nth-child(17) > div > div')
                ->click('#content_form > div.row.form > div:nth-child(17) > div > div > ul > li:nth-child(2)')*/
                ->type('address', 'Fake Address')
                ->scrollIntoView('#content_form > div.row.form > div.col-xl-12 > div > div > div.note-editing-area > div.note-editable.card-block')
                ->click('#content_form > div.row.form > div.col-xl-12 > div > div > div.note-editing-area > div.note-editable.card-block')
                ->type('#content_form > div.row.form > div.col-xl-12 > div > div > div.note-editing-area > div.note-editable.card-block', $this->faker->paragraph)
                ->pause(1000)
                ->scrollIntoView('#content_form > div.col-12 > div > button')
                ->click('#content_form > div.col-12 > div > button')
                ->waitFor('.toast-message')
                ->assertSee('Contact Added Successfully');
        });

    }

    public function testCreateSupplierWithPassword()
    {

        $this->browse(function (Browser $browser) {

            $browser->loginAs(1)
                ->visit('contact/add_contact')
                ->assertSee('Add Contact')
                ->type('name', $this->faker->name)
                ->type('business_name', $this->faker->name)
                ->type('tax_number', $this->faker->bankAccountNumber)
                ->type('opening_balance', $this->faker->randomNumber(4))
                ->type('pay_term', $this->faker->randomNumber(4))
                ->type('email', $this->faker->email)
                ->type('password', '12345678')
                ->type('mobile', $this->faker->phoneNumber)
                ->type('alternate_contact_no', $this->faker->phoneNumber)
                ->attach('file', public_path('img/profile.jpg'))
               /* //Country
                ->click('#content_form > div.row.form > div:nth-child(15) > div > div')
                ->click('#content_form > div.row.form > div:nth-child(15) > div > div > ul > li:nth-child(2)')
                ->pause(2000)

                // State
                ->click('#content_form > div.row.form > div:nth-child(16) > div > div')
                ->click('#content_form > div.row.form > div:nth-child(16) > div > div > ul > li:nth-child(2)')
                ->pause(2000)

                // City
                ->click('#content_form > div.row.form > div:nth-child(17) > div > div')
                ->click('#content_form > div.row.form > div:nth-child(17) > div > div > ul > li:nth-child(2)')*/
                ->type('address', 'Fake Address')
                ->scrollIntoView('#content_form > div.row.form > div.col-xl-12 > div > div > div.note-editing-area > div.note-editable.card-block')
                ->click('#content_form > div.row.form > div.col-xl-12 > div > div > div.note-editing-area > div.note-editable.card-block')
                ->type('#content_form > div.row.form > div.col-xl-12 > div > div > div.note-editing-area > div.note-editable.card-block', $this->faker->paragraph)
                ->pause(1000)
                ->scrollIntoView('#content_form > div.col-12 > div > button')
                ->click('#content_form > div.col-12 > div > button')
                ->waitFor('.toast-message')
                ->assertSee('Contact Added Successfully');
        });

    }

    public function testEditCustomerWithOutPassword()
    {
        $this->testCreateCustomerWithPassword();

        $this->browse(function (Browser $browser) {
            $browser->visit('contact/customer')
                ->assertSee('Customers')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(9) > div > div > a:nth-child(2)')
                ->assertSee('Edit Contact')
                ->type('name', $this->faker->name)
                ->click('#content_form > div.col-12 > div > button')
                ->waitFor('.toast-message')
                ->assertSee('Contact Updated Successfully');
        });

    }

    public function testEditCustomerWithPassword()
    {
        $this->testCreateCustomerWithPassword();

        $this->browse(function (Browser $browser) {
            $browser->visit('contact/customer')
                ->assertSee('Customers')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(9) > div > div > a:nth-child(2)')
                ->assertSee('Edit Contact')
                ->type('name', $this->faker->name)
                ->type('password', '12345678')
                ->scrollIntoView('#content_form > div.col-12 > div > button')
                ->click('#content_form > div.col-12 > div > button')
                ->waitFor('.toast-message')
                ->assertSee('Contact Updated Successfully');
        });

    }

    public function testEditSupplierWithOutPassword()
    {
        $this->testCreateSupplierWithPassword();

        $this->browse(function (Browser $browser) {
            $browser->visit('contact/supplier')
                ->assertSee('Suppliers')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(9) > div > div > a:nth-child(1)')
                ->assertSee('Edit Contact')
                ->type('name', $this->faker->name)
                ->scrollIntoView('#content_form > div.col-12 > div > button')
                ->click('#content_form > div.col-12 > div > button')
                ->waitFor('.toast-message')
                ->assertSee('Contact Updated Successfully');
        });

    }

    public function testEditSupplierWithPassword()
    {
        $this->testCreateSupplierWithPassword();

        $this->browse(function (Browser $browser) {
            $browser->visit('contact/supplier')
                ->assertSee('Suppliers')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(9) > div > div > a:nth-child(1)')
                ->assertSee('Edit Contact')
                ->type('name', $this->faker->name)
                ->type('password', '12345678')
                ->scrollIntoView('#content_form > div.col-12 > div > button')
                ->click('#content_form > div.col-12 > div > button')
                ->waitFor('.toast-message')
                ->assertSee('Contact Updated Successfully');
        });
    }

    public function testCreateCustomerWithOutLoginEditWithLogin()
    {

        $this->testDisableContactLogin();

        $this->browse(function (Browser $browser)  {

            $browser->visit('contact/add_contact')
                ->assertSee('Add Contact')
                ->click('#content_form > div.row.form > div:nth-child(1) > div > div')
                ->click('#content_form > div.row.form > div:nth-child(1) > div > div > ul > li:nth-child(2)')
                ->type('name', $this->faker->name)
                ->type('business_name', $this->faker->name)
                ->type('tax_number', $this->faker->bankAccountNumber)
                ->type('opening_balance', $this->faker->randomNumber(4))
                ->type('credit_limit', $this->faker->randomNumber(4))
                ->type('pay_term', $this->faker->randomNumber(4))
                ->type('mobile', $this->faker->phoneNumber)
                ->type('alternate_contact_no', $this->faker->phoneNumber)
                ->attach('file', public_path('img/profile.jpg'))
                /*//Country
                ->click('#content_form > div.row.form > div:nth-child(14) > div > div')
                ->click('#content_form > div.row.form > div:nth-child(14) > div > div > ul > li:nth-child(2)')
                ->pause(2000)

                // State
                ->click('#content_form > div.row.form > div:nth-child(15) > div > div')
                ->click('#content_form > div.row.form > div:nth-child(15) > div > div > ul > li:nth-child(2)')
                ->pause(2000)

                // City
                ->click('#content_form > div.row.form > div:nth-child(16) > div > div')
                ->click('#content_form > div.row.form > div:nth-child(16) > div > div > ul > li:nth-child(2)')*/
                ->type('address', 'Fake Address')
                ->scrollIntoView('#content_form > div.row.form > div.col-xl-12 > div > div > div.note-editing-area > div.note-editable.card-block')
                ->click('#content_form > div.row.form > div.col-xl-12 > div > div > div.note-editing-area > div.note-editable.card-block')
                ->type('#content_form > div.row.form > div.col-xl-12 > div > div > div.note-editing-area > div.note-editable.card-block', $this->faker->paragraph)
                ->pause(1000)
                ->scrollIntoView('#content_form > div.col-12 > div > button')
                ->click('#content_form > div.col-12 > div > button')
                ->waitFor('.toast-message')
                ->assertSee('Contact Added Successfully');
        });

        $this->testEnableContactLogin();

        $this->browse(function (Browser $browser) {
            $browser->visit('contact/customer')
                ->assertSee('Customers')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(9) > div > div > a:nth-child(2)')
                ->assertSee('Edit Contact')
                ->type('name', $this->faker->name)
                ->type('email', $this->faker->email)
                ->type('password', '12345678')
                ->scrollIntoView('#content_form > div.col-12 > div > button')
                ->click('#content_form > div.col-12 > div > button')
                ->waitFor('.toast-message')
                ->assertSee('Contact Updated Successfully');
        });
    }


    public function testCreateSupplierWithOutLoginEditWithLogin()
    {

        $this->testDisableContactLogin();


        $this->browse(function (Browser $browser)  {

            $browser->visit('contact/add_contact')
                ->assertSee('Add Contact')
                ->type('name', $this->faker->name)
                ->type('business_name', $this->faker->name)
                ->type('tax_number', $this->faker->bankAccountNumber)
                ->type('opening_balance', $this->faker->randomNumber(4))
                ->type('pay_term', $this->faker->randomNumber(4))
                ->type('mobile', $this->faker->phoneNumber)
                ->type('alternate_contact_no', $this->faker->phoneNumber)
                ->attach('file', public_path('img/profile.jpg'))
                /*//Country
                ->click('#content_form > div.row.form > div:nth-child(14) > div > div')
                ->click('#content_form > div.row.form > div:nth-child(14) > div > div > ul > li:nth-child(2)')
                ->pause(2000)

                // State
                ->click('#content_form > div.row.form > div:nth-child(15) > div > div')
                ->click('#content_form > div.row.form > div:nth-child(15) > div > div > ul > li:nth-child(2)')
                ->pause(2000)

                // City
                ->click('#content_form > div.row.form > div:nth-child(16) > div > div')
                ->click('#content_form > div.row.form > div:nth-child(16) > div > div > ul > li:nth-child(2)')*/
                ->type('address', 'Fake Address')
                ->scrollIntoView('#content_form > div.row.form > div.col-xl-12 > div > div > div.note-editing-area > div.note-editable.card-block')
                ->click('#content_form > div.row.form > div.col-xl-12 > div > div > div.note-editing-area > div.note-editable.card-block')
                ->type('#content_form > div.row.form > div.col-xl-12 > div > div > div.note-editing-area > div.note-editable.card-block', $this->faker->paragraph)
                ->pause(1000)
                ->scrollIntoView('#content_form > div.col-12 > div > button')
                ->click('#content_form > div.col-12 > div > button')
                ->waitFor('.toast-message')
                ->assertSee('Contact Added Successfully');
        });


        $this->testEnableContactLogin();

        $this->browse(function (Browser $browser) {
            $browser->visit('contact/supplier')
                ->assertSee('Suppliers')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(9) > div > div > a:nth-child(1)')
                ->assertSee('Edit Contact')
                ->type('name', $this->faker->name)
                ->type('email', $this->faker->email)
                ->type('password', '12345678')
                ->scrollIntoView('#content_form > div.col-12 > div > button')
                ->click('#content_form > div.col-12 > div > button')
                ->waitFor('.toast-message')
                ->assertSee('Contact Updated Successfully');
        });
    }
}
