<?php

namespace Tests\Browser\Modules\Contact;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\WithFaker;
use Laravel\Dusk\Browser;
use Modules\Contact\Entities\ContactModel;
use Tests\DuskTestCase;

class CustomerTest extends DuskTestCase
{
    use withFaker;

    public function tearDown(): void
    {
        $contacts = ContactModel::where('id', '!=', 1)->get();
        foreach ($contacts as $contact){
            $contact->accounts()->delete();
            $contact->delete();
        }
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testVisitAddContactFromCustomerListPage()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('contact/customer')
                ->click('#main-content > div.row.justify-content-center > div.col-12 > div > div > ul > li:nth-child(1) > a')
                ->assertSee('Add Contact');
        });
    }

    public function testAddCustomerWithRequiredData()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('contact/add_contact')
                ->assertSee('Add Contact')
                ->click('#content_form > div.row.form > div:nth-child(1) > div > div')
                ->click('#content_form > div.row.form > div:nth-child(1) > div > div > ul > li:nth-child(2)')
                ->type('name', $this->faker->name)
                ->attach('file', public_path('img/profile.jpg'))
                ->click('#content_form > div.col-12 > div > button')
                ->waitFor('.toast-message')
                ->assertSee('Contact Added Successfully');
        });
    }


    public function testAddCustomerWithAllData()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('contact/add_contact')
                ->assertSee('Add Contact')
                ->click('#content_form > div.row.form > div:nth-child(1) > div > div')
                ->click('#content_form > div.row.form > div:nth-child(1) > div > div > ul > li:nth-child(2)')
                ->type('name', $this->faker->name)
                ->type('business_name', $this->faker->name)
                ->type('tax_number', $this->faker->bankAccountNumber)
                ->type('opening_balance', $this->faker->randomNumber(4))
                ->type('credit_limit', $this->faker->randomNumber(4))
                ->type('pay_term', $this->faker->randomNumber(4))
                ->type('email', $this->faker->email)
                ->type('mobile', $this->faker->phoneNumber)
                ->type('alternate_contact_no', $this->faker->phoneNumber)
                ->attach('file', public_path('img/profile.jpg'))
               /* //Country
                ->click('#content_form > div.row.form > div:nth-child(14) > div > div')
                ->click('#content_form > div.row.form > div:nth-child(14) > div > div > ul > li:nth-child(2)')
//                ->type('address', $this->faker->address)

                    ->pause(2000)

                // State
                ->click('#content_form > div.row.form > div:nth-child(15) > div > div')
                ->click('#content_form > div.row.form > div:nth-child(15) > div > div > ul > li:nth-child(2)')
                ->pause(2000)

                // City
                ->click('#content_form > div.row.form > div:nth-child(16) > div > div')
                ->click('#content_form > div.row.form > div:nth-child(16) > div > div > ul > li:nth-child(2)')*/

                ->type('address', 'Fake Address')

                ->scrollIntoView('#content_form > div.row.form > div.col-xl-12 > div > div > div.note-editing-area > div.note-editable.card-block')
                ->click('#content_form > div.row.form > div.col-xl-12 > div > div > div.note-editing-area > div.note-editable.card-block')
                ->type('#content_form > div.row.form > div.col-xl-12 > div > div > div.note-editing-area > div.note-editable.card-block', $this->faker->paragraph)
                ->pause(1000)

                ->scrollIntoView('#content_form > div.col-12 > div > button')
                ->click('#content_form > div.col-12 > div > button')
                ->waitFor('.toast-message')
                ->assertSee('Contact Added Successfully');
        });
    }

    public function testEditCustomerWithAllData()
    {
        $this->testAddCustomerWithAllData();
        $this->browse(function (Browser $browser) {
            $browser->visit('contact/customer')
                ->assertSee('Customers')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(9) > div > div > a:nth-child(2)')
                ->assertSee('Edit Contact')
                ->type('name', $this->faker->name)
                ->scrollIntoView('#content_form > div.col-12 > div > button')
                ->click('#content_form > div.col-12 > div > button')
                ->waitFor('.toast-message')
                ->assertSee('Contact Updated Successfully');
        });
    }

    public function testShowCustomerDetails()
    {
        $this->testAddCustomerWithAllData();
        $this->browse(function (Browser $browser) {
            $browser->visit('contact/customer')
                ->assertSee('Customers')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(9) > div > div > a:nth-child(1)')
                ->assertSee('Customer Profile')
                ->assertSee('Fake Address');
        });
    }
    public function testDeleteCustomerWithAllData()
    {
        $this->testAddCustomerWithAllData();
        $this->browse(function (Browser $browser) {
            $browser->visit('contact/customer')
                ->assertSee('Customers')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(9) > div > div > a:nth-child(3)')
                ->waitFor('#confirm-delete', 5)
                ->whenAvailable('#confirm-delete', function ($modal) {
                    $modal
                        ->click('#delete_link');
                })
                ->waitFor('.toast-message')
                ->assertSee('Contact Deleted Successfully');
        });
    }
}
