<?php

namespace Tests\Browser\Modules\Location;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Laravel\Dusk\Browser;
use Modules\Inventory\Entities\ShowRoom;
use Tests\Browser\Traits\PurchaseTrait;
use Tests\DuskTestCase;

class BranchTest extends DuskTestCase
{
    use PurchaseTrait;

    public function tearDown(): void
    {
        $branches = ShowRoom::where('id', '!=', 1)->get();
        foreach ($branches as $branch){
            $branch->delete();
        }
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testVisitPageWithOutAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/location/showroom')
                ->assertPathIs('/login');
        });

    }

    public function testVisitPageWithAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/location/showroom')
                ->assertSee('Branch List');
        });
    }

    public function testCreateBranchWithRequiredField()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser->click('#main-content > section > div > div > div.col-12 > div > div > ul > li > a')
                ->whenAvailable('#ShowRoom_Add', function ($modal) {
                    $modal->type('name', 'Dhaka Branch')
                        ->click('#save_button_parent');
                })->with('.table', function ($table){
                    $table->pause(5000)
                        ->assertSee('Dhaka Branch');
                });
        });
    }

    public function testEditBranchWithRequiredField()
    {
        $this->testCreateBranchWithRequiredField();
        $this->browse(function (Browser $browser) {
            $browser->visit('/location/showroom')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(7) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(7) > div > div > a:nth-child(2)')
                ->whenAvailable('#ShowRoom_Edit', function ($modal) {
                    $modal->pause(3000)
                        ->type('name', $this->faker->name)
                        ->click('#update_save_button_parent');
                })
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Branch has been updated Successfully');
        });
    }

    public function testCreateBranchWithAllField()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser->click('#main-content > section > div > div > div.col-12 > div > div > ul > li > a')
                ->whenAvailable('#ShowRoom_Add', function ($modal) {
                    $modal->type('name', 'Dhaka Branch')
                        ->type('email', $this->faker->email)
                        ->type('phone', $this->faker->phoneNumber)
                        ->type('address', 'Dhaka, Bangladesh')
                        ->click('#save_button_parent');
                })
                ->with('.table', function ($table){
                    $table->pause(5000)
                        ->assertSee('Dhaka Branch');
                });
        });
    }

    public function testEditBranchWithAllField()
    {
        $this->testCreateBranchWithAllField();
        $this->browse(function (Browser $browser) {
            $browser->visit('/location/showroom')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(7) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(7) > div > div > a:nth-child(2)')
                ->whenAvailable('#ShowRoom_Edit', function ($modal) {
                    $modal->pause(3000)
                        ->type('name', $this->faker->name)
                        ->type('email', $this->faker->email)
                        ->type('phone', $this->faker->phoneNumber)
                        ->type('address', 'Dhaka, Bangladesh')
                        ->click('#update_save_button_parent');
                })
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Branch has been updated Successfully');
        });
    }

    public function testCreateBranchWithAllFieldStatusDeActive()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser->click('#main-content > section > div > div > div.col-12 > div > div > ul > li > a')
                ->whenAvailable('#ShowRoom_Add', function ($modal) {
                    $modal->type('name', $this->faker->name)
                        ->click('#showroom_addForm > div > div:nth-child(4) > div > div')
                        ->click('#showroom_addForm > div > div:nth-child(4) > div > div > ul > li:nth-child(2)')
                        ->click('#save_button_parent');
                })
                ->with('.table', function ($table){
                    $table->waitFor('.badge_4')
                        ->assertSee('De-Active');
                });

        });
    }

    public function testEditBranchWithAllFieldsChangeStatusDeActiveToActive()
    {
        $this->testCreateBranchWithAllFieldStatusDeActive();
        $this->browse(function (Browser $browser){
            $browser->visit('/location/showroom')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(7) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(7) > div > div > a:nth-child(2)')
                ->whenAvailable('#ShowRoom_Edit', function ($modal) {
                    $modal->pause(3000)
                        ->type('name', $this->faker->name)
                        ->click('#showroom_EditForm > div > div:nth-child(4) > div > div')
                        ->click('#showroom_EditForm > div > div:nth-child(4) > div > div > ul > li:nth-child(1)')
                        ->click('#update_save_button_parent');
                })
                ->waitFor('.toast-message')
                ->with('.table', function ($table){
                    $table->waitFor('.badge_1')
                        ->assertSee('Active');
                })
                ->assertSeeIn('.toast-message', 'Branch has been updated Successfully');
        });

    }

    public function testDeleteBranch (){
        $this->testCreateBranchWithAllField();
        $this->browse(function(Browser $browser){
            $browser->visit('/location/showroom')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(7) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(7) > div > div > a:nth-child(3)')
                ->whenAvailable('#confirm-delete', function ($modal) {
                    $modal->click('#delete_link');
                })->waitFor('.toast-message')
                ->assertSee('Branch has been deleted Successfully');

        });
    }

    public function testShowBranchDetails (){
        $this->testCreateBranchWithAllField();
        $this->browse(function(Browser $browser){
            $browser->visit('/location/showroom')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(7) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(7) > div > div > a:nth-child(1)')

                ->assertSee('ShowRoom Details');

        });
    }

    public function testAddOpeningBalance (){
        $this->testShowBranchDetails();
        $this->browse(function(Browser $browser){
            $browser
                ->click('#main-content > section > div > div > div > div > div.box_header > ul > li > a')
                ->whenAvailable('#openning_balance_Add', function ($modal){
                    $modal->type('#openning_balance_addForm > div > div.col-xl-12 > div > input', 5000)
                        ->click('#save_button_parent');
                })
                ->pause(3000)
                ->assertSee('$ 5,000.00');

        });
    }

    public function testChangeBranchFromHeader(){
        $this->testCreateBranchWithAllField();
        $this->browse(function (Browser $browser){
           $browser->click('#main-content > div.container-fluid.no-gutters > div > div > div > div:nth-child(5) > div > div.nice-select.nice_Select.select_showroom.bgLess.mb-0')
               ->click('#main-content > div.container-fluid.no-gutters > div > div > div > div:nth-child(5) > div > div.nice-select.nice_Select.select_showroom.bgLess.mb-0.open > ul > li:nth-child(2)')
               ->waitForReload ()
               ->assertSee('Branch List');

        });
    }




}
