<?php


namespace Tests\Browser\Modules\Location;


use Laravel\Dusk\Browser;
use Tests\Browser\Traits\PurchaseTrait;
use Tests\DuskTestCase;

class StockAdjustmentTest extends DuskTestCase
{
    use PurchaseTrait;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->createProduct();
    }

    public function tearDown(): void
    {
        $this->clearTable();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testVisitPageWithoutLogin(){
        $this->browse(function (Browser $browser) {
            $browser->visit('inventory/stock-adjustment/lists')
                ->assertPathIs('/login');
        });
    }


    public function testVisitPageWithLogin(){
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
            ->visit('inventory/stock-adjustment/lists')
                ->assertSee('Stock Adjustments');
        });
    }

    public function testStockAdjustment(){
        $this->testVisitPageWithLogin();

        $this->browse(function (Browser $browser){
            $browser
                ->click('#main-content > div.row.justify-content-center > div.col-12 > div > div > ul > li > a')
                ->assertPathIs('/inventory/stock-adjustment/create')
                ->assertSee('New Stock Adjustments')

                ->type('ref_no', $this->faker->randomNumber(4))
                ->type('recovery_amount', 100)

                ->click('#sale_form > div:nth-child(3) > div.col-4 > div > div')
                ->click('#sale_form > div:nth-child(3) > div.col-4 > div > div > ul > li:nth-child(2)')
                ->pause(3000)

                ->click('#sale_form > div:nth-child(3) > div.col-6 > div > div')
                ->click('#sale_form > div:nth-child(3) > div.col-6 > div > div > ul > li:nth-child(2)')
                ->pause(3000)

                ->type('#sale_form > div:nth-child(6) > div > div > div > div.note-editing-area > div.note-editable.card-block', $this->faker->paragraph)

                ->scrollIntoView('#sale_form > div:nth-child(7) > div > div > button')
                ->click('#sale_form > div:nth-child(7) > div > div > button')
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Stock Adjustment has been Added Successfully');
        });

    }

    public function testStockAdjustmentDetails(){
        $this->testStockAdjustment();
        $this->browse(function (Browser $browser){
            $browser->visit('/inventory/stock-adjustment/lists')
            ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(9) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(9) > div > div > a:nth-child(4)')
                ->assertSee('Stock Adjustment Details');
        });
    }

    public function testStockAdjustmentEdit(){
        $this->testStockAdjustment();
        $this->browse(function (Browser $browser){
            $browser->visit('/inventory/stock-adjustment/lists')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(9) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(9) > div > div > a:nth-child(2)')
                ->assertSee('Update Stock Adjustments')
                ->click('#sale_form > div:nth-child(7) > div > div > button')
                ->waitFor('.toast-message')
                ->assertSee('Stock Adjustment Updated Successfully');
        });
    }


    public function testDeleteAdjustment (){
        $this->testStockAdjustment();
        $this->browse(function(Browser $browser){
            $browser->visit('/inventory/stock-adjustment/lists')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(9) > div > button')
                    ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(9) > div > div > a:nth-child(3)')
                ->whenAvailable('#confirm-delete', function ($modal) {
                    $modal->click('#delete_link');
                })->waitFor('.toast-message')
                ->assertSee('Stock Adjustment Deleted Successfully');

        });
    }

    public function testApproveAdjustment (){
        $this->testStockAdjustment();
        $this->browse(function(Browser $browser){
            $browser->visit('/inventory/stock-adjustment/lists')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(9) > div > button')
                    ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(9) > div > div > a.dropdown-item.edit_brand')
                ->whenAvailable('#confirm-approve', function ($modal) {
                    $modal->click('#approve_link');
                })->waitFor('.toast-message')
                ->assertSee('Sale has Been Approved');

        });
    }


}
