<?php


namespace Tests\Browser\Modules\Location;


use Laravel\Dusk\Browser;
use Tests\Browser\Traits\PurchaseTrait;
use Tests\DuskTestCase;

class StockTransferTest extends DuskTestCase
{
    use PurchaseTrait;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->createProduct();
        $this->createShowRoom();
    }

    public function tearDown(): void
    {
        $this->clearTable();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testVisitPageWithoutLogin(){
        $this->browse(function (Browser $browser) {
            $browser->visit('inventory/stock-transfer')
                ->assertPathIs('/login');
        });
    }


    public function testVisitPageWithLogin(){
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
            ->visit('inventory/stock-transfer')
                ->assertSee('Stock Transfer');
        });
    }

    public function testStockTransfer(){

        $this->testVisitPageWithLogin();

        $this->browse(function (Browser $browser){
            $browser
                ->click('#main-content > div.row.justify-content-center > div.col-12 > div > div > ul > li > a')
                ->assertPathIs('/inventory/stock-transfer/create')
                ->assertSee('Transfer Product')
                ->click('#add_product > section > div > div > div:nth-child(2) > div > form > div:nth-child(2) > div:nth-child(1) > div > div')
                ->click('#add_product > section > div > div > div:nth-child(2) > div > form > div:nth-child(2) > div:nth-child(1) > div > div > ul > li:nth-child(3)')
                ->pause(4000)

                ->click('#add_product > section > div > div > div:nth-child(2) > div > form > div:nth-child(2) > div:nth-child(2) > div > div')
                ->click('#add_product > section > div > div > div:nth-child(2) > div > form > div:nth-child(2) > div:nth-child(2) > div > div > ul > li:nth-child(2)')

                ->click('#add_product > section > div > div > div:nth-child(2) > div > form > div:nth-child(4) > div.col-6 > div > div')
                ->click('#add_product > section > div > div > div:nth-child(2) > div > form > div:nth-child(4) > div.col-6 > div > div > ul > li:nth-child(2)')
                ->pause(3000)
                /*->click('#add_product > section > div > div > div:nth-child(2) > div > form > div:nth-child(4) > div.col-6 > div > div')
                ->click('#add_product > section > div > div > div:nth-child(2) > div > form > div:nth-child(4) > div.col-6 > div > div > ul > li:nth-child(3)')
                ->whenAvailable('#Item_Details', function ($modal){
                    $modal->click('div > div > div.modal-body > form > div > div:nth-child(1) > a > img')
                        ->pause(3000);
                })*/
                ->type('#add_product > section > div > div > div:nth-child(2) > div > form > div:nth-child(6) > div > div > div > div.note-editing-area > div.note-editable.card-block', $this->faker->paragraph)
                ->click('#add_product > section > div > div > div:nth-child(2) > div > form > div.col-12.mt-20 > div > button')
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Product Added To Transfer List');
        });

    }

    /*public function testStockTransferDetails(){
        $this->testStockTransfer();
        $this->browse(function (Browser $browser){
            $browser->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(6) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(6) > div > div > a:nth-child(1)')
                ->assertSee('Sent From');
        });
    }*/

    public function testStockTransferEdit(){
        $this->testStockTransfer();
        $this->browse(function (Browser $browser){
            $browser->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(6) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(6) > div > div > a:nth-child(2)')
                ->assertSee('Edit Transfer')
                ->click('#add_product > section > div > div > div:nth-child(2) > div > form > div.col-12.mt-20 > div > button')
                ->waitFor('.toast-message')
                ->assertSee('Product Updated To Transfer List Successfully');
        });
    }


    public function testDeleteTransfer (){
        $this->testStockTransfer();
        $this->browse(function(Browser $browser){
            $browser
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(6) > div > button')
                    ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(6) > div > div > a.dropdown-item.edit_brand')
                ->whenAvailable('#confirm-delete', function ($modal) {
                    $modal->click('#delete_link');
                })->waitFor('.toast-message')
                ->assertSee('Product deleted from Transfer List');

        });
    }

    public function testApproveTransfer (){
        $this->testStockTransfer();
        $this->browse(function(Browser $browser){
            $browser
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(6) > div > button')
                    ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(6) > div > div > a:nth-child(1)')
                ->whenAvailable('#confirm-approve', function ($modal) {
                    $modal->click('#approve_link');
                })->waitFor('.toast-message')
                ->assertSee('Stock Transfer Approve Successfully');

        });
    }

    public function testReceiveTransfer (){
        $this->testApproveTransfer();
        $this->browse(function(Browser $browser){
            $browser
                ->pause(3000)
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(6) > div > button')
                    ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(6) > div > div > a:nth-child(1)')
                ->whenAvailable('#confirm-approve', function ($modal) {
                    $modal->click('#approve_link');
                })->waitFor('.toast-message')
                ->assertSee('Stock Received Successfully');

        });
    }

}
