<?php

namespace Tests\Browser\Modules\Location;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\WithFaker;
use Laravel\Dusk\Browser;
use Modules\Inventory\Entities\WareHouse;
use Tests\DuskTestCase;

class WareHouseTest extends DuskTestCase
{
    use withFaker;

    public function tearDown(): void
    {
        $ware_houses = WareHouse::get();
        foreach ($ware_houses as $ware_house){
            $ware_house->delete();
        }
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testVisitPageWithOutAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/location/warehouse')
                ->assertPathIs('/login');
        });

    }

    public function testVisitPageWithAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/location/warehouse')
                ->assertSee('Warehouse List');
        });
    }

    public function testCreateWareHouseWithRequiredField()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser->click('#main-content > section > div > div > div.col-12 > div > div > ul > li > a')
                ->whenAvailable('#WareHouse_Add', function ($modal) {
                    $modal->type('name', 'Dhaka WareHouse')
                        ->click('#save_button_parent');
                })->with('.table', function ($table){
                    $table->pause(5000)
                        ->assertSee('Dhaka WareHouse');
                });
        });
    }

    public function testEditWareHouseWithRequiredField()
    {
        $this->testCreateWareHouseWithRequiredField();
        $this->browse(function (Browser $browser) {
            $browser->visit('/location/warehouse')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(7) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(7) > div > div > a:nth-child(1)')
                ->whenAvailable('#Warehouse_Edit', function ($modal) {
                    $modal->pause(3000)
                        ->type('name', $this->faker->name)
                        ->click('#update_save_button_parent');
                })
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'WareHouse has been updated Successfully');
        });
    }

    public function testCreateWareHouseWithAllField()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser->click('#main-content > section > div > div > div.col-12 > div > div > ul > li > a')
                ->whenAvailable('#WareHouse_Add', function ($modal) {
                    $modal->type('name', 'Dhaka WareHouse')
                        ->type('email', $this->faker->email)
                        ->type('phone', $this->faker->phoneNumber)
                        ->type('address', 'Dhaka, Bangladesh')
                        ->click('#save_button_parent');
                })
                ->with('.table', function ($table){
                    $table->pause(5000)
                        ->assertSee('Dhaka WareHouse');
                });
        });
    }

    public function testEditWareHouseWithAllField()
    {
        $this->testCreateWareHouseWithAllField();
        $this->browse(function (Browser $browser) {
            $browser->visit('/location/warehouse')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(7) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(7) > div > div > a:nth-child(1)')
                ->whenAvailable('#Warehouse_Edit', function ($modal) {
                    $modal->pause(3000)
                        ->type('name', $this->faker->name)
                        ->type('email', $this->faker->email)
                        ->type('phone', $this->faker->phoneNumber)
                        ->type('address', 'Dhaka, Bangladesh')
                        ->click('#update_save_button_parent');
                })
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'WareHouse has been updated Successfully');
        });
    }

    public function testCreateWareHouseWithAllFieldStatusDeActive()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser->click('#main-content > section > div > div > div.col-12 > div > div > ul > li > a')
                ->whenAvailable('#WareHouse_Add', function ($modal) {
                    $modal->type('name', $this->faker->name)
                        ->click('#warehouse_addForm > div > div:nth-child(4) > div > div')
                        ->click('#warehouse_addForm > div > div:nth-child(4) > div > div > ul > li:nth-child(2)')
                        ->click('#save_button_parent');
                })
                ->with('.table', function ($table){
                    $table->waitFor('.badge_4')
                        ->assertSee('De-Active');
                });

        });
    }

    public function testEditWareHouseWithAllFieldsChangeStatusDeActiveToActive()
    {
        $this->testCreateWareHouseWithAllFieldStatusDeActive();
        $this->browse(function (Browser $browser){
            $browser->visit('/location/warehouse')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(7) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(7) > div > div > a:nth-child(1)')
                ->whenAvailable('#Warehouse_Edit', function ($modal) {
                    $modal->pause(3000)
                        ->type('name', $this->faker->name)
                        ->click('#division_editForm > div > div:nth-child(4) > div > div')
                        ->click('#division_editForm > div > div:nth-child(4) > div > div > ul > li:nth-child(1)')
                        ->click('#update_save_button_parent');
                })
                ->waitFor('.toast-message')
                ->with('.table', function ($table){
                    $table->waitFor('.badge_1')
                        ->assertSee('Active');
                })
                ->assertSeeIn('.toast-message', 'WareHouse has been updated Successfully');
        });

    }

    public function testDeleteWareHouse (){
        $this->testCreateWareHouseWithAllField();
        $this->browse(function(Browser $browser){
            $browser->visit('/location/warehouse')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(7) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(7) > div > div > a:nth-child(2)')
                ->whenAvailable('#confirm-delete', function ($modal) {
                    $modal->click('#delete_link');
                })->waitFor('.toast-message')
                ->assertSee('WareHouse has been deleted Successfully');

        });
    }

}
