<?php


namespace Tests\Browser\Modules\SystemSettings;


use Illuminate\Foundation\Testing\WithFaker;
use Laravel\Dusk\Browser;
use Modules\Setup\Entities\Tax;
use Tests\DuskTestCase;

class TaxTest extends DuskTestCase
{
    use withFaker;

    public function tearDown(): void
    {
        $taxes = Tax::get();
        foreach ($taxes as $tax) {
            $tax->account()->delete();
            $tax->delete();
        }
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testVisitPageWithOutAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/setup/tax')
                ->assertPathIs('/login');
        });

    }

    public function testVisitPageWithAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/setup/tax')
                ->assertSee('Tax List');
        });
    }

    public function testCreateTaxWithRequiredField()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $name = $this->faker->name;
            $browser->click('#main-content > section > div > div > div.col-12 > div > div > ul > li > a')
                ->whenAvailable('#Tax_Add', function ($modal) use ($name) {
                    $modal->type('name', $name)
                        ->type('rate', 15)
                        ->click('#tax_addForm > div > div.col-lg-12.text-center > div > button');
                })->waitFor('.table')
                ->pause(5000)
                ->with('.table', function ($table) use ($name) {
                    $table->assertSee($name);
                });
        });
    }

    public function testEditTaxWithRequiredField()
    {
        $this->testCreateTaxWithRequiredField();
        $this->browse(function (Browser $browser) {
            $name = $this->faker->name;
            $browser->visit('/setup/tax')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(6) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(6) > div > div > a')
                ->whenAvailable('#Tax_Edit', function ($modal) use($name) {
                    $modal->pause(3000)
                        ->type('name', $name)
                        ->click('#tax_EditForm > div > div.col-lg-12.text-center > div > button');
                })
                ->waitFor('.table')
                ->pause(5000)
                ->with('.table', function ($table) use ($name) {
                    $table->assertSee($name);
                });
        });
    }

    public function testCreateTaxWithAllField()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $name = $this->faker->name;
            $browser->click('#main-content > section > div > div > div.col-12 > div > div > ul > li > a')
                ->whenAvailable('#Tax_Add', function ($modal) use ($name) {
                    $modal->type('name', $name)
                        ->type('rate', 15)
                        ->type('description', $this->faker->paragraph)
                        ->click('#tax_addForm > div > div.col-lg-12.text-center > div > button');
                })->waitFor('.table')
                ->pause(5000)
                ->with('.table', function ($table) use ($name) {
                    $table->assertSee($name);
                });
        });
    }

    public function testEditTaxWithAllField()
    {
        $this->testCreateTaxWithAllField();
        $this->browse(function (Browser $browser) {
            $name = $this->faker->name;
            $browser->visit('/setup/tax')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(6) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(6) > div > div > a')
                ->whenAvailable('#Tax_Edit', function ($modal) use($name) {
                    $modal->pause(3000)
                        ->type('name', $name)
                        ->type('rate', 15)
                        ->type('description', $this->faker->paragraph)
                        ->click('#tax_EditForm > div > div.col-lg-12.text-center > div > button');
                })
                ->waitFor('.table')
                ->pause(5000)
                ->with('.table', function ($table) use ($name) {
                    $table->assertSee($name);
                });
        });
    }


}
