<?php

return [

    "Generated By" => "تم الإنشاء بواسطة",  

"Please Enter Your Credit details" => "يرجى إدخال تفاصيل الائتمان الخاصة بك",  

"Please Enter Your Debit details" => "يرجى إدخال تفاصيل الخصم الخاصة بك",  

"This was selected before Without Changing this you cannot submit this" => "تم تحديد هذا مسبقًا، لا يمكنك الإرسال دون تغييره",  

"This item is already added" => "تمت إضافة هذا العنصر بالفعل",  

"Please Select Customer First" => "يرجى اختيار العميل أولاً",  

"Your due is greater than your credit limit" => "المبلغ المستحق عليك أكبر من الحد الائتماني الخاص بك",  

"Something went wrong" => "حدث خطأ ما",  

"Approval has been changed Successfully" => "تم تغيير الموافقة بنجاح",  

"browse" => "تصفح",  

"type" => "النوع",  

"delete" => "حذف",  

"select" => "اختر",  

"Delete" => "حذف",  

"Select" => "اختر",  

"Something Went Wrong" => "حدث خطأ ما",  

"Type" => "النوع",  

"Browse" => "تصفح",  

"Add Value" => "إضافة قيمة",  

"Success" => "نجاح",  

"Error" => "خطأ",  

"Show" => "عرض",  

"Purchase Price" => "سعر الشراء",  

"Quick Search" => "بحث سريع",  

"Browse file" => "استعراض ملف",  

"value" => "القيمة",  

"Bank Name" => "اسم البنك",  

"Narration" => "الوصف",  

"Amount" => "المبلغ",  

"Total" => "الإجمالي",  

"Cash" => "نقدًا",  

"Select one" => "اختر واحدًا",  

"Please Enter Your credit details" => "يرجى إدخال تفاصيل الائتمان الخاصة بك",  

"Branch" => "الفرع",  

"entries" => "المدخلات",  

"No data available in table" => "لا توجد بيانات متاحة في الجدول",  

"Showing page" => "عرض الصفحة",  

"of" => "من",  

"No records available" => "لا توجد سجلات متاحة",  

"filtered from" => "تمت التصفية من",  

"total records" => "إجمالي السجلات",  

"What you are looking is not found" => "العنصر الذي تبحث عنه غير موجود",  

"Opps" => "عذرًا!",  

"Something went wrong. If you are seeing this message multiple times, please contact Spondon IT authors." => "حدث خطأ ما. إذا كنت ترى هذه الرسالة عدة مرات، يرجى الاتصال بمطوري Spondon IT.",  

"Something is not right" => "هناك شيء غير صحيح",  

"Validation Error" => "خطأ في التحقق",  

"Select City" => "اختر المدينة",  

"Select State" => "اختر الولاية",  

"Value" => "القيمة",  

"Payment Method" => "طريقة الدفع",  

"Account No" => "رقم الحساب",  

"Alert QTY" => "تنبيه الكمية",  

"Alert Qty" => "تنبيه الكمية",  

"Selling Price" => "سعر البيع",  

"Product Images" => "صور المنتج",  

"amount" => "المبلغ",  

"Browse File" => "استعراض ملف",  

"Select One" => "اختر واحدًا",  

"Min. Selling Price" => "أدنى سعر بيع",  

"success" => "نجاح",  

"Account Owner" => "مالك الحساب",  

"Enter Amount" => "أدخل المبلغ",  

"Updated Successfully" => "تم التحديث بنجاح",  

"Tax" => "الضريبة",  

"Price" => "السعر",  

"Quantity" => "الكمية",  



];

