<?php
return [
    "Generated By" => "Generado por",

    "Please Enter Your Credit details" => "Especifique sus detalles de crédito",

    "Please Enter Your Debit details" => "Por favor, introduzca sus datos de débito",

    "This was selected before Without Changing this you cannot submit this" => "Esto se ha seleccionado antes Sin cambiar esto no puede enviar este",

    "This item is already added" => "Este elemento ya se ha añadido",

    "Please Select Customer First" => "Seleccione primero el cliente",

    "Your due is greater than your credit limit" => "Su vencimiento es mayor que su límite de crédito",

    "Something went wrong" => "Algo salió mal",

    "Approval has been changed Successfully" => "La aprobación se ha cambiado satisfactoriamente",

    "browse" => "Examinar",

    "type" => "Tipo",

    "delete" => "Suprimir",

    "select" => "Seleccione",

    "Delete" => "Suprimir",

    "Select" => "Seleccione",

    "Something Went Wrong" => "Algo Salió Mal",

    "Type" => "Tipo",

    "Browse" => "Examinar",

    "Add Value" => "Añadir valor",

    "Success" => "Éxito",

    "Error" => "Error",

    "Show" => "Mostrar",

    "Purchase Price" => "Precio de compra",

    "Quick Search" => "Búsqueda rápida",

    "Browse file" => "Buscar archivo",

    "value" => "Valor",

    "Bank Name" => "Nombre del banco",

    "Narration" => "Narración",

    "Amount" => "Importe",

    "Total" => "Total",

    "Cash" => "Efectivo",

    "Select one" => "Seleccione uno",

    "Please Enter Your credit details" => "Por favor, introduzca sus datos de crédito",

    "Branch" => "Sucursal",

    "entries" => "entradas",

    "No data available in table" => "No hay datos disponibles en la tabla",

    "Showing page" => "Mostrar página",

    "of" => "de",

    "No records available" => "No hay registros disponibles",

    "filtered from" => "filtrado de",

    "total records" => "Registros totales",

    "What you are looking is not found" => "Lo que está buscando no se encuentra",

    "Opps" => "¡Ops!",

    "Something went wrong. If you are seeing this message multiple times, please contact Spondon IT authors." => "Algo salió mal. Si está viendo este mensaje varias veces, póngase en contacto con los autores de IT.",

    "Something is not right" => "Algo no está bien",

    "Validation Error" => "Error de validación",

    "Select City" => "Seleccione Ciudad",

    "Select State" => "Seleccionar Estado",

    "Value" => "Valor",

    "Payment Method" => "Método de pago",

    "Account No" => "Número de cuenta",

    "Alert QTY" => "Alerta QTY",

    "Alert Qty" => "Alerta Qty",

    "Selling Price" => "Precio de venta",

    "Product Images" => "Imágenes del producto",

    "amount" => "Importe",

    "Browse File" => "Buscar archivo",

    "Select One" => "Seleccione uno",

    "Min. Selling Price" => "Min. Precio de venta",

    "success" => "Color de éxito",

    "Account Owner" => "Propietario de cuenta",

    "Enter Amount" => "Especifique el importe",

    "Updated Successfully" => "Actualizado correctamente",

    "Tax" => "Impuesto",
    "Price" => "Precio",
    "Quantity" => "Cantidad",

];
