<?php

namespace Tests\Browser\Modules\Leave;

use App\Staff;
use App\User;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\WithFaker;
use Laravel\Dusk\Browser;
use Modules\Leave\Entities\ApplyLeave;
use Modules\Leave\Entities\LeaveDefine;
use Modules\Leave\Entities\LeaveType;
use Tests\DuskTestCase;

class ApplyLeaveTest extends DuskTestCase
{
    use withFaker;

    protected $leaveTypes = [];
    protected $users = [];

    public function setUp(): void
    {
        parent::setUp();
        for ($i = 0; $i < 3; $i++) {
            $this->leaveTypes[] = LeaveType::create([
                'name' => $this->faker->name
            ]);
        }

        for ($i = 0; $i < 10; $i++) {
            $user = User::create([
                'email' => $this->faker->email,
                'name' => $this->faker->name,
                'role_id' => rand(2, 3)
            ]);

            Staff::create([
                'user_id' => $user->id,
                'leave_applicable_date' => date('Y-m-d')
            ]);

            $this->users[] = $user;

        }


    }

    public function tearDown(): void
    {
        $leaves = ApplyLeave::get();

        foreach ($leaves as $leave) {
            $leave->delete();
        }

        foreach ($this->users as $user) {
            $user->staff()->delete();
            $user->delete();
        }

        foreach ($this->leaveTypes as $leaveType) {
            $leaveType->delete();
        }

        parent::tearDown(); // TODO: Change the autogenerated stub
    }


    public function testApplyFirstHalfDayLeave()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/leave')
                ->click('#main-content > section > div > div > div.col-12 > div > div > ul > li > a')
                ->waitFor('#ApplyLeave', 5)
                ->whenAvailable('#ApplyLeave', function ($modal) {
                    $modal
                        ->click('#apply_leave_Form > div > div:nth-child(1) > div > div')
                        ->click('#apply_leave_Form > div > div:nth-child(1) > div > div > ul > li')
                        ->click('#apply_leave_Form > div > div:nth-child(3) > div > div')
                        ->click('#apply_leave_Form > div > div:nth-child(3) > div > div > ul > li')
                        ->type('apply_date', Carbon::today()->format('m/d/Y'))
                        ->type('start_date', Carbon::today()->addDay()->format('m/d/Y'))
                        ->click('div > div > div.modal-header')
                        ->click('#half_day_checkbox > li:nth-child(2) > label > span')
                        ->type('reason', 'Sick')
                        ->click('#save_button_parent');
                })
                ->waitForReload()
                ->assertSee(Carbon::today()->addDay()->format('jS M, Y'));
        });
    }


    public function testApplySecondHalfDayLeave()
    {
        $this->browse(function (Browser $browser) {
            $this->browse(function (Browser $browser) {
                $browser->loginAs(1)
                    ->visit('/leave')
                    ->click('#main-content > section > div > div > div.col-12 > div > div > ul > li > a')
                    ->waitFor('#ApplyLeave', 5)
                    ->whenAvailable('#ApplyLeave', function ($modal) {
                        $modal
                            ->click('#apply_leave_Form > div > div:nth-child(1) > div > div')
                            ->click('#apply_leave_Form > div > div:nth-child(1) > div > div > ul > li')
                            ->click('#apply_leave_Form > div > div:nth-child(3) > div > div')
                            ->click('#apply_leave_Form > div > div:nth-child(3) > div > div > ul > li')
                            ->type('apply_date', Carbon::today()->format('m/d/Y'))
                            ->type('start_date', Carbon::today()->addDay()->format('m/d/Y'))
                            ->click('div > div > div.modal-header')
                            ->click('#half_day_checkbox > li:nth-child(3) > label > span')
                            ->type('reason', 'Sick')
                            ->click('#save_button_parent');
                    })
                    ->waitForReload()
                    ->assertSee(Carbon::today()->addDay()->format('jS M, Y'));

            });
        });
    }

    public function testApplyFirstHalfDayMakeUpLeave()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/leave')
                ->click('#main-content > section > div > div > div.col-12 > div > div > ul > li > a')
                ->waitFor('#ApplyLeave', 5)
                ->whenAvailable('#ApplyLeave', function ($modal) {
                    $modal
                        ->click('#apply_leave_Form > div > div:nth-child(1) > div > div')
                        ->click('#apply_leave_Form > div > div:nth-child(1) > div > div > ul > li')
                        ->click('#apply_leave_Form > div > div:nth-child(3) > div > div')
                        ->click('#apply_leave_Form > div > div:nth-child(3) > div > div > ul > li')
                        ->type('apply_date', Carbon::today()->format('m/d/Y'))
                        ->type('start_date', Carbon::today()->addDay()->format('m/d/Y'))
                        ->click('#half_day_checkbox > li:nth-child(2) > label > span')
                        ->click('#make_up_leave_checkbox > li > label > span')
                        ->type('makeup_date', $this->faker->date('m/d/Y'))
                        ->click('#make_up_half_day_checkbox > li:nth-child(1) > label > span')
                        ->click('div > div > div.modal-header')
                        ->type('reason', 'Sick')
                        ->click('#save_button_parent');
                })
                ->waitForReload()
                ->assertSee(Carbon::today()->addDay()->format('jS M, Y'));
        });
    }

    public function testApplySingleDayLeave()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/leave')
                ->click('#main-content > section > div > div > div.col-12 > div > div > ul > li > a')
                ->waitFor('#ApplyLeave', 5)
                ->whenAvailable('#ApplyLeave', function ($modal) {
                    $modal
                        ->click('#apply_leave_Form > div > div:nth-child(1) > div > div')
                        ->click('#apply_leave_Form > div > div:nth-child(1) > div > div > ul > li')
                        ->click('#apply_leave_Form > div > div:nth-child(3) > div > div')
                        ->click('#apply_leave_Form > div > div:nth-child(3) > div > div > ul > li')
                        ->type('apply_date', Carbon::today()->format('m/d/Y'))
                        ->type('start_date', Carbon::today()->addDay()->format('m/d/Y'))
                        ->click('div > div > div.modal-header')

                        ->click('#apply_leave_Form > div > div:nth-child(4) > div > div')
                        ->click('#apply_leave_Form > div > div:nth-child(4) > div > div > ul > li:nth-child(2)')

                        ->type('reason', 'Sick')
                        ->click('#save_button_parent');
                })
                ->waitForReload()
                ->assertSee(Carbon::today()->addDay()->format('jS M, Y'));
        });
    }

    public function testApplySingleDayMakeupLeave()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/leave')
                ->click('#main-content > section > div > div > div.col-12 > div > div > ul > li > a')
                ->waitFor('#ApplyLeave', 5)
                ->whenAvailable('#ApplyLeave', function ($modal) {
                    $modal
                        ->click('#apply_leave_Form > div > div:nth-child(4) > div > div')
                        ->click('#apply_leave_Form > div > div:nth-child(4) > div > div > ul > li:nth-child(2)')

                        ->click('#make_up_leave_checkbox > li > label > span')
                        ->type('makeup_date', Carbon::today()->addDays(5)->format('m/d/Y'))

                        ->click('#apply_leave_Form > div > div:nth-child(1) > div > div')
                        ->click('#apply_leave_Form > div > div:nth-child(1) > div > div > ul > li')
                        ->click('#apply_leave_Form > div > div:nth-child(3) > div > div')
                        ->click('#apply_leave_Form > div > div:nth-child(3) > div > div > ul > li')
                        ->type('apply_date', Carbon::today()->format('m/d/Y'))
                        ->type('start_date', Carbon::today()->addDay()->format('m/d/Y'))
                        ->click('div > div > div.modal-header')





                        ->type('reason', 'Sick')
                        ->click('#save_button_parent');
                })
                ->waitForReload()
                ->assertSee(Carbon::today()->addDay()->format('jS M, Y'));
        });
    }

    public function testApplyMultipleDayLeave()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/leave')
                ->click('#main-content > section > div > div > div.col-12 > div > div > ul > li > a')
                ->waitFor('#ApplyLeave', 5)
                ->whenAvailable('#ApplyLeave', function ($modal) {
                    $modal
                        ->click('#apply_leave_Form > div > div:nth-child(4) > div > div')
                        ->click('#apply_leave_Form > div > div:nth-child(4) > div > div > ul > li:nth-child(3)')

                        ->type('end_date', Carbon::today()->addDays(5)->format('m/d/Y'))

                        ->click('div > div > div.modal-header')

                        ->click('#apply_leave_Form > div > div:nth-child(1) > div > div')
                        ->click('#apply_leave_Form > div > div:nth-child(1) > div > div > ul > li')
                        ->click('#apply_leave_Form > div > div:nth-child(3) > div > div')
                        ->click('#apply_leave_Form > div > div:nth-child(3) > div > div > ul > li')
                        ->type('apply_date', Carbon::today()->format('m/d/Y'))
                        ->type('start_date', Carbon::today()->addDay()->format('m/d/Y'))
                        ->click('div > div > div.modal-header')


                        ->type('reason', 'Sick')
                        ->click('#save_button_parent');
                })
                ->waitForReload()
                ->assertSee(Carbon::today()->addDays(5)->format('jS M, Y'));
        });
    }

    public function testApplyMultipleDayStartDateHalfLeave()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/leave')
                ->click('#main-content > section > div > div > div.col-12 > div > div > ul > li > a')
                ->waitFor('#ApplyLeave', 5)
                ->whenAvailable('#ApplyLeave', function ($modal) {
                    $modal
                        ->click('#apply_leave_Form > div > div:nth-child(4) > div > div')
                        ->click('#apply_leave_Form > div > div:nth-child(4) > div > div > ul > li:nth-child(3)')

                        ->type('end_date', Carbon::today()->addDays(5)->format('m/d/Y'))

                        ->click('div > div > div.modal-header')

                        ->click('#apply_leave_Form > div > div:nth-child(1) > div > div')
                        ->click('#apply_leave_Form > div > div:nth-child(1) > div > div > ul > li')
                        ->click('#apply_leave_Form > div > div:nth-child(3) > div > div')
                        ->click('#apply_leave_Form > div > div:nth-child(3) > div > div > ul > li')
                        ->type('apply_date', Carbon::today()->format('m/d/Y'))
                        ->type('start_date', Carbon::today()->addDay()->format('m/d/Y'))
                        ->click('div > div > div.modal-header')
                        ->click('#half_day_checkbox > li.mr-0.pr-2 > label > span')
                        ->click('#half_day_checkbox > li:nth-child(2) > label > span')

                        ->type('reason', 'Sick')
                        ->click('#save_button_parent');
                })
                ->waitForReload()
                ->assertSee(Carbon::today()->addDays(5)->format('jS M, Y'));
        });
    }

    public function testApplyMultipleDayEndDayHalfLeave()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/leave')
                ->click('#main-content > section > div > div > div.col-12 > div > div > ul > li > a')
                ->waitFor('#ApplyLeave', 5)
                ->whenAvailable('#ApplyLeave', function ($modal) {
                    $modal
                        ->click('#apply_leave_Form > div > div:nth-child(4) > div > div')
                        ->click('#apply_leave_Form > div > div:nth-child(4) > div > div > ul > li:nth-child(3)')

                        ->type('end_date', Carbon::today()->addDays(5)->format('m/d/Y'))

                        ->click('div > div > div.modal-header')

                        ->click('#apply_leave_Form > div > div:nth-child(1) > div > div')
                        ->click('#apply_leave_Form > div > div:nth-child(1) > div > div > ul > li')
                        ->click('#apply_leave_Form > div > div:nth-child(3) > div > div')
                        ->click('#apply_leave_Form > div > div:nth-child(3) > div > div > ul > li')
                        ->type('apply_date', Carbon::today()->format('m/d/Y'))
                        ->type('start_date', Carbon::today()->addDay()->format('m/d/Y'))
                        ->click('div > div > div.modal-header')
                        ->click('#end_date_half_day_checkbox > li.mr-0.pr-2 > label > span')
                        ->click('#end_date_half_day_checkbox > li:nth-child(3) > label > span')

                        ->type('reason', 'Sick')
                        ->click('#save_button_parent');
                })
                ->waitForReload()
                ->assertSee(Carbon::today()->addDays(5)->format('jS M, Y'));
        });
    }

    public function testApplyMultipleDayHalfLeave()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/leave')
                ->click('#main-content > section > div > div > div.col-12 > div > div > ul > li > a')
                ->waitFor('#ApplyLeave', 5)
                ->whenAvailable('#ApplyLeave', function ($modal) {
                    $modal
                        ->click('#apply_leave_Form > div > div:nth-child(4) > div > div')
                        ->click('#apply_leave_Form > div > div:nth-child(4) > div > div > ul > li:nth-child(3)')

                        ->type('end_date', Carbon::today()->addDays(5)->format('m/d/Y'))

                        ->click('div > div > div.modal-header')

                        ->click('#apply_leave_Form > div > div:nth-child(1) > div > div')
                        ->click('#apply_leave_Form > div > div:nth-child(1) > div > div > ul > li')
                        ->click('#apply_leave_Form > div > div:nth-child(3) > div > div')
                        ->click('#apply_leave_Form > div > div:nth-child(3) > div > div > ul > li')
                        ->type('apply_date', Carbon::today()->format('m/d/Y'))
                        ->type('start_date', Carbon::today()->addDay()->format('m/d/Y'))
                        ->click('div > div > div.modal-header')

                        ->click('#half_day_checkbox > li.mr-0.pr-2.half > label > span')
                        ->click('#half_day_checkbox > li:nth-child(2) > label > span')
                        ->click('#end_date_half_day_checkbox > li.mr-0.pr-2 > label > span')
                        ->click('#end_date_half_day_checkbox > li:nth-child(3) > label > span')

                        ->type('reason', 'Sick')
                        ->click('#save_button_parent');
                })
                ->waitForReload()
                ->assertSee(Carbon::today()->addDays(5)->format('jS M, Y'));
        });
    }



    public function testHalfDayLeaveEdit()
    {
        $this->testApplyFirstHalfDayLeave();
        $this->browse(function (Browser $browser) {
            $browser
                ->visit('/leave')
                ->assertSee('Apply Leave')
                ->pause(1000)
                ->click('#dropdownMenu2')
                ->pause(1000)
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(7) > div > div > a:nth-child(1)')
                ->waitFor('#Apply_Leave_Edit', 5)
                ->whenAvailable('#Apply_Leave_Edit', function ($modal) {
                    $modal
                        ->pause(1000)
                        ->type('start_date', Carbon::today()->addDays(3)->format('m/d/Y'))
                        ->click('#applyLeaveEditForm > div > div.col-lg-12.text-center > div > button');
                })
                ->waitForReload()
                ->assertSee(Carbon::today()->addDays(3)->format('jS M, Y'));

        });
    }

    public function testMultipleDayHalfLeaveEdit()
    {
        $this->testApplyMultipleDayHalfLeave();
        $this->browse(function (Browser $browser) {
            $browser
                ->visit('/leave')
                ->assertSee('Apply Leave')
                ->pause(1000)
                ->click('#dropdownMenu2')
                ->pause(1000)
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(7) > div > div > a:nth-child(1)')
                ->waitFor('#Apply_Leave_Edit', 5)
                ->whenAvailable('#Apply_Leave_Edit', function ($modal) {
                    $modal
                        ->pause(1000)
                        ->type('start_date', Carbon::today()->addDays(3)->format('m/d/Y'))
                        ->click('#applyLeaveEditForm > div > div.col-lg-12.text-center > div > button');
                })
                ->waitForReload()
                ->assertSee(Carbon::today()->addDays(3)->format('jS M, Y'));

        });
    }

    public function testSecondHalfDayLeaveEdit()
    {
        $this->testApplySecondHalfDayLeave();
        $this->browse(function (Browser $browser) {
            $browser
                ->visit('/leave')
                ->assertSee('Apply Leave')
                ->pause(1000)
                ->click('#dropdownMenu2')
                ->pause(1000)
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(7) > div > div > a:nth-child(1)')
                ->waitFor('#Apply_Leave_Edit', 5)
                ->whenAvailable('#Apply_Leave_Edit', function ($modal) {
                    $modal
                        ->pause(1000)
                        ->type('start_date', Carbon::today()->addDays(3)->format('m/d/Y'))
                        ->click('#applyLeaveEditForm > div > div.col-lg-12.text-center > div > button');
                })
                ->waitForReload()
                ->assertSee(Carbon::today()->addDays(3)->format('jS M, Y'));

        });
    }

    public function testFirstHalfDayMakeUpLeaveEdit()
    {
        $this->testApplyFirstHalfDayMakeUpLeave();
        $this->browse(function (Browser $browser) {
            $browser
                ->visit('/leave')
                ->assertSee('Apply Leave')
                ->pause(1000)
                ->click('#dropdownMenu2')
                ->pause(1000)
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(7) > div > div > a:nth-child(1)')
                ->waitFor('#Apply_Leave_Edit', 5)
                ->whenAvailable('#Apply_Leave_Edit', function ($modal) {
                    $modal
                        ->pause(1000)
                        ->type('start_date', Carbon::today()->addDays(3)->format('m/d/Y'))
                        ->click('#applyLeaveEditForm > div > div.col-lg-12.text-center > div > button');
                })
                ->waitForReload()
                ->assertSee(Carbon::today()->addDays(3)->format('jS M, Y'));

        });
    }

    public function testSingleDayLeaveEdit()
    {
        $this->testApplySingleDayLeave();
        $this->browse(function (Browser $browser) {
            $browser
                ->visit('/leave')
                ->assertSee('Apply Leave')
                ->pause(1000)
                ->click('#dropdownMenu2')
                ->pause(1000)
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(7) > div > div > a:nth-child(1)')
                ->waitFor('#Apply_Leave_Edit', 5)
                ->whenAvailable('#Apply_Leave_Edit', function ($modal) {
                    $modal
                        ->pause(1000)
                        ->type('start_date', Carbon::today()->addDays(3)->format('m/d/Y'))
                        ->click('#applyLeaveEditForm > div > div.col-lg-12.text-center > div > button');
                })
                ->waitForReload()
                ->assertSee(Carbon::today()->addDays(3)->format('jS M, Y'));

        });
    }

    public function testLeaveDelete()
    {
        $this->testApplyFirstHalfDayLeave();
        $this->browse(function (Browser $browser) {
            $browser
                ->visit('/leave')
                ->assertSee('Apply Leave')
                ->click('#dropdownMenu2')
                ->pause(1000)
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(7) > div > div > a:nth-child(3)')
                ->waitFor('#confirm-delete', 5)
                ->whenAvailable('#confirm-delete', function ($modal) {
                    $modal
                        ->click('#delete_link');
                })
                ->waitFor('.toast-message', 10)
                ->assertSee('Apply Leave Deleted Successfully');

        });
    }


    public function testLeavePending()
    {
        $this->testApplyFirstHalfDayLeave();
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/leave/pending')
                ->assertSee('Pending Leave')
                ->pause(1000)
                ->click('#dropdownMenu2')
                ->pause(1000)
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(9) > div > div > a:nth-child(1)')
                ->waitFor('#Apply_Leave_Edit', 5)
                ->whenAvailable('#Apply_Leave_Edit', function ($modal) {
                    $modal
                        ->assertSee('Apply Leave Details');
                });
        });
    }

    public function testApprovePendingLeave()
    {
        $this->testApplyFirstHalfDayLeave();
        $this->browse(function (Browser $browser) {
            $browser
                ->visit('/leave/pending')
                ->assertSee('Pending Leave')
                ->pause(1000)
                ->click('#dropdownMenu2')
                ->pause(1000)
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(9) > div > div > a:nth-child(1)')
                ->waitFor('#Apply_Leave_Edit', 5)
                ->whenAvailable('#Apply_Leave_Edit', function ($modal) {
                    $modal
                        ->click('div > div > div.modal-body > div:nth-child(7) > div.col-xl-3 > div > div')
                        ->scrollIntoView('div > div > div.modal-body > div:nth-child(7) > div.col-xl-3 > div > div > ul > li:nth-child(2)')
                        ->click('div > div > div.modal-body > div:nth-child(7) > div.col-xl-3 > div > div > ul > li:nth-child(2)');

                })
                ->waitForReload()
                ->visit('leave/approved')
                ->assertSee('Approved');
        });
    }

    public function testCancelPendingLeave()
    {
        $this->testApplyFirstHalfDayLeave();
        $this->browse(function (Browser $browser) {
            $browser
                ->visit('/leave/pending')
                ->assertSee('Pending Leave')
                ->pause(1000)
                ->click('#dropdownMenu2')
                ->pause(1000)
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(9) > div > div > a:nth-child(1)')
                ->waitFor('#Apply_Leave_Edit', 5)
                ->whenAvailable('#Apply_Leave_Edit', function ($modal) {
                    $modal
                        ->click('div > div > div.modal-body > div:nth-child(7) > div.col-xl-3 > div > div')
                        ->scrollIntoView('div > div > div.modal-body > div:nth-child(7) > div.col-xl-3 > div > div > ul > li:nth-child(4)')
                        ->click('div > div > div.modal-body > div:nth-child(7) > div.col-xl-3 > div > div > ul > li:nth-child(4)');

                })
                ->waitForReload()
                ->visit('leave')
                ->assertSee('Cancelled');
        });
    }

    public function testVisitCarryForward()
    {
        $this->browse(function (Browser $browser){
            $browser->loginAs(1)
                ->visit('/leave/carry-forward')
                ->assertSee('Carry Forward');
        });
    }

    public function testEnableCarryForward()
    {
        $this->browse(function (Browser $browser){
            $browser->loginAs(1)
                ->visit('/leave/carry-forward')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(7) > label > div')
                ->waitFor('.toast-message')
                ->assertSee('Carry Forward Status Update');
        });
    }

    public function testDisableCarryForward()
    {
        $this->testEnableCarryForward();
        $this->browse(function (Browser $browser){
            $browser->loginAs(1)
                ->visit('/leave/carry-forward')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(7) > label > div')
                ->waitFor('.toast-message')
                ->assertSee('Carry Forward Status Update');
        });
    }
}
