<?php

namespace Tests\Browser\Modules\Leave;

use Carbon\Carbon;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\WithFaker;
use Laravel\Dusk\Browser;
use Modules\Leave\Entities\Holiday;
use Tests\DuskTestCase;

class HolidayTest extends DuskTestCase
{
    use withFaker;

    public function tearDown(): void
    {
        $holidays = Holiday::all();

        foreach ($holidays as $holiday) {
            $holiday->delete();
        }

        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testCreateYear()
    {
        $this->browse(function (Browser $browser){
            $browser->loginAs(1)
                ->visit('/leave/holidays')
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-4.holiday_setup > h3 > a')
                ->waitFor('#year_add', 5)
                ->whenAvailable('#year_add', function ($modal){
                    $modal
                        ->type('year', date('Y'))
                        ->pause(1000)
                        ->click('#save_year');
                })
                ->waitFor('.toast-message')
                ->assertSee('Year Created Successfully');
        });
    }

    public function testYearView()
    {
        $this->testCreateYear();
        $this->browse(function (Browser $browser){
            $browser
                ->click('#dropdownMenu2')
                ->pause(1000)
                ->click('#DataTables_Table_1 > tbody > tr:nth-child(1) > td:nth-child(3) > div > div > a:nth-child(1)')
                ->assertVisible('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8 > div > div.col-md-12 > div > div > div > div > table');
        });
    }

    public function testAddSingleDaySingleHoliday()
    {
        $this->testCreateYear();
        $this->browse(function (Browser $browser){
            $browser
                ->visit('/leave/holidays')
                ->pause(1000)
                ->click('#dropdownMenu2')
                ->pause(1000)
                ->click('#DataTables_Table_1 > tbody > tr:nth-child(1) > td:nth-child(3) > div > div > a:nth-child(2)')
                ->waitForText('HOLIDAY COPY FROM')
                ->type('holiday_name[]', $this->faker->name)
                ->type('date[]', date('m/d/Y'))
                ->pause(2000)
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > div.row.justify-content-center.mt-2 > button')
                ->waitFor('.toast-message')
                ->assertSee('Holiday Settings Saved Successfully');
        });
    }


    public function testAddSingleDayMultipleHoliday()
    {
        $this->testCreateYear();
        $this->browse(function (Browser $browser){
            $browser
                ->visit('/leave/holidays')
                ->pause(1000)
                ->click('#dropdownMenu2')
                ->pause(1000)
                ->click('#DataTables_Table_1 > tbody > tr:nth-child(1) > td:nth-child(3) > div > div > a:nth-child(2)')
                ->waitForText('HOLIDAY COPY FROM')
                ->type('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > table > tbody > tr > td:nth-child(1) > div > input',$this->faker->name)
                ->type('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > table > tbody > tr > td:nth-child(3) > div.single_date > div > div > div > div > div > input', date('m/d/Y'))
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > table > tbody > tr:nth-child(1) > td:nth-child(4) > a')
                ->type('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > table > tbody > tr.add_row > td:nth-child(1) > div > input', $this->faker->name)
                ->type('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > table > tbody > tr.add_row > td:nth-child(3) > div.single_date > div > div > div > div > div > input', Carbon::today()->addDays(3)->format('m/d/Y'))
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > table > tbody > tr:nth-child(1) > td:nth-child(4) > a')
                ->type('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > table > tbody > tr:nth-child(3) > td:nth-child(1) > div > input',$this->faker->name)
                ->type('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > table > tbody > tr:nth-child(3) > td:nth-child(3) > div.single_date > div > div > div > div > div > input', Carbon::today()->addDays(5)->format('m/d/Y'))
                ->pause(2000)
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > div.row.justify-content-center.mt-2 > button')
                ->waitFor('.toast-message')
                ->assertSee('Holiday Settings Saved Successfully')
            ->assertSee(Carbon::today()->addDays(3)->format('Y-m-d'));
        });
    }

    public function testAddMultipleDaySingleHoliday()
    {
        $this->testCreateYear();
        $this->browse(function (Browser $browser){
            $browser
                ->visit('/leave/holidays')
                ->pause(1000)
                ->click('#dropdownMenu2')
                ->pause(1000)
                ->click('#DataTables_Table_1 > tbody > tr > td:nth-child(3) > div > div > a:nth-child(2)')
                ->waitForText('HOLIDAY COPY FROM')
                ->type('holiday_name[]',$this->faker->name)
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > table > tbody > tr:nth-child(1) > td:nth-child(2) > div > div')
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > table > tbody > tr:nth-child(1) > td:nth-child(2) > div > div > ul > li:nth-child(2)')
                ->type('start_date[]', date('Y-m-d'))
                ->type('end_date[]', Carbon::today()->addDays(3)->format('m/d/Y'))
                ->pause(2000)
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > div.row.justify-content-center.mt-2 > button')
                ->waitFor('.toast-message')
                ->assertSee('Holiday Settings Saved Successfully')
            ->assertSee(Carbon::today()->addDays(3)->format('Y-m-d'));
        });
    }

    public function testAddMultipleDayMultipleHoliday()
    {
        $this->testCreateYear();
        $this->browse(function (Browser $browser){
            $browser
                ->visit('/leave/holidays')
                ->pause(1000)
                ->click('#dropdownMenu2')
                ->pause(1000)
                ->click('#DataTables_Table_1 > tbody > tr > td:nth-child(3) > div > div > a:nth-child(2)')
                ->waitForText('HOLIDAY COPY FROM')

                ->type('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > table > tbody > tr > td:nth-child(1) > div > input',$this->faker->name)
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > table > tbody > tr:nth-child(1) > td:nth-child(2) > div > div')
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > table > tbody > tr:nth-child(1) > td:nth-child(2) > div > div > ul > li:nth-child(2)')
                ->type('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > table > tbody > tr:nth-child(1) > td:nth-child(3) > div.multiple_date > div:nth-child(1) > div > div > div > div > input', date('m/d/Y'))
                ->type('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > table > tbody > tr:nth-child(1) > td:nth-child(3) > div.multiple_date > div:nth-child(2) > div > div > div > div > input', Carbon::today()->addDays(3)->format('m/d/Y'))

//                Add row
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > table > tbody > tr:nth-child(1) > td:nth-child(4) > a')

                ->type('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > table > tbody > tr.add_row > td:nth-child(1) > div > input',$this->faker->name)
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > table > tbody > tr:nth-child(2) > td:nth-child(2) > div > div')
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > table > tbody > tr:nth-child(2) > td:nth-child(2) > div > div > ul > li:nth-child(2)')

                ->type('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > table > tbody > tr:nth-child(2) > td:nth-child(3) > div.multiple_date > div:nth-child(1) > div > div > div > div > input', Carbon::today()->addDays(5)->format('m/d/Y'))
                ->type('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > table > tbody > tr:nth-child(2) > td:nth-child(3) > div.multiple_date > div:nth-child(2) > div > div > div > div > input', Carbon::today()->addDays(7)->format('m/d/Y'))

//                Add row
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > table > tbody > tr:nth-child(1) > td:nth-child(4) > a')

                ->type('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > table > tbody > tr:nth-child(3) > td:nth-child(1) > div > input',$this->faker->name)

                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > table > tbody > tr:nth-child(3) > td:nth-child(2) > div > div')
                ->scrollIntoView('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > table > tbody > tr:nth-child(3) > td:nth-child(2) > div > div > ul > li:nth-child(2)')
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > table > tbody > tr:nth-child(3) > td:nth-child(2) > div > div > ul > li:nth-child(2)')

                ->type('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > table > tbody > tr:nth-child(3) > td:nth-child(3) > div.multiple_date > div:nth-child(1) > div > div > div > div > input', Carbon::today()->addDays(9)->format('m/d/Y'))
                ->type('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > table > tbody > tr:nth-child(3) > td:nth-child(3) > div.multiple_date > div:nth-child(2) > div > div > div > div > input', Carbon::today()->addDays(10)->format('m/d/Y'))
                ->pause(2000)
                ->scrollIntoView('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > div.row.justify-content-center.mt-2 > button')
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > div.row.justify-content-center.mt-2 > button')
                ->waitFor('.toast-message')
                ->assertSee('Holiday Settings Saved Successfully')
            ->assertSee(Carbon::today()->addDays(10)->format('Y-m-d'));
        });
    }

    public function testYearDeleteWithHoliday()
    {
        $this->testAddMultipleDayMultipleHoliday();
        $this->browse(function (Browser $browser){
            $browser
                ->visit('/leave/holidays')
                ->pause(1000)
                ->click('#dropdownMenu2')
                ->pause(1000)
                ->click('#DataTables_Table_1 > tbody > tr > td:nth-child(3) > div > div > a:nth-child(3)')
                ->waitFor('#confirm-delete', 5)
                ->whenAvailable('#confirm-delete', function ($modal){
                    $modal
                        ->click('#delete_link');
                })
                ->waitFor('.toast-message')
                ->assertSee('Year Deleted Successfully');
        });
    }

    public function testYearDeleteWithOutHoliday()
    {
        $this->testCreateYear();
        $this->browse(function (Browser $browser){
            $browser
                ->visit('/leave/holidays')
                ->pause(1000)
                ->click('#dropdownMenu2')
                ->pause(1000)
                ->click('#DataTables_Table_1 > tbody > tr > td:nth-child(3) > div > div > a:nth-child(3)')
                ->waitFor('#confirm-delete', 5)
                ->whenAvailable('#confirm-delete', function ($modal){
                    $modal
                        ->click('#delete_link');
                })
                ->waitFor('.toast-message')
                ->assertSee('Year Deleted Successfully');
        });
    }

    public function testHolidayCopyFrom(){

        $this->testAddMultipleDayMultipleHoliday();

        $this->browse(function(Browser $browser){
           $browser->visit('/leave/holidays')
               ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-4.holiday_setup > h3 > a')
               ->waitFor('#year_add', 5)
               ->whenAvailable('#year_add', function ($modal){
                   $modal
                       ->type('year', date('Y') + 1)
                       ->pause(1000)
                       ->click('#save_year');
               })
               ->waitFor('.toast-message')
               ->assertSee('Year Created Successfully')
               ->pause(1000)
               ->visit('/leave/holidays')
               ->click('#dropdownMenu2')
               ->pause(1000)
               ->click('#DataTables_Table_1 > tbody > tr:nth-child(1) > td:nth-child(3) > div > div > a:nth-child(2)')
               ->waitForText('HOLIDAY COPY FROM')
               ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > div > div > div > div')
               ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > div > div > div > div > ul > li:nth-child(2)')
               ->pause(2000)
               ->scrollIntoView('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > div.row.justify-content-center.mt-2 > button')
               ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-8.mt-30 > div > form > div.row.justify-content-center.mt-2 > button')
               ->waitFor('.toast-message')
               ->assertSee('Holiday Settings Saved Successfully');

        });
    }

}
