<?php

namespace Tests\Browser\Modules\Leave;

use App\User;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\WithFaker;
use Laravel\Dusk\Browser;
use Modules\Leave\Entities\LeaveDefine;
use Modules\Leave\Entities\LeaveType;
use Tests\DuskTestCase;

class LeaveDefineTest extends DuskTestCase
{
    use withFaker;

    protected $leaveTypes = [];
    protected $users = [];

    public function setUp(): void
    {
        parent::setUp();
        for ($i = 0; $i < 3; $i++) {
            $this->leaveTypes[] = LeaveType::create([
                'name' => $this->faker->name
            ]);
        }

        for ($i = 0; $i < 10; $i++) {
            $this->users[] = User::create([
                'email' => $this->faker->email,
                'name' => $this->faker->name,
                'role_id' => rand(2, 3)
            ]);
        }


    }

    public function tearDown(): void
    {
        $leaveDefines = LeaveDefine::get();

        foreach ($leaveDefines as $define) {
            $define->delete();
        }

        foreach ($this->users as $user) {
            $user->delete();
        }

        foreach ($this->leaveTypes as $leaveType) {
            $leaveType->delete();
        }

        parent::tearDown(); // TODO: Change the autogenerated stub
    }


    public function testLeaveDefineForAdmin()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/leave/define-lists')
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > button')
                ->waitFor('#leave_define_add', 5)
                ->whenAvailable('#leave_define_add', function ($modal) {
                    $modal
                        ->click('#leave_define_create_form > div > div.col-xl-12.role_id > div > div')
                        ->click('#leave_define_create_form > div > div.col-xl-12.role_id > div > div > ul > li:nth-child(2)')
                        ->pause(3000)
                        ->click('#leave_define_create_form > div > div:nth-child(4) > div > div')
                        ->click('#leave_define_create_form > div > div:nth-child(4) > div > div > ul > li:nth-child(2)')
                        ->type('total_days', 10)
                        ->click('#leave_define_create_form_button');
                })
                ->waitFor('.toast-message')
                ->assertSee('Leave Defined Successfully');
        });

    }

    public function testLeaveDefineForUsers()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/leave/define-lists')
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > button')
                ->waitFor('#leave_define_add', 5)
                ->whenAvailable('#leave_define_add', function ($modal) {
                    $modal
                        ->click('#leave_define_create_form > div > div.col-xl-12.role_id > div > div')
                        ->click('#leave_define_create_form > div > div.col-xl-12.role_id > div > div > ul > li:nth-child(2)')
                        ->pause(3000)
                        ->click('#leave_define_create_form > div > div.col-lg-12.user_id > div > div')
                        ->click('#leave_define_create_form > div > div.col-lg-12.user_id > div > div > ul > li:nth-child(2)')
                        ->click('#leave_define_create_form > div > div:nth-child(4) > div > div')
                        ->click('#leave_define_create_form > div > div:nth-child(4) > div > div > ul > li:nth-child(2)')
                        ->type('total_days', 10)
                        ->click('#leave_define_create_form_button');
                })
                ->waitFor('.toast-message')
                ->assertSee('Leave Defined Successfully');
        });

    }

    public function testLeaveDefineForUsersWithBalanceForward()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/leave/define-lists')
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > button')
                ->waitFor('#leave_define_add', 5)
                ->whenAvailable('#leave_define_add', function ($modal) {
                    $modal
                        ->click('#leave_define_create_form > div > div.col-xl-12.role_id > div > div')
                        ->click('#leave_define_create_form > div > div.col-xl-12.role_id > div > div > ul > li:nth-child(2)')
                        ->pause(3000)
                        ->click('#leave_define_create_form > div > div.col-lg-12.user_id > div > div')
                        ->click('#leave_define_create_form > div > div.col-lg-12.user_id > div > div > ul > li:nth-child(2)')
                        ->click('#leave_define_create_form > div > div:nth-child(4) > div > div')
                        ->click('#leave_define_create_form > div > div:nth-child(4) > div > div > ul > li:nth-child(2)')
                        ->type('total_days', 10)
                        ->click('#balance_forward_checkbox > li > label > span')
                        ->type('max_forward', 10)
                        ->click('#leave_define_create_form_button');
                })
                ->waitFor('.toast-message')
                ->assertSee('Leave Defined Successfully');
        });

    }

    public function testLeaveDefineForUsersWithAdjustment()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/leave/define-lists')
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > button')
                ->waitFor('#leave_define_add', 5)
                ->whenAvailable('#leave_define_add', function ($modal) {
                    $modal
                        ->click('#leave_define_create_form > div > div.col-xl-12.role_id > div > div')
                        ->click('#leave_define_create_form > div > div.col-xl-12.role_id > div > div > ul > li:nth-child(2)')
                        ->pause(3000)
                        ->click('#leave_define_create_form > div > div.col-lg-12.user_id > div > div')
                        ->click('#leave_define_create_form > div > div.col-lg-12.user_id > div > div > ul > li:nth-child(2)')
                        ->click('#leave_define_create_form > div > div:nth-child(4) > div > div')
                        ->click('#leave_define_create_form > div > div:nth-child(4) > div > div > ul > li:nth-child(2)')
                        ->type('total_days', 10)
                        ->click('#adjust_checkbox > li > label > span')
                        ->click('#leave_define_create_form_button');
                })
                ->waitFor('.toast-message')
                ->assertSee('Leave Defined Successfully');
        });

    }

    public function testLeaveDefineForUsersWithOnlyThisYear()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/leave/define-lists')
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > button')
                ->waitFor('#leave_define_add', 5)
                ->whenAvailable('#leave_define_add', function ($modal) {
                    $modal
                        ->click('#leave_define_create_form > div > div.col-xl-12.role_id > div > div')
                        ->click('#leave_define_create_form > div > div.col-xl-12.role_id > div > div > ul > li:nth-child(2)')
                        ->pause(3000)
                        ->click('#leave_define_create_form > div > div.col-lg-12.user_id > div > div')
                        ->click('#leave_define_create_form > div > div.col-lg-12.user_id > div > div > ul > li:nth-child(2)')
                        ->click('#leave_define_create_form > div > div:nth-child(4) > div > div')
                        ->click('#leave_define_create_form > div > div:nth-child(4) > div > div > ul > li:nth-child(2)')
                        ->type('total_days', 10)
                        ->click('#only_this_year_checkbox > li > label > span')
                        ->click('#leave_define_create_form_button');
                })
                ->waitFor('.toast-message')
                ->assertSee('Leave Defined Successfully');
        });

    }


    public function testLeaveDefineWithAllField()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/leave/define-lists')
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > button')
                ->waitFor('#leave_define_add', 5)
                ->whenAvailable('#leave_define_add', function ($modal) {
                    $modal
                        ->click('#leave_define_create_form > div > div.col-xl-12.role_id > div > div')
                        ->click('#leave_define_create_form > div > div.col-xl-12.role_id > div > div > ul > li:nth-child(2)')
                        ->pause(3000)
                        ->click('#leave_define_create_form > div > div.col-lg-12.user_id > div > div')
                        ->click('#leave_define_create_form > div > div.col-lg-12.user_id > div > div > ul > li:nth-child(2)')
                        ->click('#leave_define_create_form > div > div:nth-child(4) > div > div')
                        ->click('#leave_define_create_form > div > div:nth-child(4) > div > div > ul > li:nth-child(2)')
                        ->type('total_days', 10)
                        ->click('#balance_forward_checkbox > li > label > span')
                        ->type('max_forward', 10)
                        ->click('#adjust_checkbox > li > label > span')
                        ->click('#only_this_year_checkbox > li > label > span')
                        ->click('#leave_define_create_form_button');
                })
                ->waitFor('.toast-message')
                ->assertSee('Leave Defined Successfully');
        });

    }

    public function testDuplicateLeaveDefineWithOutUser()
    {
        $this->testLeaveDefineForAdmin();
        $this->browse(function (Browser $browser) {
            $browser
                ->visit('/leave/define-lists')
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > button')
                ->waitFor('#leave_define_add', 5)
                ->whenAvailable('#leave_define_add', function ($modal) {
                    $modal
                        ->click('#leave_define_create_form > div > div.col-xl-12.role_id > div > div')
                        ->click('#leave_define_create_form > div > div.col-xl-12.role_id > div > div > ul > li:nth-child(2)')
                        ->pause(3000)
                        ->click('#leave_define_create_form > div > div:nth-child(4) > div > div')
                        ->click('#leave_define_create_form > div > div:nth-child(4) > div > div > ul > li:nth-child(2)')
                        ->type('total_days', 10)
                        ->click('#leave_define_create_form_button');
                })
                ->waitFor('.toast-message')
                ->assertSee('Leave Type For this role already defined');
        });

    }

    public function testDuplicateLeaveDefineWith()
    {
        $this->testLeaveDefineWithAllField();
        $this->browse(function (Browser $browser) {
            $browser
                ->visit('/leave/define-lists')
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > button')
                ->waitFor('#leave_define_add', 5)
                ->whenAvailable('#leave_define_add', function ($modal) {
                    $modal
                        ->click('#leave_define_create_form > div > div.col-xl-12.role_id > div > div')
                        ->click('#leave_define_create_form > div > div.col-xl-12.role_id > div > div > ul > li:nth-child(2)')
                        ->pause(3000)
                        ->click('#leave_define_create_form > div > div.col-lg-12.user_id > div > div')
                        ->click('#leave_define_create_form > div > div.col-lg-12.user_id > div > div > ul > li:nth-child(2)')
                        ->click('#leave_define_create_form > div > div:nth-child(4) > div > div')
                        ->click('#leave_define_create_form > div > div:nth-child(4) > div > div > ul > li:nth-child(2)')
                        ->type('total_days', 10)
                        ->click('#balance_forward_checkbox > li > label > span')
                        ->type('max_forward', 10)
                        ->click('#adjust_checkbox > li > label > span')
                        ->click('#only_this_year_checkbox > li > label > span')
                        ->click('#leave_define_create_form_button');
                })
                ->waitFor('.toast-message')
                ->assertSee('Leave Type For this role already defined');
        });

    }

    public function testLeaveDefineForStaffs()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/leave/define-lists')
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > button')
                ->waitFor('#leave_define_add', 5)
                ->whenAvailable('#leave_define_add', function ($modal) {
                    $modal
                        ->click('#leave_define_create_form > div > div.col-xl-12.role_id > div > div')
                        ->click('#leave_define_create_form > div > div.col-xl-12.role_id > div > div > ul > li:nth-child(3)')
                        ->click('#leave_define_create_form > div > div:nth-child(4) > div > div')
                        ->click('#leave_define_create_form > div > div:nth-child(4) > div > div > ul > li:nth-child(2)')
                        ->type('total_days', 10)
                        ->click('#leave_define_create_form_button');
                })
                ->waitFor('.toast-message')
                ->assertSee('Leave Defined Successfully');
        });

    }

    public function testLeaveDefineForAdminWithBalanceForward()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/leave/define-lists')
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > button')
                ->waitFor('#leave_define_add', 5)
                ->whenAvailable('#leave_define_add', function ($modal) {
                    $modal
                        ->click('#leave_define_create_form > div > div.col-xl-12.role_id > div > div')
                        ->click('#leave_define_create_form > div > div.col-xl-12.role_id > div > div > ul > li:nth-child(2)')
                        ->click('#leave_define_create_form > div > div:nth-child(4) > div > div')
                        ->click('#leave_define_create_form > div > div:nth-child(4) > div > div > ul > li:nth-child(3)')
                        ->type('total_days', 10)
                        ->click('#balance_forward_checkbox > li > label > span')
                        ->type('max_forward', 10)
                        ->click('#leave_define_create_form_button');
                })
                ->waitFor('.toast-message')
                ->assertSee('Leave Defined Successfully');
        });

    }

    public function testLeaveDefineForStaffWithBalanceForward()
    {

        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/leave/define-lists')
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > button')
                ->waitFor('#leave_define_add', 5)
                ->whenAvailable('#leave_define_add', function ($modal) {
                    $modal
                        ->click('#leave_define_create_form > div > div.col-xl-12.role_id > div > div')
                        ->click('#leave_define_create_form > div > div.col-xl-12.role_id > div > div > ul > li:nth-child(3)')
                        ->click('#leave_define_create_form > div > div:nth-child(4) > div > div')
                        ->click('#leave_define_create_form > div > div:nth-child(4) > div > div > ul > li:nth-child(3)')
                        ->type('total_days', 10)
                        ->click('#balance_forward_checkbox > li > label > span')
                        ->type('max_forward', 10)
                        ->click('#leave_define_create_form_button');
                })
                ->waitFor('.toast-message')
                ->assertSee('Leave Defined Successfully');
        });

    }


    public function testLeaveDefineForAdminAdjustWithPreviousLeave()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/leave/define-lists')
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > button')
                ->waitFor('#leave_define_add', 5)
                ->whenAvailable('#leave_define_add', function ($modal) {
                    $modal
                        ->click('#leave_define_create_form > div > div.col-xl-12.role_id > div > div')
                        ->click('#leave_define_create_form > div > div.col-xl-12.role_id > div > div > ul > li:nth-child(2)')
                        ->click('#leave_define_create_form > div > div:nth-child(4) > div > div')
                        ->click('#leave_define_create_form > div > div:nth-child(4) > div > div > ul > li:nth-child(4)')
                        ->type('total_days', 10)
                        ->click('#adjust_checkbox > li > label > span')
                        ->click('#leave_define_create_form_button');
                })
                ->waitFor('.toast-message')
                ->assertSee('Leave Defined Successfully');
        });

    }


    public function testLeaveDefineForStaffAdjustWithPreviousLeave()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/leave/define-lists')
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > button')
                ->waitFor('#leave_define_add', 5)
                ->whenAvailable('#leave_define_add', function ($modal) {
                    $modal
                        ->click('#leave_define_create_form > div > div.col-xl-12.role_id > div > div')
                        ->click('#leave_define_create_form > div > div.col-xl-12.role_id > div > div > ul > li:nth-child(3)')
                        ->click('#leave_define_create_form > div > div:nth-child(4) > div > div')
                        ->click('#leave_define_create_form > div > div:nth-child(4) > div > div > ul > li:nth-child(4)')
                        ->type('total_days', 10)
                        ->click('#adjust_checkbox > li > label > span')
                        ->click('#leave_define_create_form_button');
                })
                ->waitFor('.toast-message')
                ->assertSee('Leave Defined Successfully');
        });

    }


    public function testLeaveDefineEdit()
    {
        $this->testLeaveDefineWithAllField();
        $this->browse(function (Browser $browser) {
            $browser
                ->visit('/leave/define-lists')
                ->click('#dropdownMenu2')
                ->pause(1000)
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(7) > div > div > a:nth-child(1)')
                ->waitFor('#leave_define_add', 5)
                ->whenAvailable('#leave_define_add', function ($modal) {
                    $modal
                        ->type('total_days', 11)
                        ->click('#leave_define_create_form_button');
                })->waitFor('.toast-message')
                ->assertSee('Leave Define Updated Successfully');
        });
    }

    public function testLeaveDefineDelete()
    {
        $this->testLeaveDefineWithAllField();
        $this->browse(function (Browser $browser) {
            $browser
                ->visit('/leave/define-lists')
                ->click('#dropdownMenu2')
                ->pause(1000)
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(7) > div > div > a:nth-child(2)')
                ->waitFor('#deleteItemModal', 5)
                ->whenAvailable('#deleteItemModal', function ($modal) {
                    $modal
                        ->click('#item_delete_form > button');
                })->waitFor('.toast-message')
                ->assertSee('Leave Define Deleted Successfully');
        });
    }
}
