<?php

namespace Tests\Browser\Modules\Leave;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\WithFaker;
use Laravel\Dusk\Browser;
use Modules\Leave\Entities\LeaveType;
use Tests\DuskTestCase;

class LeaveTypeTest extends DuskTestCase
{
    use withFaker;

    public function tearDown(): void
    {
        $leaveTypes = LeaveType::all();

        foreach ($leaveTypes as $leaveType) {
            $leaveType->delete();
        }

        parent::tearDown(); // TODO: Change the autogenerated stub
    }


    public function testCreateActiveLeaveType()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/leave/types')
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > button')
                ->waitFor('#item_add', 5)
                ->whenAvailable('#item_add', function ($modal) {
                    $modal
                        ->type('name',$this->faker->name)
                        ->click('#item_create_form > div > div.col-lg-12.text-center > div > button');
                })
                ->waitFor('.toast-message')
                ->assertSee('Leave Type Added Successfully')
            ;
        });
    }

    public function testCreateInActiveLeaveType()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('/leave/types')
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > button')
                ->waitFor('#item_add', 5)
                ->whenAvailable('#item_add', function ($modal) {
                    $modal
                        ->type('name',$this->faker->name)
                        ->click('#theme_nav > li:nth-child(2) > label > span')
                        ->click('#item_create_form > div > div.col-lg-12.text-center > div > button');
                })
                ->waitFor('.toast-message')
                ->assertSee('Leave Type Added Successfully')
                ->pause(3000)
                ->assertSee('DeActive')
            ;
        });
    }

    public function testEditActiveLeaveType()
    {
        $this->testCreateActiveLeaveType();
        $this->browse(function (Browser $browser) {
            $browser
                ->visit('/leave/types')
                ->click('#dropdownMenu2')
                ->pause(1000)
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(4) > div > div > a:nth-child(1)')
                ->waitFor('#item_add', 5)
                ->whenAvailable('#item_add', function ($modal) {
                    $modal
                        ->type('name', $this->faker->name)
                        ->click('#item_create_form > div > div.col-lg-12.text-center > div > button');
                })->waitFor('.toast-message')
                ->assertSee('Leave Type updated Successfully')
            ;
        });
    }

    public function testEditInActiveLeaveType()
    {
        $this->testCreateInActiveLeaveType();
        $this->browse(function (Browser $browser) {
            $browser
                ->visit('/leave/types')
                ->click('#dropdownMenu2')
                ->pause(1000)
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(4) > div > div > a:nth-child(1)')
                ->waitFor('#item_add', 5)
                ->whenAvailable('#item_add', function ($modal) {
                    $modal
                        ->type('name', $this->faker->name)
                        ->click('#item_create_form > div > div.col-lg-12.text-center > div > button');
                })->waitFor('.toast-message')
                ->assertSee('Leave Type updated Successfully')
                ->pause(3000)
                ->assertSee('DeActive')
            ;
        });
    }

    public function testEditInActiveLeaveTypeToActiveLeaveType()
    {
        $this->testCreateInActiveLeaveType();
        $this->browse(function (Browser $browser) {
            $browser
                ->visit('/leave/types')
                ->click('#dropdownMenu2')
                ->pause(1000)
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(4) > div > div > a:nth-child(1)')
                ->waitFor('#item_add', 5)
                ->whenAvailable('#item_add', function ($modal) {
                    $modal
                        ->type('name', $this->faker->name)
                        ->click('#theme_nav > li:nth-child(1) > label > span')
                        ->click('#item_create_form > div > div.col-lg-12.text-center > div > button');
                })->waitFor('.toast-message')
                ->assertSee('Leave Type updated Successfully')
                ->pause(3000)
                ->assertSee('Active')
            ;
        });
    }

    public function testLeaveTypeDelete()
    {
        $this->testCreateInActiveLeaveType();
        $this->browse(function (Browser $browser) {
            $browser
                ->visit('/leave/types')
                ->click('#dropdownMenu2')
                ->pause(1000)
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(4) > div > div > a:nth-child(2)')
                ->waitFor('#deleteItemModal', 5)
                ->whenAvailable('#deleteItemModal', function ($modal) {
                    $modal
                        ->click('#item_delete_form > button');
                })->waitFor('.toast-message')
                ->assertSee('Leave Type Deleted Successfully')
            ;
        });
    }
}
