<?php


namespace Tests\Browser\Modules\HumanResource;


use App\User;
use Illuminate\Foundation\Testing\WithFaker;
use Laravel\Dusk\Browser;
use Tests\DuskTestCase;

class AttendanceTest extends DuskTestCase {

    use WithFaker;
    protected $users = [];

    public function setUp(): void
    {
        parent::setUp();

        for ($i = 0; $i < 10; $i++) {
            $this->users[] = User::create([
                'email' => $this->faker->email,
                'name' => $this->faker->name,
                'role_id' => rand(2, 3)
            ]);
        }

    }

    public function tearDown(): void
    {
        foreach ($this->users as $user) {
            $user->delete();
        }

        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testVisitPageWithOutAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser
                ->visit('/attendance/hr/attendance')
                ->assertPathIs('/login')
                ->visit('/attendance/hr/attendance/report-index')
                ->assertPathIs('/login');
        });
    }

    public function testVisitPageWithAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser
                ->loginAs(1)
                ->visit('session-data')
                ->visit('/attendance/hr/attendance')
                ->assertSee('Attendance')
                ->visit('/attendance/hr/attendance/report-index')
                ->assertSee('Attendance Report');
        });
    }

    public function testVisitAttendacePageWithAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser
                ->loginAs(1)
                ->visit('session-data')
                ->visit('/attendance/hr/attendance')
                ->assertSee('Attendance');
        });
    }

    public function testAttendance(){
        $this->testVisitAttendacePageWithAuth();
        $this->browse(function (Browser $browser){
            $browser
                ->click('#main-content > section > div > div > div.col-lg-12 > div > div:nth-child(1) > div.col-lg-6 > div > div')
                ->click('#main-content > section > div > div > div.col-lg-12 > div > div:nth-child(1) > div.col-lg-6 > div > div > ul > li:nth-child(2)')
                ->click('#get_attendance')
                ->pause(5000)
                ->click('#main-content > div.create_form > form > div.common_QA_section.QA_section_heading_custom.th_padding_l0 > div > div > table > tbody > tr:nth-child(2) > td:nth-child(3) > div > div:nth-child(1) > label')
                ->click('#save_button_parent')
                ->waitFor('.toast-message')
                ->assertSee('Attendance has been taken')
                ->visit('/attendance/hr/attendance/report-index')
                ->assertSee('Attendance Report')
                ->click('#main-content > section > div > div > div.col-lg-12.mb-3 > div > form > div:nth-child(1) > div:nth-child(1) > div > div')
                ->click('#main-content > section > div > div > div.col-lg-12.mb-3 > div > form > div:nth-child(1) > div:nth-child(1) > div > div > ul > li:nth-child(2)')
                ->click('#save_button_parent')
                ->assertSee('Attendance Report')

            ;
        });
    }

}
