<?php


namespace Tests\Browser\Modules\HumanResource;


use Illuminate\Foundation\Testing\WithFaker;
use Laravel\Dusk\Browser;
use Modules\Setup\Entities\Department;
use Tests\DuskTestCase;

class DepartmentTest extends DuskTestCase
{
    use withFaker;

    public function setUp(): void
    {
        parent::setUp();
    }

    public function tearDown(): void
    {
        $departments = Department::where('id', '>', 3)->get();
        foreach ($departments as $department) {
            $department->delete();
        }
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testVisitPageWithOutAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser
                ->visit('/hr/departments')
                ->assertPathIs('/login');
        });
    }

    public function testVisitPageWithAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser
                ->loginAs(1)
                ->visit('session-data')
                ->visit('/hr/departments')
                ->assertSee('Department List');
        });
    }

    public function testCreateDepartmentWithRequiredField()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > button')
                ->whenAvailable('#item_add', function ($modal) {
                    $modal->type('name', $this->faker->name)
                        ->click('#item_create_form > div > div.col-lg-12.text-center > div > button');
                })->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Department has been created successfully!');
        });
    }

    public function testEditDepartmentWithRequiredField()
    {
        $this->testCreateDepartmentWithRequiredField();
        $this->browse(function (Browser $browser) {
            $browser->visit('/hr/departments')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(5) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(5) > div > div > a:nth-child(1)')
                ->whenAvailable('#item_edit', function ($modal) {
                    $modal->pause(3000)
                        ->type('name', $this->faker->name)
                        ->click('#item_edit_form > div > div.col-lg-12.text-center > div > button');
                })
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Department has been updated successfully!');
        });
    }

    public function testCreateDepartmentWithAllField()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > button')
                ->whenAvailable('#item_add', function ($modal) {
                    $modal->type('name', $this->faker->name)
                        ->type('details', $this->faker->paragraph)
                        ->click('#item_create_form > div > div.col-lg-12.text-center > div > button');
                })->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Department has been created successfully!');
        });
    }

    public function testEditDepartmentWithAllField()
    {
        $this->testCreateDepartmentWithAllField();
        $this->browse(function (Browser $browser) {
            $browser->visit('/hr/departments')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(5) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(5) > div > div > a:nth-child(1)')
                ->whenAvailable('#item_edit', function ($modal) {
                    $modal->pause(3000)
                        ->type('name', $this->faker->name)
                        ->type('details', $this->faker->paragraph)
                        ->click('#item_edit_form > div > div.col-lg-12.text-center > div > button');
                })
                ->waitFor('.toast-message')
                ->assertSeeIn('.toast-message', 'Department has been updated successfully!');
        });
    }

    public function testCreateDepartmentWithAllFieldStatusDeActive()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser->click('#main-content > section > div.container-fluid.p-0 > div > div.col-12 > div > div > ul > li > button')
                ->whenAvailable('#item_add', function ($modal) {
                    $modal->type('name', $this->faker->name)
                        ->type('details', $this->faker->paragraph)
                        ->click('#theme_nav > li:nth-child(2) > label > span')
                        ->click('#item_create_form > div > div.col-lg-12.text-center > div > button');
                })->waitFor('.toast-message')
                ->with('.table', function ($table){
                    $table->waitFor('.badge_4')
                        ->assertSee('DeActive');
                })
                ->assertSeeIn('.toast-message', 'Department has been created successfully!');
        });
    }

    public function testEditDepartmentWithAllFieldsChangeStatusDeActiveToActive()
    {
        $this->testCreateDepartmentWithAllFieldStatusDeActive();
        $this->browse(function (Browser $browser){
            $browser->visit('/hr/departments')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(5) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(5) > div > div > a:nth-child(1)')
                ->whenAvailable('#item_edit', function ($modal) {
                    $modal->pause(3000)
                        ->type('name', $this->faker->name)
                        ->type('details', $this->faker->paragraph)
                        ->click('#theme_nav > li:nth-child(1) > label > span')
                        ->click('#item_edit_form > div > div.col-lg-12.text-center > div > button');
                })
                ->waitFor('.toast-message')
                ->with('.table', function ($table){
                    $table->waitFor('.badge_1')
                        ->assertSee('Active');
                })
                ->assertSeeIn('.toast-message', 'Department has been updated successfully!');
        });

    }

    public function testDeleteDepartment (){
        $this->testCreateDepartmentWithAllField();
        $this->browse(function(Browser $browser){
            $browser->visit('/hr/departments')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(5) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(5) > div > div > a:nth-child(2)')
                ->whenAvailable('#deleteItemModal', function ($modal) {
                    $modal->click('#item_delete_form > button');
                })->waitFor('.toast-message')
                ->assertSee('Department has been deleted successfully!');

        });
    }

}
