<?php


namespace Tests\Browser\Modules\HumanResource;


use Laravel\Dusk\Browser;
use Tests\Browser\Traits\PurchaseTrait;
use Tests\DuskTestCase;

class LoanTest extends DuskTestCase
{
    use PurchaseTrait;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->createStaff();

    }

    public function tearDown(): void
    {
        $this->deleteStaff();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testVisitPageWithOutAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser
                ->visit('/hr/apply-loans')
                ->assertPathIs('/login')
                ->visit('/hr/apply-loans/history')
                ->assertPathIs('/login')
                ->visit('/hr/loan-approval')
                ->assertPathIs('/login');
        });
    }

    public function testVisitPageWithAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser
                ->loginAs(1)
                ->visit('session-data')
                ->visit('/hr/apply-loans')
                ->assertSee('Loan Apply')
                ->visit('/hr/apply-loans/history')
                ->assertSee('Loan History')
                ->visit('/hr/loan-approval')
                ->assertSee('Loan Approval');
        });
    }

    public function visitApplyLoanPageWithAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser
                ->loginAs(1)
                ->visit('session-data')
                ->visit('/hr/apply-loans')
                ->assertSee('Loan Apply')
               ;
        });
    }

    public function testApplyLoan(){
        $this->visitApplyLoanPageWithAuth();
        $this->browse(function (Browser $browser){
            $browser->click('#main-content > section > div > div > div.col-12 > div > div > ul > li > a')
                ->whenAvailable('#ApplyLoan', function ($modal){
                    $modal
                        ->click('#ApplyLoan_addForm > div:nth-child(1) > div > div > div')
                        ->click('#ApplyLoan_addForm > div:nth-child(1) > div > div > div > ul > li:nth-child(2)')
                        ->type('#ApplyLoan_addForm > div:nth-child(2) > div:nth-child(3) > div > input', $this->faker->jobTitle)
                        ->type('#loan_date', date('m/d/Y'))
                        ->type('#amount', 360000)
                        ->type('#total_month', 36)
                        ->type('#note', $this->faker->paragraph)
                        ->click('#save_button_parent');
                })
                ->assertSee('Loan Apply')
                ;
        });
    }

    public function testEditLoan(){
        $this->testApplyLoan();
        $this->browse(function (Browser $browser){
            $browser
                ->pause(5000)
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(8) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(8) > div > div > a:nth-child(2)')
                ->whenAvailable('#ApplyLoanEdit', function ($modal){
                    $modal
                        ->click('#ApplyLoan_addForm > div > div.col-lg-12.text-center > div > button');
                })
                ->waitFor('.toast-message')
                ->assertSee('Loan has been updated Successfully')
                ;
        });
    }

    public function testViewLoan(){
        $this->testApplyLoan();
        $this->browse(function (Browser $browser){
            $browser
                ->pause(5000)
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(8) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(8) > div > div > a:nth-child(1)')
                ->whenAvailable('#ApplyLoanview', function ($modal){
                    $modal->assertSee('Apply Loan Details');
                })
                ;
        });
    }

    public function testDeleteLoan(){
        $this->testApplyLoan();
        $this->browse(function (Browser $browser){
            $browser
                ->pause(5000)
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(8) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(8) > div > div > a.dropdown-item.edit_brand')
                ->whenAvailable('#confirm-delete', function ($modal){
                    $modal->click('#delete_link');
                })
                ->waitFor('.toast-message')
                ->assertSee('Applied Loan has been deleted Successfully')
                ;
        });
    }

    public function testApproveLoan(){
        $this->testApplyLoan();
        $this->browse(function (Browser $browser){
            $browser
                ->visit('hr/loan-approval')
                ->assertSee('Loan Approval')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(8) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(8) > div > div > a:nth-child(1)')
                ->whenAvailable('#ApplyLoanview', function ($modal){
                    $modal
                    ->assertSee('Apply Loan Details')
                        ->click('div > div > div.modal-body > div:nth-child(2) > div.col-xl-3 > div > div')
                        ->click('div > div > div.modal-body > div:nth-child(2) > div.col-xl-3 > div > div > ul > li:nth-child(2)')

                    ;
                })
                ->pause(5000)
                ->waitFor('.table')
                ->with('.table', function ($table){
                    $table->waitFor('.badge_1')
                        ->assertSee('Approved');
                })
                ;
        });
    }

    public function testCancelLoan(){
        $this->testApplyLoan();
        $this->browse(function (Browser $browser){
            $browser
                ->visit('hr/loan-approval')
                ->assertSee('Loan Approval')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(8) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(8) > div > div > a:nth-child(1)')
                ->whenAvailable('#ApplyLoanview', function ($modal){
                    $modal
                        ->assertSee('Apply Loan Details')
                        ->click('div > div > div.modal-body > div:nth-child(2) > div.col-xl-3 > div > div')
                        ->click('div > div > div.modal-body > div:nth-child(2) > div.col-xl-3 > div > div > ul > li:nth-child(2)')
                    ;
                })
                ->with('.table', function ($table){
                    $table->waitFor('.badge_4')
                        ->assertSee('Cancelled');
                })
            ;
        });
    }

}
