<?php


namespace Tests\Browser\Modules\HumanResource;


use Laravel\Dusk\Browser;
use Tests\Browser\Traits\PurchaseTrait;
use Tests\DuskTestCase;

class PayrollTest extends DuskTestCase
{
    use PurchaseTrait;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->createStaff();

    }

    public function tearDown(): void
    {
        $this->deleteStaff();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testVisitPageWithOutAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser
                ->visit('/hr/payroll')
                ->assertPathIs('/login')
                ->visit('/hr/payroll/reports')
                ->assertPathIs('/login');
        });
    }

    public function testVisitPageWithAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser
                ->loginAs(1)
                ->visit('session-data')
                ->visit('/hr/payroll')
                ->assertSee('Payroll')
                ->visit('/hr/payroll/reports')
                ->assertSee('Payroll Reports');
        });
    }

    public function testSearchUser()
    {
        $this->browse(function (Browser $browser) {
            $browser
                ->loginAs(1)
                ->visit('session-data')
                ->visit('/hr/payroll')
                ->assertSee('Payroll')
                ->click('#main-content > section > div > div > div:nth-child(2) > div > form > div:nth-child(1) > div:nth-child(1) > div > div')
                ->click('#main-content > section > div > div > div:nth-child(2) > div > form > div:nth-child(1) > div:nth-child(1) > div > div > ul > li:nth-child(2)')
                ->click('#save_button_parent');

        });
    }

    public function testGeneratePayroll()
    {
        $this->testSearchUser();
        $this->browse(function (Browser $browser){
           $browser->click('#DataTables_Table_0 > tbody > tr > td.sorting_1')
               ->click('#DataTables_Table_0 > tbody > tr.child > td > ul > li > span.dtr-data > a')
               ->assertSee('Generate Payroll')
               ->click('#main-content > form > section > div > div > div:nth-child(1) > div.d-flex.justify-content-between.mb-20 > div:nth-child(2) > button')
               ->pause(1000)
               ->click('#main-content > form > section > div > div > div:nth-child(1) > div.d-flex.justify-content-between.mb-20 > div:nth-child(2) > button')
               ->pause(1000)

               ->click('#main-content > form > section > div > div > div:nth-child(2) > div.d-flex.justify-content-between.mb-20 > div:nth-child(2) > button')
               ->pause(1000)
               ->click('#main-content > form > section > div > div > div:nth-child(2) > div.d-flex.justify-content-between.mb-20 > div:nth-child(2) > button')
               ->pause(1000)

//               Earnings
               ->type('#row0 > td.pr-30 > div > input', $this->faker->title)
               ->type('#row0 > td:nth-child(2) > div > input', 500)
               ->type('#row1 > td.pr-30 > div > input', $this->faker->title)
               ->type('#row1 > td:nth-child(2) > div > input', 500)
               ->type('#row2 > td.pr-30 > div > input', $this->faker->title)
               ->type('#row2 > td:nth-child(2) > div > input', 500)

//               Deduction
               ->type('#DeductionRow0 > td.pr-30 > div > input', $this->faker->title)
               ->type('#DeductionRow0 > td:nth-child(2) > div > input', 250)
               ->type('#DeductionRow1 > td.pr-30 > div > input', $this->faker->title)
               ->type('#DeductionRow1 > td:nth-child(2) > div > input', 250)
               ->type('#DeductionRow2 > td.pr-30 > div > input', $this->faker->title)
               ->type('#DeductionRow2 > td:nth-child(2) > div > input', 250)

               ->pause(1000)
               ->click('#main-content > form > section > div > div > div:nth-child(3) > div.d-flex.justify-content-between.mb-20 > div:nth-child(2) > button')
               ->pause(1000)
               ->click('#main-content > form > section > div > div > div:nth-child(3) > div.col-lg-12.mt-20.text-right > button')

               ->waitFor('.toast-message')
               ->assertSee('Operation successful');
        });

    }

    public function testProceedToPay(){
        $this->testGeneratePayroll();
        $this->testSearchUser();
        $this->browse(function (Browser $browser) {
            $browser
                ->click('#DataTables_Table_0 > tbody > tr > td.sorting_1')
                ->click('#DataTables_Table_0 > tbody > tr.child > td > ul > li > span.dtr-data > a:nth-child(1)')
                ->whenAvailable('#PaymentForm', function ($modal){
                    $modal->click('#division_editForm > div.col-lg-12.text-center > div > button');
                })
                ->waitFor('.toast-message')
                ->assertSee('Payment Has been done Successfully')
;
        });

    }

    public function testViewPaySlip(){
        $this->testProceedToPay();
        $this->testSearchUser();
        $this->browse(function (Browser $browser) {
            $browser
                ->click('#DataTables_Table_0 > tbody > tr > td.sorting_1')
                ->click('#DataTables_Table_0 > tbody > tr.child > td > ul > li > span.dtr-data > a')
                ->whenAvailable('#SlipForm', function ($modal){
                    $modal->assertSee('View Payslip Details');
                })
;
        });

    }

    public function testPayrollReport()
    {
        $this->testProceedToPay();
        $this->browse(function (Browser $browser) {
            $browser
                ->visit('/hr/payroll/reports')
                ->assertSee('Payroll Reports');
        });
    }

}
