<?php

namespace Tests\Browser\Modules\HumanResource;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\WithFaker;
use Laravel\Dusk\Browser;
use Modules\RolePermission\Entities\Role;
use Tests\DuskTestCase;

class RoleTest extends DuskTestCase
{
    use withFaker;

    public function setUp(): void
    {
        parent::setUp();
    }

    public function tearDown(): void
    {
        $roles = Role::where('id', '>', 5)->get();
        foreach ($roles as $role) {
            $role->delete();
        }
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testVisitPageWithOutAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser
                ->visit('/hr/role-permission/roles')
                ->assertPathIs('/login');
        });
    }

    public function testVisitPageWithAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser
                ->loginAs(1)
                ->visit('session-data')
                ->visit('/hr/role-permission/roles')
                ->assertSee('Role List');
        });
    }

    public function testRoleCreate()
    {
        $this->testVisitPageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser
                ->type('name',$this->faker->name)
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-3 > div > div > form > div > div > div.row.mt-40 > div > button')
                ->waitFor('.toast-message')
                ->assertSee('Role Create Successful');
        });
    }

    public function testRoleUpdate()
    {
        $this->testRoleCreate();
        $this->browse(function (Browser $browser) {
            $browser
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(4) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(4) > div > div > a:nth-child(1)')
                ->click('#main-content > section > div.container-fluid.p-0 > div > div.col-lg-3 > div > div > form > div > div > div.row.mt-40 > div > button')
                ->waitFor('.toast-message')
                ->assertSee('Role Update Successful');
        });
    }

    public function testRoleDelete()
    {
        $this->testRoleCreate();
        $this->browse(function (Browser $browser) {
            $browser
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(4) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(4) > div > div > a:nth-child(2)')
                ->whenAvailable('#confirm-delete', function ($modal) {
                    $modal->click('#delete_link');
                })
                ->waitFor('.toast-message')
                ->assertSee('Role Delete Successful');
        });
    }

    public function testAssignPermissions()
    {
        $this->testRoleCreate();
        $this->browse(function (Browser $browser) {
            $browser
                ->click('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(4) > a > button')
                ->assertSee('Assign Permission')
                ->click('#main-content > form > div > div.mesonary_role_header > div:nth-child(1) > div > div.permission_header.d-flex.align-items-center.justify-content-between > div:nth-child(1) > label')
               ->click('#main-content > form > div > div.row.mt-40 > div > button')
                ->waitFor('.toast-message')
                ->assertSee('Operation successful');
        });
    }
}
