<?php


namespace Tests\Browser\Modules\HumanResource;


use App\User;
use Illuminate\Support\Facades\File;
use Laravel\Dusk\Browser;
use Tests\Browser\Traits\PurchaseTrait;
use Tests\DuskTestCase;

class StaffTest extends DuskTestCase
{
    use PurchaseTrait;

    public function tearDown(): void
    {
        $users = User::where('id', '!=', 1)->get();
        foreach ($users as $user) {
            if (File::exists($user->avatar)) {
                File::delete($user->avatar);
            }
            $user->staff ? $user->staff->delete() : '';
            $user->delete();
        }
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testVisitPageWithOutAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser
                ->visit('/hr/staffs')
                ->assertPathIs('/login')
                ->visit('/hr/staffs/create')
                ->assertPathIs('/login');
        });
    }

    public function testVisitPageWithAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('session-data')
                ->visit('/hr/staffs')
                ->assertSee('Staff List')
                ->visit('/hr/staffs/create')
                ->assertSee('Add New Staff');
        });
    }

    public function visitCreatePageWithAuth()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit('session-data')
                ->visit('/hr/staffs/create')
                ->assertSee('Add New Staff');
        });
    }

    public function testCreateAdminRoleStaff()
    {
        $this->visitCreatePageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser
                ->click('#staff_addForm > div > div:nth-child(3) > div > div')
                ->click('#staff_addForm > div > div:nth-child(3) > div > div > ul > li:nth-child(2)')
                ->type('#staff_addForm > div > div:nth-child(4) > div > input', $this->faker->name)
                ->type('#staff_addForm > div > div:nth-child(5) > div > input', $this->faker->email)
                ->type('#staff_addForm > div > div:nth-child(7) > div > input', '12345678')
                ->type('#date_of_birth', '11/25/1992')
                ->type('#current_address', 'Rajshahi')
                ->type('#permanent_address', 'Rajshahi')
                ->type('#staff_addForm > div > div.col-lg-4.opening_balance_div > div > input', 5000)
                ->attach('#staff_addForm > div > div:nth-child(16) > div > div > button > input', public_path('img/profile.jpg'))
                ->type('#staff_addForm > div > div:nth-child(17) > div > div > div > div > div > input', date('m/d/Y'))
                ->type('bank_name', 'ECB')
                ->type('bank_branch_name', 'Mirpur-10')
                ->type('bank_account_name', 'John')
                ->type('bank_account_no', '585523285613')
                ->type('#basic_salary', 30000)
                ->click('#staff_addForm > div > div.col-xl-6.employee_type_div > div > div')
                ->click('#staff_addForm > div > div.col-xl-6.employee_type_div > div > div > ul > li:nth-child(4)')
                ->click('#save_button_parent')
                ->waitFor('.toast-message', 20)
                ->assertSee('Staff has been added Successfully');
        });
    }

    public function testCreateStaffRoleStaff()
    {
        $this->visitCreatePageWithAuth();
        $this->browse(function (Browser $browser) {
            $browser
                ->click('#staff_addForm > div > div:nth-child(3) > div > div')
                ->click('#staff_addForm > div > div:nth-child(3) > div > div > ul > li:nth-child(3)')
                ->type('#staff_addForm > div > div:nth-child(4) > div > input', $this->faker->name)
                ->type('#staff_addForm > div > div:nth-child(5) > div > input', $this->faker->email)
                ->type('#staff_addForm > div > div:nth-child(7) > div > input', '12345678')
                ->type('#date_of_birth', '11/25/1992')
                ->type('#current_address', 'Rajshahi')
                ->type('#permanent_address', 'Rajshahi')
                ->type('#staff_addForm > div > div.col-lg-4.opening_balance_div > div > input', 5000)
                ->attach('#staff_addForm > div > div:nth-child(16) > div > div > button > input', public_path('img/profile.jpg'))
                ->type('#staff_addForm > div > div:nth-child(17) > div > div > div > div > div > input', date('m/d/Y'))
                ->type('bank_name', 'ECB')
                ->type('bank_branch_name', 'Mirpur-10')
                ->type('bank_account_name', 'John')
                ->type('bank_account_no', '585523285613')
                ->type('#basic_salary', 30000)
                ->click('#staff_addForm > div > div.col-xl-6.employee_type_div > div > div')
                ->click('#staff_addForm > div > div.col-xl-6.employee_type_div > div > div > ul > li:nth-child(4)')
                ->click('#save_button_parent')
                ->waitFor('.toast-message', 20)
                ->assertSee('Staff has been added Successfully');
        });
    }

    public function testEditAdminRoleStaff()
    {
        $this->testCreateAdminRoleStaff();
        $this->browse(function (Browser $browser) {
            $browser
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(10) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(10) > div > div > a:nth-child(1)')
                ->assertSee('Edit Staff Info')
                ->click('#save_button_parent')
                ->waitFor('.toast-message')
                ->assertSee('Staff info has been updated Successfully');
        });

    }

    public function testDeleteAdminRoleStaff()
    {
        $this->testCreateAdminRoleStaff();
        $this->browse(function (Browser $browser) {
            $browser
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(10) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(10) > div > div > a:nth-child(3)')
                ->whenAvailable('#confirm-delete', function ($modal) {
                    $modal->click('#delete_link');
                })
                ->waitFor('.toast-message')
                ->assertSee('Staff has been deleted Successfully');
        });

    }

    public function testEditStaffRoleStaff()
    {
        $this->testCreateStaffRoleStaff();
        $this->browse(function (Browser $browser) {
            $browser
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(10) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(10) > div > div > a:nth-child(1)')
                ->assertSee('Edit Staff Info')
                ->click('#save_button_parent')
                ->waitFor('.toast-message')
                ->assertSee('Staff info has been updated Successfully');
        });

    }

    public function testDeleteStaffRoleStaff()
    {
        $this->testCreateStaffRoleStaff();
        $this->browse(function (Browser $browser) {
            $browser
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(10) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(10) > div > div > a:nth-child(3)')
                ->whenAvailable('#confirm-delete', function ($modal) {
                    $modal->click('#delete_link');
                })
                ->waitFor('.toast-message')
                ->assertSee('Staff has been deleted Successfully');
        });
    }

    public function testViewStaffRoleStaff()
    {
        $this->testCreateStaffRoleStaff();
        $this->browse(function (Browser $browser) {
            $browser
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(10) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(10) > div > div > a:nth-child(2)')
                ->assertSee('Staff Info');
        });

    }
    public function testViewAdminRoleStaff()
    {
        $this->testCreateAdminRoleStaff();
        $this->browse(function (Browser $browser) {
            $browser
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(10) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(10) > div > div > a:nth-child(2)')
                ->assertSee('Staff Info');
        });

    }

    public function testChangeStatusActiveToInActiveAdminRoleStaff()
    {
        $this->testCreateAdminRoleStaff();
        $this->browse(function (Browser $browser) {
            $browser
                ->pause(5000)
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(6) > label > div')
                ->waitFor('.toast-message', 5)
                ->assertSee('Status has been updated Successfully');
        });
    }

    public function testChangeStatusInActiveToActiveAdminRoleStaff()
    {
        $this->testChangeStatusActiveToInActiveAdminRoleStaff();
        $this->browse(function (Browser $browser) {
            $browser
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(6) > label > div')
                ->waitFor('.toast-message')
                ->assertSee('Status has been updated Successfully');
        });
    }

    public function testUploadDocumentAdminRoleStaff()
    {
        $this->testViewAdminRoleStaff();
        $this->browse(function (Browser $browser) {
            $browser
                ->click('#main-content > section > div > div > div.col-lg-9.staff-details > ul > li:nth-child(2) > a')
                ->pause(5000)
                ->click('#staffDocuments > div > div.text-right.mb-20 > button')
                ->whenAvailable('#add_document_madal', function ($modal){
                    $modal
                        ->type('div > div > div.modal-body > div > form > div > div.col-xl-12 > div > input', 'Document')
                        ->attach('div > div > div.modal-body > div > form > div > div:nth-child(3) > div > div > button > input', public_path('img/profile.jpg'))
                        ->click('div > div > div.modal-body > div > form > div > div.col-lg-12.text-center.mt-40 > div > button.primary-btn.fix-gr-bg');
                })
                ->waitFor('.toast-message')
                ->assertSee('Staff Document has been uploaded Successfully');
        });
    }

    public function testDeleteUploadDocumentAdminRoleStaff()
    {
        $this->testUploadDocumentAdminRoleStaff();
        $this->browse(function (Browser $browser) {
            $browser
                ->click('#main-content > section > div > div > div.col-lg-9.staff-details > ul > li:nth-child(2) > a')
                ->pause(5000)
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(2) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(2) > div > div > a:nth-child(2)')
                ->whenAvailable('#confirm-delete', function ($modal) {
                    $modal->click('#delete_link');
                })
                ->waitFor('.toast-message')
                ->assertSee('Staff Document has been deleted Successfully');
        });
    }
}
