<?php

namespace Tests\Browser\Modules\Purchase;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Laravel\Dusk\Browser;
use Tests\Browser\Traits\PurchaseTrait;
use Tests\DuskTestCase;

class PurchaseOrderTest extends DuskTestCase
{
    use PurchaseTrait;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
       $this->createProduct();
        $this->createSupplier();
    }

    public function tearDown(): void
    {
//        $this->clearTable();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testVisitPageWithoutLogin(){

        $this->browse(function (Browser $browser){
            $browser->visit('purchase/purchase_order')
                ->assertPathIs('/login')
                ->visit('purchase/purchase_order/create')
                ->assertPathIs('/login');
        });
    }

    public function testVisitPageWithLogin(){

        $this->browse(function (Browser $browser){
            $browser->loginAs(1)
                ->visit('purchase/purchase_order/create')
                ->assertSee('Add Purchase Order');
        });
    }

    public function testCreatePurchaseWithRequiredFieldWithDueWithVariantProduct(){

        $this->testVisitPageWithLogin();
        $this->browse(function (Browser $browser){
            $browser
                ->click('#addForm > div:nth-child(2) > div:nth-child(1) > div > div')
                ->click('#addForm > div:nth-child(2) > div:nth-child(1) > div > div > ul > li:nth-child(2)')
                ->click('#addForm > div:nth-child(2) > div:nth-child(2) > div > div')
                ->click('#addForm > div:nth-child(2) > div:nth-child(2) > div > div > ul > li.option:nth-child(2')

//                select Product
                ->click('#addForm > div:nth-child(2) > div.col-lg-8.col-md-8.col-sm-12 > div > div')
                ->click('#addForm > div:nth-child(2) > div.col-lg-8.col-md-8.col-sm-12 > div > div > ul > li:nth-child(2)') // Single product
                ->pause(2000)

                ->click('#addForm > div:nth-child(2) > div.col-lg-8.col-md-8.col-sm-12 > div > div')
                ->click('#addForm > div:nth-child(2) > div.col-lg-8.col-md-8.col-sm-12 > div > div > ul > li:nth-child(3)') // Variant product
                ->whenAvailable('#Item_Details', function($model){
                    $model->click('div > div > div.modal-body > form > div > div:nth-child(1)')
                        ->click('div > div > div.modal-header > button')
                    ;
                }, 20)
                ->pause(3000)

                ->click('#addForm > div:nth-child(2) > div.col-lg-8.col-md-8.col-sm-12 > div > div')
                ->click('#addForm > div:nth-child(2) > div.col-lg-8.col-md-8.col-sm-12 > div > div > ul > li:nth-child(3)') // Variant product
                ->whenAvailable('#Item_Details', function($model){
                    $model->click('div > div > div.modal-body > form > div > div:nth-child(2) > a')
                        ->click('div > div > div.modal-header > button')

                        ;
                },20)
                ->pause(3000)

                ->type('#addForm > div:nth-child(6) > div > div > div > div.note-editing-area > div.note-editable.card-block', $this->faker->paragraph)
                ->click('#add_product > section > div > div > div:nth-child(2) > div > div.row.mt-20.justify-content-center.text-center > button.primary-btn.mr-2.fix-gr-bg.submit_btn')
                ->waitFor('.toast-message', 20)
                ->assertSee('Purchase Added Successfully')
            ;
        });

    }

    public function testCreatePurchaseWithRequiredFieldWithDue(){

        $this->testVisitPageWithLogin();
        $this->browse(function (Browser $browser){
            $browser
                ->click('#addForm > div:nth-child(2) > div:nth-child(1) > div > div')
                ->click('#addForm > div:nth-child(2) > div:nth-child(1) > div > div > ul > li:nth-child(2)')
                ->click('#addForm > div:nth-child(2) > div:nth-child(2) > div > div')
                ->click('#addForm > div:nth-child(2) > div:nth-child(2) > div > div > ul > li.option:nth-child(2')

                ->pause(3000)

                //                select Product
                ->click('#addForm > div:nth-child(2) > div.col-lg-8.col-md-8.col-sm-12 > div > div')
                ->click('#addForm > div:nth-child(2) > div.col-lg-8.col-md-8.col-sm-12 > div > div > ul > li:nth-child(2)') // Single product
                ->pause(3000)

                ->type('#addForm > div:nth-child(6) > div > div > div > div.note-editing-area > div.note-editable.card-block', $this->faker->paragraph)
                ->click('#add_product > section > div > div > div:nth-child(2) > div > div.row.mt-20.justify-content-center.text-center > button.primary-btn.mr-2.fix-gr-bg.submit_btn')
                ->waitFor('.toast-message', 20)
                ->assertSee('Purchase Added Successfully')
            ;
        });

    }


    public function testAddPayment(){
        $this->testCreatePurchaseWithRequiredFieldWithDue();
        $this->browse(function (Browser $browser){
            $browser->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(9) > div > div > a:nth-child(1)')
                ->assertSee('Payment')
                ->click('#add_product > section > div > div > div:nth-child(2) > form > div > div.col-lg-12.text-center.pt_15 > div > div.payment_buttons > button.primary_color_btn.payment_btn.multiple-payment-button.green_btn')
                ->waitFor('.toast-message', 20)
                ->assertSee('Payment Successful');
        });
    }

    public function testPurchaseOrderDetails(){
        $this->testCreatePurchaseWithRequiredFieldWithDue();
        $this->browse(function (Browser $browser){
            $browser->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(9) > div > div > a:nth-child(2)')
                ->assertSee('A4 SIZE');
        });
    }

    public function testCreatePurchaseWithRequiredFieldWithCashPayment(){

        $this->testVisitPageWithLogin();
        $this->browse(function (Browser $browser){
            $browser
                ->click('#addForm > div:nth-child(2) > div:nth-child(1) > div > div')
                ->click('#addForm > div:nth-child(2) > div:nth-child(1) > div > div > ul > li:nth-child(2)')
                ->click('#addForm > div:nth-child(2) > div:nth-child(2) > div > div')
                ->click('#addForm > div:nth-child(2) > div:nth-child(2) > div > div > ul > li.option:nth-child(2')

//                select Product
                ->click('#addForm > div:nth-child(2) > div.col-lg-8.col-md-8.col-sm-12 > div > div')
                ->click('#addForm > div:nth-child(2) > div.col-lg-8.col-md-8.col-sm-12 > div > div > ul > li:nth-child(2)') // Single product
                ->pause(2000)


                ->type('#addForm > div:nth-child(2) > div.col-md-6.col-lg-6.col-sm-12.amount_div > div > input', 50)

                ->type('#addForm > div:nth-child(6) > div > div > div > div.note-editing-area > div.note-editable.card-block', $this->faker->paragraph)
                ->click('#add_product > section > div > div > div:nth-child(2) > div > div.row.mt-20.justify-content-center.text-center > button.primary-btn.mr-2.fix-gr-bg.submit_btn')
                ->waitFor('.toast-message', 20)
                ->assertSee('Purchase Added Successfully')
            ;
        });

    }

    public function testCreatePurchaseWithRequiredFieldOnlySingleProduct(){

        $this->testVisitPageWithLogin();
        $this->browse(function (Browser $browser){
            $browser
                ->click('#addForm > div:nth-child(2) > div:nth-child(1) > div > div')
                ->click('#addForm > div:nth-child(2) > div:nth-child(1) > div > div > ul > li:nth-child(2)')
                ->click('#addForm > div:nth-child(2) > div:nth-child(2) > div > div')
                ->click('#addForm > div:nth-child(2) > div:nth-child(2) > div > div > ul > li.option:nth-child(2')

//                select Product
                ->click('#addForm > div:nth-child(2) > div.col-lg-8.col-md-8.col-sm-12 > div > div')
                ->click('#addForm > div:nth-child(2) > div.col-lg-8.col-md-8.col-sm-12 > div > div > ul > li:nth-child(2)') // Single product
                ->pause(2000)
                ->type('#addForm > div:nth-child(6) > div > div > div > div.note-editing-area > div.note-editable.card-block', $this->faker->paragraph)
                ->click('#add_product > section > div > div > div:nth-child(2) > div > div.row.mt-20.justify-content-center.text-center > button.primary-btn.mr-2.fix-gr-bg.submit_btn')
                ->waitFor('.toast-message', 20)
                ->assertSee('Purchase Added Successfully')
            ;
        });

    }

    public function testAddPaymentToPartialInvoice()
    {
        $this->testCreatePurchaseWithRequiredFieldWithCashPayment();
        $this->browse(function (Browser $browser){
            $browser->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(9) > div > div > a:nth-child(1)')
                ->assertSee('Payment')
                ->click('#add_product > section > div > div > div:nth-child(2) > form > div > div.col-lg-12.text-center.pt_15 > div > div.payment_buttons > button.primary_color_btn.payment_btn.multiple-payment-button.green_btn')
                ->waitFor('.toast-message', 20)
                ->assertSee('Payment Successful');
        });

    }

    public function testAddPartialPaymentToPurchaseOrder(){
        $this->testCreatePurchaseWithRequiredFieldOnlySingleProduct();
        $this->browse(function (Browser $browser){
            $browser->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(9) > div > div > a:nth-child(1)')
                ->assertSee('Payment')
                ->type('#pos_payment_method > div:nth-child(1) > div:nth-child(1) > div > input', 50)
                ->click('#add_product > section > div > div > div:nth-child(2) > form > div > div.col-lg-12.text-center.pt_15 > div > div.payment_buttons > button.primary_color_btn.payment_btn.multiple-payment-button.green_btn')
                ->waitFor('.toast-message', 20)
                ->assertSee('Payment Successful');
        });
    }

    public function testAddMultiplePaymentToPurchaseOrder(){
        $this->testCreatePurchaseWithRequiredFieldOnlySingleProduct();
        $this->browse(function (Browser $browser){
            $browser->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(9) > div > div > a:nth-child(1)')
                ->assertSee('Payment')
                ->type('#pos_payment_method > div:nth-child(1) > div:nth-child(1) > div > input', 50)
                ->click('#add_product > section > div > div > div:nth-child(2) > form > div > div.row > div > div > div.pos_payment_method_upper > div.row.justify-content-center.mt-20.no-gutters > a')
                ->type('#pos_payment_method1 > div.row > div:nth-child(1) > div > input', 40)

                ->click('#add_product > section > div > div > div:nth-child(2) > form > div > div.col-lg-12.text-center.pt_15 > div > div.payment_buttons > button.primary_color_btn.payment_btn.multiple-payment-button.green_btn')
                ->waitFor('.toast-message', 20)
                ->assertSee('Payment Successful');
        });
    }

    public function testQuickCashPaymentToPurchaseOrder(){
        $this->testCreatePurchaseWithRequiredFieldOnlySingleProduct();
        $this->browse(function (Browser $browser){
            $browser->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(9) > div > div > a:nth-child(1)')
                ->assertSee('Payment')
                ->click('#add_product > section > div > div > div:nth-child(2) > form > div > div.row > div > div > div.payment_widget_tiket > ul > li:nth-child(5) > a')
                ->click('#add_product > section > div > div > div:nth-child(2) > form > div > div.row > div > div > div.payment_widget_tiket > ul > li:nth-child(6) > a')
                ->click('#add_product > section > div > div > div:nth-child(2) > form > div > div.row > div > div > div.payment_widget_tiket > ul > li:nth-child(6) > a')

                ->click('#add_product > section > div > div > div:nth-child(2) > form > div > div.col-lg-12.text-center.pt_15 > div > div.payment_buttons > button.primary_color_btn.payment_btn.multiple-payment-button.green_btn')
                ->waitFor('.toast-message', 20)
                ->assertSee('Payment Successful');
        });
    }

    public function testReceiveProduct(){
        $this->testCreatePurchaseWithRequiredFieldOnlySingleProduct();
        $this->browse(function (Browser $browser){
            $browser->visit('inventory/purchase-order-recieve')
                ->assertSee('Recieve Purchase Orders')
                ->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(7) > div > div > a')
                ->assertSee('Receive Products')
                ->click('#add_product > section > div > div > div:nth-child(2) > div > div > div > form > div > div > button')
                ->waitFor('.toast-message', 20)
                ->assertSee('Product Has Been Received Successfully');
        });
    }

    public function testShowReceiveHistory(){
        $this->testReceiveProduct();
        $this->browse(function (Browser $browser){
            $browser->click('#dropdownMenu2')
                ->click('#DataTables_Table_0 > tbody > tr > td:nth-child(7) > div > div > a')
                ->assertSee('Purchase Receive');

        });
    }


    public function testVisitPagesWithLogin(){
        $this->browse(function (Browser $browser){
           $browser->loginAs(1)
           ->visit('inventory/inventory/cost-of-goods-history')
           ->assertSee('Product Costing (Sales)')
               ->visit('/inventory/stock-report')
               ->assertSee('Stock List')
               ->visit('inventory/stock-product-info')
               ->assertSee('Product Information')
               ->visit('/purchase/suggested-list')
               ->assertSee('Stock Alert List')
               ->visit('inventory/product-movement')
               ->assertSee('Product Movement');

        });
    }

    public function testVisitPagesWithOutLogin(){
        $this->browse(function (Browser $browser){
           $browser
           ->visit('inventory/inventory/cost-of-goods-history')
               ->assertPathIs('/login')
               ->visit('/inventory/stock-report')
               ->assertPathIs('/login')
               ->visit('inventory/stock-product-info')
               ->assertPathIs('/login')
               ->visit('/purchase/suggested-list')
               ->assertPathIs('/login')
               ->visit('inventory/product-movement')
               ->assertPathIs('/login');

        });
    }

    public function testPurchaseReturn(){
        $this->testReceiveProduct();
        $this->browse(function (Browser $browser){
            $browser->visit('purchase/purchase-return-list')
                ->assertSee('Purchase Return List')
                ->click('#main-content > div.row.justify-content-center > div.col-12 > div > div > ul > li > a')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(9) > div > button')
                ->click('#DataTables_Table_0 > tbody > tr.odd > td:nth-child(9) > div > div > a')
                ->assertSee('Purchase Return')
                ->type('#DataTables_Table_0 > tbody > tr:nth-child(2) > td:nth-child(7) > input.primary_input_field.quantity.quantity1', 1)
                ->click('#main-content > section > div > div > div:nth-child(2) > div > div.row.mt-50 > div > form > div.col-12.mt-5 > div > button')
                ->waitFor('.toast-message', 20)
                ->assertSee('Item Updated Successfully');
        });
    }



}
